### PR TITLE
Remove the DirectPipeline class

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Users who wish to use the DirectPipelineRunner should do so by creating
a new Pipeline with the runner set in the PipelineOptions.

Replace existing uses with TestPipeline, and DataflowAssert if necessary.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @lukecwik

**Comment by tgroh** [comment]
CC: @amitsela This changes the way in which TransformTranslatorTest is executed, but I believe has no semantic impact.

**Comment by lukecwik** [comment]
LGTM

Probably should get rid of DataflowPipeline and all others like it.

**Comment by tgroh** [comment]
Yes. #186 to do that.

**Pull request closed without merging**
