### PR TITLE
[BEAM-687] Upgrade maven-compiler-plugin to fix incremental build

### PR DESCRIPTION
**Pull request by swegner**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

We are hitting an issue with AutoValue and the current version of
maven-compiler-plugin which breaks incremental build. See:
https://issues.apache.org/jira/browse/MCOMPILER-236

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
Please update all the archetype pom.xmls as well.

**Comment by swegner** [comment]
Not quite ready to merge. For some reason, when building `sdks-java-maven-archetypes-starter` twice in a row, I get an unused dependency error:

```
[WARNING] Used undeclared dependencies found:
[WARNING]    org.slf4j:slf4j-api:jar:1.7.14:runtime
```

This only happens on the second `mvn install`, not sure why /cc @peihe

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
LGTM

**Comment by jbonofre** [comment]
By the way, I don't have the dependency issue (I did mvn clean install two times).

**Comment by lukecwik** [comment]
I think this is a clear improvement, will merge and the undeclared dep issue can be tackled when its reproducible.

**Comment by jbonofre** [comment]
+1

**Comment by swegner** [comment]
Sounds good, feel free to merge. I've opened a JIRA issue to track the undeclared dep issue: 

[[BEAM-668] Repeated 'mvn install' fails on beam-sdks-java-maven-archetypes-starter with undeclared dependency error](https://issues.apache.org/jira/browse/BEAM-688)

**Comment by swegner** [comment]
Merged: b5853a6

**Pull request closed without merging**
