### PR TITLE
[BEAM-438] Rename PTransform.apply to PTransform.expand

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Opening this to have a code pointer in dev list discussion.

### CODE REVIEW

**Comment by nssalian** [comment]
Looks good. Thanks @kennknowles

**Comment by davorbonaci** [comment]
LGTM.

But, please discuss at the dev@ mailing list and update the website documentation too.

**Comment by nssalian** [comment]
@davorbonaci looks like @kennknowles  sent a note to dev@. Website documentation would be great as well.

**Comment by kennknowles** [comment]
Yup, I'll wait some time to ensure consensus on the dev list, and I'll update the website.

**Pull request closed without merging**
