### PR TITLE
[BEAM-491]-Reuse context and disable UI in the Spark runner tests

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Rename dataflow to beam.

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @kennknowles 

Generally LGTM but Kenn has opinions here :)

**Comment by amitsela** [comment]
Wow... I was waiting for Jenkins/Travis before Ring you guys 😄 
This should solve the Jenkins issues since all `spark.*` System properties propagate into the `SparkConf`

**Comment by kennknowles** [comment]
LGTM once tests pass. The conservative software engineer in me says that we should stick to public documented properties and use `spark.ui.port=0` but I can suppress that feeling since this property _should_ be public.

**Comment by dhalperi** [comment]
Thanks, merged!

**Pull request merged**
