### PR TITLE
Explicitly set the Runner in TestFlinkPipelineRunner

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This ensures that the created PipelineOptions are valid if the
DirectRunner is not on the classpath.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi 

Succeeds locally with `mvn -P release clean package`

**Comment by tgroh** [comment]
CC: @mxm

**Comment by kennknowles** [comment]
What is the `-P release` about?

**Comment by dhalperi** [comment]
I was testing some other builds with the `release` profile enabled when I sent thomas my exact command line to repro :)

**Comment by mxm** [comment]
LGTM +1 to merge

**Pull request closed without merging**
