### PR TITLE
Fix expression-not-assigned and unused-variable lint warnings

### PR DESCRIPTION
**Pull request by aaltay**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by aaltay** [comment]
@charlesccychen Could you review this please?

**Comment by charlesccychen** [comment]
Thanks!  This LGTM.  I expected more of the "expression-not-assigned" lint errors--were all the other instances already correctly marked with the pylint disable?

**Comment by aaltay** [comment]
Thank you. Yes, all other places are already marked with pylint disable.

**Comment by aaltay** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Merged

**Pull request merged**
