### PR TITLE
Move native TextFileWriter to use GcsIO for writing

### PR DESCRIPTION
**Pull request by charlesccychen**

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by charlesccychen** [comment]
Thanks! R: @dhalperi

**Comment by dhalperi** [comment]
LGTM

**Comment by dhalperi** [comment]
Merged, close at leisure

**Comment by charlesccychen** [comment]
Thanks!

**Pull request closed without merging**
