### PR TITLE
Set runtime scope for Dataflow runner dep on runners-core

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @davorbonaci or @dhalperi

**Comment by davorbonaci** [comment]
Already caught a suspicious depenendecy:

    runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/sdk/util/GroupAlsoByWindowViaWindowSetDoFn.java:[33,40] package org.apache.beam.runners.core does not exist

**Comment by dhalperi** [comment]
Believe that file can be removed now.

**Comment by kennknowles** [comment]
I think putting it back in the old namespace is simplest.

**Comment by kennknowles** [comment]
Once the fragility of the service to this namespacing is fixed, we can just do the move along with all the rest of runners-core.

**Comment by kennknowles** [comment]
False: it is the new name that must remain. I've put it back.

**Comment by davorbonaci** [comment]
LGTM on the current version (runtime scope + removal of `org.apache.beam.sdk.util.GroupAlsoByWindowViaWindowSetDoFn`).

Please squash / self-merge, once test pass. Manual streaming test would be good too.

**Pull request merged**
