### PR TITLE
[BEAM-860] Move Apache RAT license check out of release profile

### PR DESCRIPTION
**Pull request by mizitch**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
- [x] Make sure the PR title is formatted like:
  `[BEAM-<Jira issue #>] Description of pull request`
- [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
     Travis-CI on your fork and ensure the whole test matrix passes).
- [x] Replace `<Jira issue #>` in the title with the actual Jira issue
     number, if there is one.
- [x] If this contribution is large, please file an Apache
     [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
---

Move Apache RAT license check out of release profile. It runs quickly, so can run as a part of normal mvn verify phase. Will make it so missing licenses are caught locally more easily.

Tested this locally by removing the license from a file and running 'mvn clean verify' as well as 'mvn clean verify -P release'. Now both fail, whereas previously, only 'mvn clean verify -P release' failed.

See discussion at https://github.com/apache/incubator-beam/pull/1199#issuecomment-256802048

Would you mind looking @dhalperi ? Sorry to send 100% of my two PRs so far to you, but you do have context on this one...

### CODE REVIEW

**Comment by mizitch** [comment]
Travis failures are pre-existing recurring ones related to Spark runner compilation and Spark runner test failure

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by dhalperi** [comment]
Spoke with some other folks in person. I think we want to keep the default `mvn verify` profile to only the subsets of commands that a Beam **user** wants to run. To that end:

* we should leave RAT off
* we should remove checkstyle and other similar things
* we should document very concisely in the contribution guide what command Jenkins precommit runs (maybe it should be `-Pprecommit` ?) for contributors who want to test locally

**Comment by jbonofre** [comment]
+1, it makes sense to me.

**Comment by mizitch** [comment]
Makes sense, closing this PR, some further commentary on the JIRA: https://issues.apache.org/jira/browse/BEAM-860

**Pull request closed without merging**
