### PR TITLE
[BEAM-753] Pin the version of dependencies

### PR DESCRIPTION
**Pull request by aaltay**
Pin the version of all dependencies between a known good version and up to (not including) the next major version.

### CODE REVIEW

**Comment by aaltay** [comment]
R: @charlesccychen

**Comment by charlesccychen** [comment]
Thanks! LGTM.

**Comment by charlesccychen** [comment]
R: @robertwb 

Adding Robert for merge.

**Comment by aaltay** [comment]
Thank you.

**Comment by aaltay** [comment]
This was not merged to the python-sdk branch, reopening it.

**Comment by robertwb** [comment]
And now it's in the official apache branch.

**Comment by aaltay** [comment]
Thank you!

**Pull request closed without merging**
