### PR TITLE
[BEAM-498] Rename DoFn to OldDoFn, DoFnWithContext to DoFn, and port some examples

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @bjchambers. Since there was general approval on the mailing list and these changes are mostly trivial, I'm mostly just asking Ben for a double-check since he has the most technical depth on this.

### CODE REVIEW

**Comment by kennknowles** [comment]
We need to get this to an LGTM state as far as code and unit tests, and then there will be a little dance with the integration testing story. It may save a lot of effort to allow some integration testing failure as we update things that link in the SDK, or we might be able to hack a simple solution.

**Comment by kennknowles** [comment]
The code is now to the point where the only failures are integration tests with the Dataflow service.

**Comment by kennknowles** [comment]
R: @dhalperi perhaps, too.

It is rather mechanical but large-scale. I'd love to get it in when things get green so that further changes can be incremental.

**Comment by kennknowles** [comment]
Also: everything will be ported _back_ to `DoFn` so there is little use in fixing grammar, etc.

**Comment by dhalperi** [comment]
LGTM

**Pull request closed without merging**
