### PR TITLE
[BEAM-392] Update flink runner to use flink version 1.0.3

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by iemejia** [comment]
I also cleaned some references to the old runner name (FlinkPipelineRunner).

**Comment by iemejia** [comment]
Hi, can some of you guys check if this is ok, @aljoscha @mxm. Thanks.

**Comment by aljoscha** [comment]
Thanks for your work, LGTM.

**Comment by mxm** [comment]
LGTM. Thanks for updating!

**Comment by iemejia** [comment]
As you agree, can you please merge it. I am not a committer (but I hope to become one soon).

**Pull request closed without merging**
