### PR TITLE
DRAFT [BEAM-77] Move remaining GCP IO to google-cloud-platform

### PR DESCRIPTION
**Pull request by dhalperi**
TODO list:

- [x] Move BigQueryIO and tests
- [x] Move PubSubIO and tests
- [x] Move DatastoreIO and tests
- [ ] Extract GCSOperations and related code from FileBasedSource/FileBasedSink
- [ ] Add ServiceLoader logic for IOChannelFactories
- [ ] Move Transport, RetryHttpInitializer, Credentials
- [ ] Fixup any runners that are affected by moves.

### CODE REVIEW

**Comment by dhalperi** [comment]
R-future: @lukecwik 

For any early comments you may want to make.

WILL NOT MERGE until all checkboxes in PR desc are checked, and other pre-merge checks are done.

**Comment by jbonofre** [comment]
At first glance, it looks good to me for BigQueryIO. I'm running complete test now.

**Comment by dhalperi** [comment]
hi @jbonofre  -- thanks.

note that this is an in-progress PR and will be in various stages of brokenness as I chug through the TODO list.

**Comment by dhalperi** [comment]
Closing since this needs more work.

**Pull request closed without merging**
