### PR TITLE
[BEAM-841] Add maven-gpg-plugin to support releases preparation

### PR DESCRIPTION
**Pull request by wikier**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
- [X] Make sure the PR title is formatted like:
  `[BEAM-<Jira issue #>] Description of pull request`
- [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
     Travis-CI on your fork and ensure the whole test matrix passes).
- [X] Replace `<Jira issue #>` in the title with the actual Jira issue
     number, if there is one.
- [X] If this contribution is large, please file an Apache
     [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This patch makes use of `maven-gpg-plugin` to produce signatures and checksum of a release, addressing [BEAM-841](https://issues.apache.org/jira/browse/BEAM-841) problems.

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Thanks Sergio. Gonna check but I think it's already done.

**Comment by jbonofre** [comment]
@wikier I don't think this PR makes sense as the pluginManagement from the Apache POM already does the gpg sign:

http://repo.maven.apache.org/maven2/org/apache/apache/18/apache-18.pom

```
<!--
 We want to sign the artifact, the POM, and all attached artifacts 
-->
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-gpg-plugin</artifactId>
<executions>
<execution>
<id>sign-release-artifacts</id>
<goals>
<goal>sign</goal>
</goals>
</execution>
</executions>
</plugin>
```

I would close this PR (I let a comment in the Jira as well).

**Comment by wikier** [comment]
@jbonofre, this comes because I saw the artifacts were manually signed in one of the previous releases. In addition, the `pluginManagement` part solves an old issue of the ASF parent pom signing the checksums and signatures, which may be already solved in the latest releases.

**Comment by jbonofre** [comment]
I think we are good now as we use Apache POM 18 and we leverage the Apache release profile already using gpg plugin.

**Comment by wikier** [comment]
Then I agree we can close it.

**Pull request closed without merging**
