### PR TITLE
BEAM-635- Release 0.2.0-incubating - Support Flink Release Version 1.1.2

### PR DESCRIPTION
**Pull request by sumitchawla**
Support Latest Flink Release of version of 1.1.0 in BEAM 0.2.0-incubating release
0.2.0-incubating has just been release. It will be great if we can add support for latest Flink 1.1.0 release.

### CODE REVIEW

**Comment by mxm** [comment]
Hi @sumitchawla. Looks good! I'm not sure whether there will be a minor release 0.2.1-incubating. Flink 1.1.2 is already supported in the latest version 0.3.0-incubating-SNAPSHOT which also contains many improvements and fixes. The next release should be coming out pretty soon. Is there anything stopping you from using the latest snapshot version?

**Comment by dhalperi** [comment]
R: @mxm

**Comment by dhalperi** [comment]
Sumit, not sure what the status is here. Looks like this, or part of this, has been merged?  https://github.com/apache/incubator-beam/blob/master/runners/flink/pom.xml#L42

**Comment by sumitchawla** [comment]
@dhalperi I ended up using 0.3.0-SNAPSHOT-DATE commit to absorb Flink 1.1.2

**Comment by mxm** [comment]
@dhalperi This PR was opened against the `release-0.2.0-incubating` branch to bump the Flink version in a minor release. That would change the major version of Flink in a minor release of Beam. We quickly discussed this on the mailing list and figured it would be too much for a minor release.

@sumitchawla Thanks for your understanding. Could you close the PR?

**Comment by sumitchawla** [comment]
Ended up using 0.3.0-SNAPSHOT-DATE commit to absorb Flink 1.1.2

**Pull request closed without merging**
