### PR TITLE
Fixing the custom ptransform snippet in the comments

### PR DESCRIPTION
**Pull request by aaltay**

### CODE REVIEW

**Comment by aaltay** [comment]
R: @charlesccychen 

Please review. (Note that the change entirely happens in a docstring if it is not clear from truncated file diff ui.)

**Comment by charlesccychen** [comment]
Thanks, LGTM.

R: @dhalperi (thanks Dan!)

**Comment by dhalperi** [comment]
LGTM, merged. Close PR at your leisure.

**Comment by aaltay** [comment]
Thanks!

**Pull request closed without merging**
