### PR TITLE
[BEAM-80] Change ReduceFnRunner to process elements before timers

### PR DESCRIPTION
**Pull request by peihe**
This change will allow ReduceFnRunner to add more elements to firing panes.
For example, when elements and its end of window timer come in the same bundle, ReduceFnRunner now can include these elements in the ON_TIME pane.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @kennknowles

**Comment by bjchambers** [comment]
Could you elaborate on why this change is necessary? It seems like if we have both elements and timers arriving in a given bundle, that processing the elements before the timer means that any pane produced by the timer will be larger. Larger panes potentially means fewer panes, so it seems like it would be good to maintain that property.

Switching the order (like this) means that we could fire an ON_TIME pane (for instance), even though we have additional data that could be added to it.

**Comment by peihe** [comment]
bjchambers@ yes, I am changing it to process elements first.

The problem you described (ON_TIME pane and dropped elements) is exactly the one I want to fix.

**Comment by bjchambers** [comment]
@peihe Rather than describing this as "swap", can you put in the description the order that you're switching to and why? Thanks!

**Comment by peihe** [comment]
updated CL description

**Pull request merged**
