### PR TITLE
Remove overrides of isStreaming() and getAppName() in SparkPipelineOptions

### PR DESCRIPTION
**Pull request by peihe**
isStreaming() is already default to false implicitly, since it is not set.
getAppName() defaults to the name of the class that constructs the PipelineOptions via the PipelineOptionsFactory.

I think both should work in Spark. And, I see no reason to override them.

### CODE REVIEW

**Comment by peihe** [comment]
R: @amitsela @lukecwik

**Comment by amitsela** [comment]
Can also remove https://github.com/apache/incubator-beam/blob/master/runners/spark/src/main/java/org/apache/beam/runners/spark/SparkStreamingPipelineOptions.java#L40 in that case.

**Comment by peihe** [comment]
Done - removed getAppName in SparkStreaming options.

**Comment by lukecwik** [comment]
Default values based upon which interface you invoke is generally not a good idea as the value will be "set" based upon which interface you invoke. Thus we should remove isStreaming() from SparkStreamingPipelineOptions.

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
Waiting for Jenkins/Travis and will merge.

**Pull request closed without merging**
