### PR TITLE
Clarifies that 'TextFileSource' only supports UTF-8 and ASCII encodings.

### PR DESCRIPTION
**Pull request by chamikaramj**

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @charlesccychen

**Comment by charlesccychen** [comment]
LGTM.

**Comment by chamikaramj** [comment]
Thanks Charles.

R: @bjchambers

**Comment by dhalperi** [comment]
Merged; please manually close PR.

**Comment by chamikaramj** [comment]
Thanks Dan.

**Pull request closed without merging**
