### PR TITLE
[BEAM-286] Reorganize flink runner module to follow other runners str…

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Reorganize flink runner module to follow other runners structure.

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @mxm 
R: @aljoscha

**Comment by aljoscha** [comment]
Since this is mostly touching POMs and removing examples it shouldn't clash to much with #343. You'll probably have to coordinate with with @jasonkuster on #345.

LGTM to me, since it's mostly removing examples that were originally copied from the Google Dataflow (not a mistake) code base. Let's wait and see what @mxm has to say.

**Comment by jasonkuster** [comment]
Looks like this is a superset of the flink stuff I'm doing in #345. Since this makes more changes, I'm happy to revert the flink changes I've made, wait for this to go in, and then rebase to pick this up.

**Comment by jbonofre** [comment]
@aljoscha Thanks for the update.
@jasonkuster up to you, but maybe we can start with this "move" and then apply your change.

**Comment by mxm** [comment]
I commented on the JIRA issue. I don't think we can merge this PR. However, we could get rid of some of the examples in a separate issue/pull request.

**Comment by davorbonaci** [comment]
Triage: 0.1.0-incubating, release blocking.

Let's continue the discussion in JIRA.

**Comment by jbonofre** [comment]
For now, I'm closing this PR.

**Pull request closed without merging**
