### PR TITLE
[BEAM-398] Mark JAXBContext volatile in JAXBCoder

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by tgroh** [comment]
R: @swegner

**Comment by swegner** [comment]
Hey look what I found: [[BEAM-398] JAXBCoder uses incorrect Double-Checked Locking](https://issues.apache.org/jira/browse/BEAM-398)

Assuming this fixes it, please also remove the [`findbugs-filter.xml` entries](https://github.com/apache/incubator-beam/blob/master/sdks/java/build-tools/src/main/resources/beam/findbugs-filter.xml#L34).

**Comment by swegner** [comment]
Please update [`findbugs-filter.xml`](https://github.com/apache/incubator-beam/blob/master/sdks/java/build-tools/src/main/resources/beam/findbugs-filter.xml#L34) to remove the exclusion for this. Otherwise LGTM.

**Comment by tgroh** [comment]
Updated to mark the context as volatile (only)

PTAL

@swegner

**Comment by lukecwik** [comment]
LGTM

**Pull request closed without merging**
