### PR TITLE
[BEAM-1185] Remove the word 'Pipeline' from the PipelineRunner subclasses

### PR DESCRIPTION
**Pull request by aaltay**
The change is mostly mechanical, except for the runner.py (and its
test). Temporarily added a way for not breaking existing users of this
runners. After a grace period after the new year, I will remove that
piece of code.

### CODE REVIEW

**Comment by aaltay** [comment]
R: @robertwb

**Comment by robertwb** [comment]
LGTM, but looks like it needs a rebase. 

Should we take this chance to also deprecate Blocking as a runner as Java did?

**Comment by aaltay** [comment]
Thank you @robertwb. Rebased and added a depracated warning for BlockingDataflowRunner. I will work work actually removing as part of https://issues.apache.org/jira/browse/BEAM-759.

**Comment by aaltay** [comment]
Travis errors is due to this, https://issues.apache.org/jira/browse/BEAM-1090. I am working on that separately. The test is flaky.

**Comment by robertwb** [comment]
LGTM

**Comment by aaltay** [comment]
Thank you.

**Pull request closed without merging**
