### PR TITLE
[BEAM-502] Updates JSON to/from Python object conversion to handle null/None values.

### PR DESCRIPTION
**Pull request by chamikaramj**
Updates Python object to JSON conversion to handle 'None' values.

Updates JSON to Python object conversion to return 'None' for JSON null objects instead of '[]'.

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM

**Comment by chamikaramj** [comment]
Thanks.

R: @dhalperi

**Comment by dhalperi** [comment]
LGTM, merged, close at will (if github doesn't close it for me)

**Comment by chamikaramj** [comment]
Thanks Dan.

**Pull request merged**
