### PR TITLE
[BEAM-22][BEAM-243] Execute NeedsRunner tests in the DirectRunner module

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
This ensures that all tests that depend on a pipeline are executed in a module
capable of executing them.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
I think inheritance works so that you can simply use the `NeedsRunner` category.

**Comment by tgroh** [comment]
Done.

**Comment by tgroh** [comment]
This build will fail until https://github.com/apache/incubator-beam/pull/429 is merged, as it includes https://github.com/apache/incubator-beam/pull/418, which also requires #429.

**Comment by kennknowles** [comment]
Tomorrow all the prerequisites should be in. What is the story with the last commit, d427fb0?

**Comment by tgroh** [comment]
I'm not 100% sure, but there may be the potential for a leak due to how we're constructing ExecutorServices, and that change would plug that leak (and regardless is probably a slightly superior invocation of feedbacks) (but I missed removing an export and thus build failures)

**Comment by tgroh** [comment]
The earlier Travis failures seem to have been because Travis dislikes me. 3 additional successes

https://travis-ci.org/tgroh/incubator-beam/builds/136579107
https://travis-ci.org/tgroh/incubator-beam/builds/136579169
https://travis-ci.org/tgroh/incubator-beam/builds/136579179

@kennknowles

**Comment by kennknowles** [comment]
LGTM. Will merge since the test timing looks reasonable.

**Pull request merged**
