### PR TITLE
[BEAM-186] Fix pubsub injector for streaming examples

### PR DESCRIPTION
**Pull request by herohde**

### CODE REVIEW

**Comment by herohde** [comment]
R: @bjchambers

**Comment by bjchambers** [comment]
Also update the example archetypes?
https://github.com/apache/incubator-beam/blob/master/sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/src/main/java/WindowedWordCount.java
https://github.com/apache/incubator-beam/blob/master/sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/src/main/java/common/DataflowExampleUtils.java

**Comment by herohde** [comment]
It's already in the CL.

**Comment by bjchambers** [comment]
Doh. Sorry.

LGTM.

**Comment by herohde** [comment]
Thanks Ben!

**Pull request closed without merging**
