### PR TITLE
[BEAM-77] Directory reorganization

### PR DESCRIPTION
**Pull request by davorbonaci**
This pull requests reorganizes directory structure. This is the first step towards the organization proposed in the document shared a few weeks ago.

We'll try to merge this quickly to limit complicated merges. This shouldn't prevent feedback -- please keep it coming -- we'll just address such feedback in a follow-up commit.

This is the first step only, and there are many things that are incomplete:

* Some READMEs may now become out-of-date.
* We need a few more aggregator `pom.xml` files; they are not added yet.

There's nothing in this pull request that renames Dataflow to Beam; it just moves files around without changing the content.

Aside: `asfgit` is very slow; the pull request pulls in a few commits merged into Apache repository that the GitHub mirror hasn't picked up yet. This should be properly rebased prior to merge.

R: @dhalperi; everyone else very welcome.

### CODE REVIEW

**Comment by kennknowles** [comment]
Note on your aside: you will not need to rebase. The commits d510b4e, 8bce693, and 9f8dd18 will simply be added to GitHub and the master pointer updated. Then it will automatically look like the PR you intend.

**Comment by kennknowles** [comment]
Also, performing an "offline" review of the new changes and pushing is perfectly safe. I found it easiest to read the changes via `git diff --stat apache/master github/pr/72`.

LGTM, though the Jenkins failure looks like it might be a real breakage of some sort.

**Comment by dhalperi** [comment]
The changes LGTM.

Travis passes fully, but Jenkins fails only on the archetypes. I spent an hour trying to fix, but was not successful, and it looks like the cause may be related to the `-incubating` suffix and artifact resolution that was discussed ad nauseum on the list.

I think that in the interest of getting the big move in we should go ahead and merge, and fixup the Jenkins archetype issue as we go. It may require updating the version of Maven in Jenkins.

**Comment by dhalperi** [comment]
asfgit is still slow, but this has been merged.

Travis is still useful as a signal of build success, and jenkins results should be manually inspected.

**Comment by dhalperi** [comment]
And I've filed https://issues.apache.org/jira/browse/BEAM-148 for the Jenkins test issue.

**Comment by davorbonaci** [comment]
Thanks @dhalperi and @kennknowles.

**Comment by mxm** [comment]
LGTM from the Flink side.

**Pull request merged**
