### PR TITLE
[BEAM-22] Switch the Default PipelineRunner

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Use the InProcessPiplineRunner (pending rename) as the default runner.
The InProcessPipelineRunner implements the beam model, including support
for Unbounded PCollections.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @davorbonaci 
CC: @kennknowles @bjchambers

**Comment by davorbonaci** [comment]
LGTM. Merge in-progress.

**Comment by dhalperi** [comment]
This broke Travis. Expected?

https://issues.apache.org/jira/browse/BEAM-203?filter=-2

**Comment by dhalperi** [comment]
Also does not work on my laptop. Machine runs out of threads.

**Comment by davorbonaci** [comment]
Not expected. @tgroh, can you take a peek?

**Pull request merged**
