### PR TITLE
Remove remaining window parameterization from triggers and their tests

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
This is a follow-up to #168, getting rid of a couple straggler parameterizations and their uses in tests.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @bjchambers

**Comment by bjchambers** [comment]
LGTM but wait for travis.

I assume that you did a grep for static methods in the triggers that have a generic parameter and/or classes with a generic, so we have a reasonable belief we got everything. Thanks!

**Comment by bjchambers** [comment]
LGTM but merge conflicts.

**Comment by kennknowles** [comment]
Resolved conflicts. Will merge this in once CI is green.

**Pull request merged**
