### PR TITLE
merge master into python-sdk

### PR DESCRIPTION
**Pull request by aaltay**
Merge master branch into python-sdk branch. We will do this on a regular basis going forward to keep python-sdk development branch in sync with the master.

Merging changes since 6/20/2016 (#498). 

Used theirs strategy for merging:
`git merge --strategy-option theirs origin/master`

There was a single non-trivial merge conflict for `.travis.yml`

and manually removed these files (that were already deleted in master):

```
runners/direct-java/src/main/java/org/apache/beam/runners/direct/EvaluatorKey.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/AvroIOShardedWriteFactoryTest.java
runners/direct-java/src/test/java/org/apache/beam/runners/direct/TextIOShardedWriteFactoryTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/io/DataflowAvroIOTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/io/DataflowPubsubIOTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/io/DataflowTextIOTest.java
runners/google-cloud-dataflow-java/src/test/java/org/apache/beam/runners/dataflow/transforms/DataflowDisplayDataEvaluator.java
```

### CODE REVIEW

**Comment by aaltay** [comment]
Please review:
@chamikaramj - especially for Python
@dhalperi - especially for git commands I used, and integrity of the branch.

**Comment by aaltay** [comment]
This contains a bad merge. I see https://github.com/apache/incubator-beam/commit/1f449881a88d9927b507ad46d0004e3c9805513a in the merged commit list, but its changes were overwritten.

**Comment by aaltay** [comment]
R: @kennknowles  Please review..

**Comment by kennknowles** [comment]
LGTM. Confirmed:

 - `git diff python-sdk..HEAD` has a good diff to `.travis.yml` and the rest of the changes are in the Java codebase, README, poms. By "good" diff I mean that it is quite reasonable to disable the Java tests as long as Python is on a feature branch.
 - `git diff master..HEAD` has a good diff to `.travis.yml` and the rest of the changes are in the Python codebase.

Will merge and push this up to `python-sdk`.

**Comment by aaltay** [comment]
Ken thanks a lot for detailed verification.

**Pull request merged**
