### PR TITLE
[BEAM-206] FileBasedSink: improve parallelism in GCS copy/remove

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
Unit tests?

**Comment by dhalperi** [comment]
Refactored and unit tested what i can. Still no excellent way to unit test BatchRequest. Not only can I not mock the `.batch()` call to create a batch, I also can't mock the `BatchRequest` object itself. And there's no getters on the BatchRequest that will let me inspect the request payloads.

I did run a job: 2016-08-21_23_12_50-10923575837433736309

Took 28s after side input initialization to copy the 10K files.

**Comment by lukecwik** [comment]
LGTM

**Pull request closed without merging**
