### PR TITLE
[BEAM-1143] More escaping in Jenkins timestamp spec

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

The current timestamp spec is insufficiently escaped. The failure mode is that relative timestamps are shown instead of a readable standard datetime.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @jasonkuster

**Comment by kennknowles** [comment]
Because this is a form of breakage that I just introduced, I will pursue review after merging, to make the build clean.

**Comment by kennknowles** [comment]
R: @davorbonaci as committer.

**Comment by davorbonaci** [comment]
LGTM

**Comment by jasonkuster** [comment]
LGTM

**Pull request merged**
