### PR TITLE
[BEAM-270] Support Timestamps/Windows in Flink Batch

### PR DESCRIPTION
**Pull request by aljoscha**
This change sits on top of #291 

With this we can run all of the `RunnableOnService` tests on the Flink batch runner. Almost all of our own Flink-specific IT cases fail now because they verified the older, non-complete support for the Beam model. I did not remove them, since we should discuss whether we want to keep them, or keep only those that test a specific integration with Beam. If we want to keep them they have to be fixed.

For now `CombineTest.testSessionsCombineWithContext` fails. I'm inserting a pre-shuffle combine phase but with merging windows the correct, final window in which an element will reside is not yet know in the pre-shuffle combine. This means that we don't get the correct side input for those values in the `CombineFnWithContext`. To fix the failing test I can get rid of the pre-shuffle combine, this means that we have more network traffic but are correct. What are the thought on this?

For GroupByKey/Combine.PerKey I'm doing a shuffle by key and then an in-memory pass over the windows. For non-merging windows this could also be changed to do a shuffle by key-and-window but then we would have to explode all windows on the send side.

**This is the text from the commit in question:**

   [BEAM-270] Support Timestamps/Windows in Flink Batch
    
    With this change we always use WindowedValue<T> for the underlying Flink
    DataSets instead of just T. This allows us to support windowing as well.
    
    This changes also a lot of other stuff enabled by the above:
    
     - Use WindowedValue throughout
     - Add proper translation for Window.into()
     - Make side inputs window aware
     - Make GroupByKey and Combine transformations window aware, this
       includes support for merging windows. GroupByKey is implemented as a
       Combine with a concatenating CombineFn, for simplicity
    
    This removes Flink specific transformations for things that are handled
    by builtin sources/sinks, among other things this:
    
     - Removes special translation for AvroIO.Read/Write and
       TextIO.Read/Write
     - Removes special support for Write.Bound, this was not working properly
       and is now handled by the Beam machinery that uses DoFns for this
     - Removes special translation for binary Co-Group, the code was still
       in there but was never used
    
    With this change all RunnableOnService tests run on Flink Batch.

R: @mxm for Flink review
R: @kennknowles, you are probably interested in how the shuffle/reduce works

### CODE REVIEW

**Comment by kennknowles** [comment]
Will this now succeed even if you drop a0376ff? That commit causes unrelated issues, so if your change now makes that obsolete, we could drop it and merge this instead of #291.

**Comment by aljoscha** [comment]
Yes, it will work without that. All the other commits that change from `Void` to `int` are also obsolete. Same for the commits that introduce the special categories, but those might be useful for other runners. I'll make a PR that includes only the required commits from here, these should be:
 - Add TestFlinkPipelineRunner to FlinkRunnerRegistrar
 - Configure RunnableOnService tests for Flink in batch mode
 - Fix Dangling Flink DataSets
 - Add hamcrest dep to Flink Runner
 - Fix faulty Flink Flatten with empty PCollectionList
 - Remove unused threadCount from integration tests (not really required, but good)
 - Disable Flink streaming integration tests for now
 - Special casing job exec AssertionError in TestFlinkPipelineRunner
 - [BEAM-270] Support Timestamps/Windows in Flink Batch 
 - fixup, remove WordCount changes, remove KvCoderComparator code

How should we squash those. Or should we include each commit separately?

**Comment by mxm** [comment]
Great work @aljoscha 👍 I think it is fine to leave the relevant commits. You could squash all test-related commits into one commit. I'd like to take a look once you've opened the new PR.

**Comment by aljoscha** [comment]
I'll open a new PR with only the relevant commits in a sec. There is still the question of the failing Flink specific tests. I can fix them now, but if we remove them anyways because most stuff is now covered by the RunnableOnService tests then I'd rather not do it.

This is the list of tests that we currently have for the batch runner:
```
AvroITCase
FlattenizeITCase
FlinkRunnerRegistrarTest
JoinExamplesITCase
MaybeEmptyTestITCase
ParDoMultiOutputITCase
PipelineOptionsTest
ReadSourceITCase
RemoveDuplicatesEmptyITCase
RemoveDuplicatesITCase
SideInputITCase
TfIdfITCase
WordCountITCase
WordCountJoin2ITCase
WordCountJoin3ITCase
WriteSinkITCase
```

I would say that we only have to keep these:
```
FlinkRunnerRegistrarTest
FlinkTestPipeline
PipelineOptionsTest
ReadSourceITCase
WriteSinkITCase
```

These would basically test that source/sink integration and reading/writing from/to the outside world are correct. (The `RunnableOnTest` tests never have a sink, they always verify using `PAssert`, if I'm not mistaken) And also the plumbing of the runner and the pipeline options is verified. All the other stuff is already tests more thoroughly by the `RunnableOnService` tests.

**Comment by aljoscha** [comment]
It seems there is still a small problem that leads to one test failing, I have not yet pinpointed it. I'll keep you posted.

**Comment by aljoscha** [comment]
I finally found the bug and created a cleaned version in #335

**Comment by kennknowles** [comment]
So is this PR defunct?

**Comment by aljoscha** [comment]
Yes, sorry, I left it open for the messages and history of commits.

**Pull request closed without merging**
