### PR TITLE
Use Apache's release to produce the source release

### PR DESCRIPTION
**Pull request by dhalperi**
And use final-name to override the artifact and directory names

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @davorbonaci

**Comment by jbonofre** [comment]
And what do we do for future binary distributions ?

Testing the output and content.

**Comment by jbonofre** [comment]
I'm checking if the artifactId is correct in the .m2/repository (and used for the deploy). It's good for target folder for sure, but not sure for the maven deploy. Checking.

**Comment by jbonofre** [comment]
If we agree to do the rename manually of the source distribution and all related signature files, that's OK.

IMHO, it's better to have apache-beam...zip on dist.apache.org (as you can see for other projects on dist.apache.org/release like spark, karaf, etc).

**Comment by jbonofre** [comment]
As reminder, the purpose of the distributions module was:
1. use apache-beam as artifactId allowing us to directly have the correct filename in the maven coordinates used for the deploy (apache-beam...zip)
2. prepare the future to create binary distributions (using a specific assembly descriptor) like apache-beam-java-spark-bin...zip

**Comment by jbonofre** [comment]
Just checked with the rename of the zip file: the signature is still valid:

```
gpg --verify beam-parent-0.2.0-incubating-SNAPSHOT-source-release.zip.asc foobar.zip 
gpg: Signature made Wed 08 Jun 2016 09:15:54 PM CEST using RSA key ID C8282E76
gpg: Good signature from "Jean-Baptiste Onofré <jbonofre@apache.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1AA8 CF92 D409 A733 93D0  B736 BFF2 EE42 C828 2E76
```

So, I will update the release guide to document the renaming step before uploading to dist.apache.org.

LGTM

**Comment by davorbonaci** [comment]
LGTM. Merging.

**Pull request merged**
