### PR TITLE
[BEAM-1087] Fix inconsistent pickle from dill when dumping the session

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This PR tries to fix https://github.com/GoogleCloudPlatform/DataflowPythonSDK/issues/31 with adding a reduce hook to the Step and Job classes. We also need to modify the dump session so that the pickling is consistent due to https://github.com/uqfoundation/dill/issues/195. 

R: @robertwb PTAL

### CODE REVIEW

**Comment by sb2nov** [comment]
R: @robertwb PTAL

**Comment by robertwb** [comment]
Ideally we shouldn't be pickling any live objects from apiclient.py... can this be avoided?

**Comment by sb2nov** [comment]
There is a dangerous looking solution in https://github.com/uqfoundation/dill/issues/66 which could be useful in ignoring the objects in apiclient but I think that might add complexity compared to the adding reduce methods to the two classes. Thoughts ?

**Comment by robertwb** [comment]
I think this is good for now, and in general it'd be better to have more robust session (or at least __main__ module) pickling. LGTM

**Comment by sb2nov** [comment]
Thanks. Yeah, having a more robust pickling story would be great.

**Pull request closed without merging**
