### PR TITLE
Estimate sizes

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
- [ ] Make sure the PR title is formatted like:
  `[BEAM-<Jira issue #>] Description of pull request`
- [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
     Travis-CI on your fork and ensure the whole test matrix passes).
- [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
     number, if there is one.
- [ ] If this contribution is large, please file an Apache
     [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @charlesccychen

**Comment by charlesccychen** [comment]
Thanks for noticing this inconsistency.  LGTM.

**Comment by robertwb** [comment]
Thanks. Will merge once I verify all tests pass on the buildbots.

**Comment by robertwb** [comment]
Actually, I'm going to have to look at this a bit more. It appears there's cases where the [container] coder is PickleCoder, but the container **can't** be pickled, but the elements can be pickled with this PickleCoder. So the wrong behavior is needed :(.

**Comment by robertwb** [comment]
PTAL

**Comment by charlesccychen** [comment]
Thanks! LGTM.

**Comment by charlesccychen** [comment]
Jenkins failure looks unrelated.

**Pull request closed without merging**
