### PR TITLE
Code cleanup in BigQueryIO

### PR DESCRIPTION
**Pull request by peihe**
1. Use toJsonString() to avoid try catch
2. add getTableWithDefaultProject in BigQuery.Write

### CODE REVIEW

**Comment by peihe** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Please add a test that would have caught this bug.

**Comment by dhalperi** [comment]
Pei: status?

**Comment by peihe** [comment]
I think you are referring to the executing project bug. It is fixed in https://github.com/apache/incubator-beam/pull/352, and the unit test is in https://github.com/apache/incubator-beam/pull/376.

This PR is just come code cleanup.

Ready for review.

**Pull request closed without merging**
