### PR TITLE
Update transitive dependencies for Apex 3.5.0 snapshot version.

### PR DESCRIPTION
**Pull request by tweise**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
R @kennknowles

### CODE REVIEW

**Comment by tweise** [comment]
@kennknowles I just found the build failure and it is due to changes in Apex. We are waiting for the 3.5.0 release to update the dependency of he Apex runner.

**Comment by tweise** [comment]
Please hold on with merging the PR until the snapshot is updated.

**Comment by kennknowles** [comment]
OK, I will wait. Can you just remove the tags and add the dependencies?

**Comment by tweise** [comment]
This setup is to ensure that the transitive dependencies are used as declared by Apex (vs. repeating them). The real issue is that we depend on the snapshot, and that's the result of the issue identified in the jenkins environment as part of #540

**Comment by tweise** [comment]
@kennknowles I removed the version numbers so that it works with old and new. Will put those back when moving to final release. Please merge.

**Comment by kennknowles** [comment]
I see what you mean about what you are trying to accomplish. So it doesn't make sense for `ApexRunner` to depend on specific versions of `com.datatorrent:netlet`, `commons-io`, or `hadoop-common`.

But the runner itself, just by linking to particular classes and methods, should at least have a version _range_ for these dependencies that includes those APIs actually referenced. The transitive dependency should presumably fall within that range, but it should work with all compatible transitive deps. Is this not the case?

I don't think we should have compile-time references to classes and methods without declared dependencies except in very special circumstances.

**Comment by tweise** [comment]
From what I understand, there is no way to express what I'm looking for with the version ranges:

https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification

I want to say  "use the transitive dependency at the version it was defined at". I found the ignoredUsedUndeclaredDependency tags providing exactly that. Each tag is the equivalent of a white listed transitive dependency. If it wasn't done that way, the changes in the snapshot dependencies would have gone unnoticed and there would potentially be a runtime conflict.

Would you be OK pulling in this change to unblock others (BEAM-1043) while we further discuss alternative solutions?

**Comment by kennknowles** [comment]
OK, LGTM to unblock precommit issues.

**Pull request closed without merging**
