### PR TITLE
[BEAM-395] KafkaIO tests should be marked 'NeedsRunner'

### PR DESCRIPTION
**Pull request by rangadi**
KafkaIO Tests are currently marked as 'RunnableOnService', which implies the tests can run on any beam runner. This is not correct. 

Though the tests are not runner dependent per se, they depend on mocks for Kafka consumer and kafka producer. That requires the tests to be local to a JVM. These tests can only run on single JVM runners like DirectRunner.

These tests should be marked 'NeedsRunner' for now.
-----------
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by rangadi** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
LGTM, will merge when green.

**Comment by dhalperi** [comment]
Does not pass checkstyle, Please take a look @rangadi

**Comment by rangadi** [comment]
:R @dhalperi : fixed the error. Earlier I should have waited till travis builds passed before mentioning you on the PR, will remember next time.

**Comment by dhalperi** [comment]
To speed the review process, you can run `mvn verify` locally (or `mvn checkstyle:checkstyle` to just check CheckStyle) before pushing.

In any case, it's no problem for me to notice and point out issues ;). Thanks for the fix!

**Pull request closed without merging**
