### PR TITLE
[BEAM-160] Import NexMark integration tests.

### PR DESCRIPTION
**Pull request by mshields822**
BUILDS ON https://github.com/apache/incubator-beam/pull/85

This is an initial import of the 'NexMark' integration tests.
All Google Dataflow specific code has been isolated.
It could do with more cleanup, but wanted to get it out in the sunlight.

### CODE REVIEW

**Comment by davorbonaci** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
Build fix, please?

    Caused by: hudson.plugins.git.GitException: Command "git merge 30585ad3529b0799043d3cef9d2824337b631baa" returned status code 1:
    stdout: Auto-merging sdks/java/core/pom.xml
    Auto-merging pom.xml
    CONFLICT (content): Merge conflict in pom.xml
    Automatic merge failed; fix conflicts and then commit the result.

**Comment by davorbonaci** [comment]
I'm not sure between `integration/java` and `sdks/java/integration`. I think I prefer the second one a bit more. Even more, we might want to do `sdks/java/integration/nexmark`.

**Comment by mshields822** [comment]
I don't think we should take the build seriously until the pubsub pull
request is in since this builds on top. I've put it here so I can point to
it this fri and get the early stuff done.

Not really fussed about the directory name, whatever seems best is fine.
But it will depend on at least one runner so putting under sdks/... seems
misleading. Thought about examples/... but the code quality there is
significantly higher :-)

**Comment by kennknowles** [comment]
+1 to Mark's last point. When modules are all split, we are going to want this dependency direction:

integration tests → runner(s) → SDK

Otherwise we have a cycle between runners and SDK. Is there another option?

**Comment by kennknowles** [comment]
Pinging because this has been sitting for a while. Maybe rebase to kick the tests against the new code layout?

**Comment by mshields822** [comment]
I'm still chipping away on this in the background. I've left it as a
dormant PR since I've been pointing customers to it (esp for Q10). Will
ping back when actually ready, and we need the 3 pubsub ones to go in first.

**Pull request closed without merging**
