### PR TITLE
Improve error handling in gcsio.py

### PR DESCRIPTION
**Pull request by charlesccychen**

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @aaltay, @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by charlesccychen** [comment]
Thanks! Travis passed: https://travis-ci.org/charlesccychen/incubator-beam/builds/152518967

R: @dhalperi

**Comment by dhalperi** [comment]
LGTM, merged

**Pull request closed without merging**
