### PR TITLE
OffsetBasedSource: allow empty sources

### PR DESCRIPTION
**Pull request by dhalperi**
As one example, empty files exist.

### CODE REVIEW

**Comment by dhalperi** [comment]
R: anyone (@lukecwik @tgroh @bjchambers @kennknowles)

**Comment by lukecwik** [comment]
This seems worthwhile to have a test around it since its a boundary condition.

**Comment by dhalperi** [comment]
Thanks. Done, PTAL.  (Also did a little other housekeeping in the test file.)

**Comment by kennknowles** [comment]
LGTM. Interesting findbugs issue.

**Comment by kennknowles** [comment]
You'll need all subclasses to also guarantee it is `@NonNull`.

**Comment by dhalperi** [comment]
Yeah, reverted the change to make fraction consumed non-null. Don't love this inheritance, but I was not intending to make a backwards-incompatible change in this PR.

**Comment by dhalperi** [comment]
Thanks @kennknowles , @lukecwik --merged.

**Pull request closed without merging**
