### PR TITLE
[BEAM-983] runners/spark/translation/streaming/utils/TestPipelineOptions.java missing Apache license header.

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
@davorbonaci Jenkins is slacking around here, not doing it's job 😉

**Comment by amitsela** [comment]
@davorbonaci I don't see a PreCommit running for this PR..

**Comment by davorbonaci** [comment]
(it was committed 7 days ago, but it might have been pushed just now)

**Comment by kennknowles** [comment]
FWIW I think our configuration is probably broken. The command `mvn rat:check` fails on `master` even after the rollback, even after running `git clean -d -f -x`.

**Pull request closed without merging**
