### PR TITLE
Delete DatastoreWordCount

### PR DESCRIPTION
**Pull request by dhalperi**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This is the kind of example we do not need to have in Beam. It's just WordCount with a different data source.

### CODE REVIEW

**Comment by vikkyrk** [comment]
Is there any other place we are moving these examples to? I can imagine users taking this code and modifying it to their needs.

**Comment by dhalperi** [comment]
Probably a Dataflow or GCP-specific location.

**Comment by dhalperi** [comment]
R: @francesperry @davorbonaci 

strong opinions?

**Comment by davorbonaci** [comment]
LGTM. This example doesn't seem to provide much educational value beyond what other examples provide and DatastoreIO's Javadoc.

**Pull request closed without merging**
