### PR TITLE
[BEAM-360] Implements a framework for developing Python SDK sources for new file types

### PR DESCRIPTION
**Pull request by chamikaramj**
Module 'filebasedsource' provides a framework for  creating sources for new file types. This framework implements several features common to many sources based on files.

Additionally, module 'avroio' contains a new source, 'AvroSource', that is implemented using the framework described above. 'AvroSource' is a source for reading Avro files.

Adds many unit tests for 'filebasedsource' and 'avroio' modules.

### CODE REVIEW

**Comment by chamikaramj** [comment]
Hi @silviulica and @dhalperi , can you take a look ?

**Comment by silviulica** [comment]
LGTM -- Thanks Cham! Great progress.

**Comment by chamikaramj** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Merging on @silviulica 's LGTM

**Comment by dhalperi** [comment]
Merged to python-sdk branch. Please close PR manually as GitHub won't close it until the "closes PR" commit makes it into master branch.

**Comment by chamikaramj** [comment]
Thanks. Closing PR.

**Pull request closed without merging**
