### PR TITLE
[BEAM-898] Fix Jenkins Build Failure - IT Options Conflicts

### PR DESCRIPTION
**Pull request by markflyhigh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

 - Remove checksum variable in IT Options since it causes conflict between different ITs.
 - only register TestPipelineOptions.class to avoid incompatibility of options defined in different pipeline.

Test is done by running full set of IT tests on Dataflow service.

### CODE REVIEW

**Comment by markflyhigh** [comment]
+R: @peihe @jasonkuster

**Comment by peihe** [comment]
LGTM

R: @lukecwik

**Comment by lukecwik** [comment]
Merging

**Comment by peihe** [comment]
Re: "It solves the problem by somewhat decreasing the utility offered of the test."
I think the previous utility comes from the improperly uses of PipelineOptions:
1. It was using PipelineOptions as the parser for arguments only used in IT tests main(), such as checksum (which is not a true pipeline option).
2. It is still using PipelineOptions as the arguments parser for WordCount.main(). All cmd arguments, relevant or irrelevant, are passed to WordCount.
WordCount.main(TestPipeline.convertToArgs(options))

Those improper uses requires declaring all PipelineOptions in the global namespace through register(), which caused the post-submit failure.

This PR removed the first improper use, and reduced some utilities (which we are not currently depends on). So, I think it is a good change.

There is some ideas about support a testArg for ITs tests in here:
https://issues.apache.org/jira/browse/BEAM-898?focusedCommentId=15648972&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15648972

**Pull request closed without merging**
