### PR TITLE
Remove the whitelisting required warning

### PR DESCRIPTION
**Pull request by aaltay**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Removes the project whitelisting required warning from Python SDK. This only removes the warning and actual whitelisting requirement will be lifted soon.

### CODE REVIEW

**Comment by aaltay** [comment]
R: @silviulica

Could you please review?

**Comment by silviulica** [comment]
LGTM - Thanks!

**Comment by dhalperi** [comment]
LGTM, merging

**Comment by dhalperi** [comment]
Merged; please manually close PR.

**Pull request merged**
