### PR TITLE
Encapsulate cloning behavior of in-process ParDo evaluator

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This will make way for using the evaluator in contexts where cloning
is not appropriate, such as the evaluator for `GroupAlsoByWindow`

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @tgroh for in-process runner
R: @lukecwik for committer

**Comment by tgroh** [comment]
LGTM

**Comment by tgroh** [comment]
Actually, upon second thought;

Given that we are expected to reuse DoFns, this could fold in another change, and provide the ParDo to the evaluator as a ThreadLocal. Doing so gives a similar behavior (using ThreadLocal#initialValue()) instead of supplier.get(). That should get the same benefit (given that we only ever call supplier.get() once), but also enforce the requirement for DoFns to be used in a single thread, plus reuse.

**Comment by kennknowles** [comment]
I believe the decision of how and when to re-use a `DoFn` should occur outside the evaluator, but I could be mistaken. Not totally sure how that jives with your comment.

**Comment by kennknowles** [comment]
Via @lukecwik: instead, this logic should move even further out. A new evaluator should be created whenever a `DoFn` would be cloned anyhow, so there's no need to abstract this into a supplier, but just move the cloning out to the `ParDoMultiEvaluatorFactory`, etc. I will combine that smaller change directly into my GBK PR.

**Pull request closed without merging**
