### PR TITLE
[BEAM-310] Actually Split Root Transforms

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Permit the ExecutorServiceParallelExecutor to control its own
ExecutorService by passing only a TargetParallelism parameter. Split
roots into the greater of 3 or the target parallelism.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi @jkff

**Comment by dhalperi** [comment]
Regression test?

**Comment by dhalperi** [comment]
LGTM otherwise

**Comment by tgroh** [comment]
Added a test to ensure that split is called with smaller than the estimated size (which only occurs if targetParallelism is greater than 1, which we now enforce)

**Comment by dhalperi** [comment]
(Existing LGTM stands, Please self-merge once green)

**Pull request closed without merging**
