### PR TITLE
Few datastore related fixes

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
- pin googledatastore version to 6.4.1
- add num_shards options to datastore wordcount example
- move datastore wordcount example to cookbook directory

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM, thank you.

**Comment by vikkyrk** [comment]
@aaltay combined a few fixes in this PR, PTAL.

**Comment by aaltay** [comment]
LGTM, thank you

**Comment by vikkyrk** [comment]
R: @robertwb

**Comment by robertwb** [comment]
Merging this now, but for future reference version pinning should probably be its own commit (and PR).

**Pull request merged**
