### PR TITLE
[BEAM-569] Define maxNumRecords default value to Long.MAX_VALUE in JmsIO

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Hmm. It would be cleaner if rather than have a zero-args constructor and defaults in the class, your static factory method simply passed in all the defaults to the real constructor. Then you need not worry about the initialization state of any parameters.

See, for example, [`BigtableIO`](https://github.com/apache/incubator-beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java#L154)

**Comment by jbonofre** [comment]
Updated according to the comment.

**Comment by jbonofre** [comment]
R: @jkff

**Comment by jkff** [comment]
LGTM but note I'm not formally a committer.

**Comment by jbonofre** [comment]
Thanks, I will merge ;)

**Pull request closed without merging**
