### PR TITLE
[BEAM-149] move language source config to pluginManagement

### PR DESCRIPTION
**Pull request by mxm**
This fixes issues with the source/target level in IntelliJ.

### CODE REVIEW

**Comment by mxm** [comment]
CC @mshields822 @kennknowles Could you verify this fix works for you?

**Comment by kennknowles** [comment]
Yup, seems to work throughout. Normally you'd need an explicit reference to the plugin the <plugins> section, but I guess the compiler is special. Or maybe there's just some spooky action.

**Comment by kennknowles** [comment]
LGTM, if it also works for IntelliJ then that's great.

**Comment by mxm** [comment]
Yes, it works consistently in IntelliJ for me. You're right, it is cleaner to keep the reference in the plugin section. I've pushed another fix to make it explicit.

**Comment by kennknowles** [comment]
Botched the merge commit, but this is in (squashed the fixup commit into the initial one)

**Comment by kennknowles** [comment]
@mxm what I mean is that I can't close this, and asfgit won't unless I poke it with a bogus commit containing the magic message, but I think you can close it when ready.

**Comment by mxm** [comment]
Thanks for merging!

**Pull request closed without merging**
