### PR TITLE
[BEAM-22] Enable RunnableOnService Tests

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Not ready for review. Publishing PR to hook into Travis and Jenkins.

Update runners/direct-java/pom.xml to enable the RunnableOnService
tests phase.

### CODE REVIEW

**Comment by tgroh** [comment]
Takes ~1.5m to build the direct runner + run the additional RunnableOnService Tests on Jenkins; about 2-3 on the slower travis targets.

**Comment by tgroh** [comment]
R: @kennknowles 
After merge of #326

**Comment by kennknowles** [comment]
Nice. Since we will, afterwards, be removing the test runs of the current `DirectPipelineRunner`, the change in build time will be reduced. I think we can merge this straight away. If we encounter any problems it will be easy to revert and/or disable selected tests.

**Comment by kennknowles** [comment]
It does seem that the cost on travis is much greater.

**Comment by kennknowles** [comment]
You can actually do the disabling of redundant tests in this PR by adding `<excludedGroups>org.apache.beam.testing.RunnableOnService</excludedGroups>` to the `sdks/java/` test configuration. Then we will have an even better idea of the test timing.

**Comment by kennknowles** [comment]
LGTM. I think it is time to merge this.

**Pull request merged**
