### PR TITLE
Removed BatchWrite from DataflowRunner

### PR DESCRIPTION
**Pull request by ianzhou1**

### CODE REVIEW

**Comment by ianzhou1** [comment]
@dhalperi looks like the BatchWrite was doing some sort of validation. Should I try to validate elsewhere or ignore this?

**Comment by dhalperi** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
This is currently being used by Dataflow to validate that the output path for file based sinks is a valid GCS location, you can't remove it without removing a good error catching signal for users.

What was the motivation behind this change?

**Comment by lukecwik** [comment]
@kennknowles This is an example of a piece of data about a read operation which a runner is interested in looking at to provide a better experience for users.

**Comment by dhalperi** [comment]
I believe that the precondition was only necessary for native sinks. Now
that we're all Java sources here I don't see why a Dataflow job couldn't
write to s3.

**Comment by lukecwik** [comment]
This was a feature we had part of the Dataflow runner for native sinks. During the migration from native sinks to custom sinks, we wanted to maintain that feature. We could remove the feature now but that would mean that mistyped paths would only be validated during execution of the pipeline vs at construction time.

I think this all ties into what do we do with IOChannelUtils in the longer run and who is responsible for validation (SDK, Runner, both?).

**Comment by dhalperi** [comment]
I'm a little confused why TextIO itself doesn't or can't do the validation? Because we don't expect to have the right IOChannelFactories registered at pipeline submission time?

**Comment by lukecwik** [comment]
No, its not that they aren't registered. The issue is that it doesn't make sense to support local paths in Dataflow which Dataflow guards against.

**Comment by kennknowles** [comment]
@lukecwik thanks for the pointer. I can see a runner wanting to know enough to perform its own validation.

**Bad option**: (strawman to match what we have today): 
 - The URN of the UDF clearly identifies it. Problem: there can be no hierarchy with `instanceof` so the cases of interest would have to be enumerated.
 - The SDK puts relevant metadata in the SDK-specific payload. Problem: the SDK doesn't necessarily know what is relevant.
 - The runner groks the SDK-specific payload. Problem: not language independent, breaking abstraction that is allowed to change whenever. Total non-starter.


**Good option**:
 - The UDF envelope has a place for resource/capability requirements, which are a standardized spec.
 - The SDK puts relevant metadata in the capability requirements. Same problem as above, but the capability requirement spec lists all the options. An I/O author must consult them, and propose new ones if needed.
 - The runner can then decide whether it is able to provide the required capabilities.

Assuming the second choice, we have yet to nail down how such capability requirements should be expressed. It all comes down to the Fn envelope. Great example to work with.

**Pull request closed without merging**
