### PR TITLE
[BEAM-615] Add support for processing time timers in FlinkRunner

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @aljoscha or @mxm 

I coded this very quickly without learning probably what I need to about the `FlinkRunner` or Flink. It seems to work for the naive examples I am experimenting with. Perhaps you can find errors and suggest corrections, or pull it and do it right?

### CODE REVIEW

**Comment by mxm** [comment]
Thanks for the PR @kennknowles. Processing time support definitely needs to be fixed. The changes look sensible to me but I would wait for @aljoscha opinion on this.

**Comment by aljoscha** [comment]
This would work but not in the presence of failures/recovery because timers need to be checkpointed, as we do with the event-time timers in `WindowDoFnOperator`.

I'm currently working on an addition to Flink that would provide user code with an interface that allows setting processing-time/event-time timers that would also be kept in a fault-tolerant way by the system. Maybe we should wait for that and then update `WindowDoFnOperator` to use that for both event-time timers and processing-time timers.

**Comment by kennknowles** [comment]
I see. I first considered duplicating the logic for event-time timers, but I had hoped the shortcut of using the underlying Flink timers would work. I will close this PR, leaving the open question of whether to emulate the event-time timer logic vs wait for the fault-tolerant Flink APIs.

**Comment by mxm** [comment]
I think this PR could be extended with not much work to checkpoint processing time timers in the `snapshotOperatorState(..)` method. It might be worth doing that because the next Flink release will only be available in a couple of months.

**Pull request closed without merging**
