### PR TITLE
[BEAM-124] Modify example dependencies to only add runners as optional dependencies

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Also support excluding runners by disabling the include-runners profile.

Tested ITs
BQ and WordCount pass on Dataflow
WordCount passes on Flink and Spark

Upfront setup:
```
mvn clean install -pl examples/java,examples/java8 -am
```

Dataflow:
```
mvn clean verify -pl examples/java -DskipITs=false -DintegrationTestPipelineOptions='[ "--tempRoot=gs://clouddfe-testing-temp-storage", "--runner=org.apache.beam.runners.dataflow.testing.TestDataflowRunner" ]'
```

Flink:
```
mvn clean verify -pl examples/java -DskipITs=false -DintegrationTestPipelineOptions='[ "--tempRoot=gs://clouddfe-testing-temp-storage", "--runner=org.apache.beam.runners.flink.TestFlinkRunner" ]' -Dit.test=WordCountIT
```

Spark:
```
mvn clean verify -pl examples/java -DskipITs=false -DintegrationTestPipelineOptions='[ "--tempRoot=/tmp", "--runner=org.apache.beam.runners.spark.SparkRunner" ]' -Dit.test=WordCountIT
```

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @markflyhigh  @jasonkuster

**Comment by lukecwik** [comment]
CC: @dhalperi

**Comment by markflyhigh** [comment]
LGTM for adding runners optional dependencies.

@jasonkuster Any thoughts/plans for examples/java8 testing? Also we want all runner supported in examples/java8 right? @lukecwik

**Comment by lukecwik** [comment]
Yes, having all runners supports two usecases, integration testing and allowing for users to run examples easily.

**Comment by dhalperi** [comment]
FWIW, LGTM too

**Comment by jasonkuster** [comment]
@markflyhigh We'll probably put something there at some point, but for now what we've got is a good start.

@lukecwik LGTM

**Pull request closed without merging**
