### PR TITLE
[BEAM-327] Update DataflowPipelineRunner worker container version

### PR DESCRIPTION
**Pull request by swegner**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by swegner** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
... still waiting for green.

**Comment by swegner** [comment]
Seems that our Jenkins workers might be stuck: https://builds.apache.org/job/beam_PreCommit_MavenVerify/buildTimeTrend

**Comment by dhalperi** [comment]
Yep, Jenkins seems to be a little borked. But Jenkins is the one that runs the integration test, so I can't merge this yet.

**Comment by dhalperi** [comment]
Here, Jenkins adds value over travis... Can you rebase and push so that jenkins gets kicked?

Or run a few pipelines manually confirming this works?

**Comment by kennknowles** [comment]
You can run the needed tests directly via:

```bash
mvn --batch-mode --errors clean verify \
    --also-make-dependents --projects runners/google-cloud-dataflow-java \
    -DforkCount=0 \
    -DrunnableOnServicePipelineOptions='[ "--runner=org.apache.beam.runners.dataflow.testing.TestDataflowPipelineRunner", "--project=YOUR_PROJECT", "--tempRoot=YOUR_STAGING_LOCATION" ]
```

**Comment by dhalperi** [comment]
LGTM, thanks!

**Pull request merged**
