### PR TITLE
Static import Preconditions.checkX everywhere

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @bjchambers your turn for a little OCD

**Comment by tgroh** [comment]
runners/flink/runner/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/io/UnboundedFlinkSource.java
runners/flink/runner/src/main/java/org/apache/beam/runners/flink/translation/utils/SerializedPipelineOptions.java
sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOTest.java (Comments)

**Comment by lukecwik** [comment]
Even without the places that Thomas pointed out, this looks good to me.

**Comment by dhalperi** [comment]
Fixed the two Flink cases, which were just unused imports not caught by Checkstyle because it's disabled for that module.

The TextIOTest is just the actual use of the word "preconditions" to mean the concept, not the Guava library ;)

**Comment by dhalperi** [comment]
Thanks -- will merge when green.

**Pull request closed without merging**
