### PR TITLE
[BEAM-1139] Revert Apex+Kryo PR and fix via deps

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Reverts #1586 and moves forwards with a minor dependency hack.

This may break something in the Spark runner's integration tests, since the conflict is real and this simply overrides and hopes for the best. So do not bother to review until Jenkins confirms integration test success.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @tweise @davorbonaci 

It looks like this approach - which should be temporary - gets some green for our precommit.

**Comment by tweise** [comment]
LGTM as stop gap measure.

**Comment by kennknowles** [comment]
Moved the dependency to `-P jenkins-precommit` as that is a bit cleaner. That profile should go away since it assumes `-P apex-runner` and `-P spark-runner` together, so this stopgap will go way with it.

I will merge when green.

**Comment by davorbonaci** [comment]
LGTM.

**Comment by kennknowles** [comment]
To expedite, manually confirmed this:

```
mvn -DskipTests clean install -P apex-runner -pl examples/java -am

mvn --errors failsafe:integration-test@apex-runner-integration-tests \
    -pl examples/java \
    -P apex-runner \
    -P spark-runner,dataflow-runner,flink-runner,direct-runner \
    -P jenkins-precommit \
    -D test=WordCountIT \
    -D beamTestPipelineOptions='[
      "--runner=org.apache.beam.runners.apex.TestApexRunner",
      "--project=...",
      "--tempRoot=..."
    ]'
```

This runs the failing execution with all the various profiles active, as Jenkins does. I'll merge to get ahead of the Jenkins build queue and maybe get some green for all those doomed builds. (worst case: still not green)

**Pull request merged**
