### PR TITLE
[BEAM-498] Remove some more uses of OldDoFn

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @tgroh 

In the DirectRunner tests, I ported the syntax, though not the logic since it doesn't actually run yet. I'm not totally certain these tests are needed beyond future ROS tests.

### CODE REVIEW

**Comment by kennknowles** [comment]
Feel free to leave this review lower priority and I will port a bunch more `DirectRunner` tests tonight.

**Comment by kennknowles** [comment]
OK, this is ready for review. I have removed all non-essential uses of `OldDoFn` from `beam-runners-direct-java`.

**Comment by tgroh** [comment]
The only essential use is `GroupAlsoByWindowEvaluatorFactory`, yes?

**Comment by kennknowles** [comment]
That is correct.

**Pull request closed without merging**
