### PR TITLE
Javadoc has invalid references after the recent refactorings + other fixes

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by iemejia** [comment]
This PR fixes some issues in the javadoc, in particular invalid links and references to stuff that no longer applies, as well as:

- Useless semicolon use
- Overcomplicated boolean expressions
- Removes unneeded java keywords (e.g. final on private method, return ; in void).
- Style fixes for Filter<T>

**Comment by iemejia** [comment]
I did not create a JIRA for this since this is a small fix, but please tell me in case I must create one.
R: @dhalperi

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
LGTM.

I will squash the commits and amend the message to link to https://issues.apache.org/jira/browse/BEAM-475.

**Pull request closed without merging**
