### PR TITLE
BigtableIO.Read: use PBegin, rather than PInput

### PR DESCRIPTION
**Pull request by dhalperi**
Sources should start from the beginning of a pipeline.

### CODE REVIEW

**Comment by dhalperi** [comment]
any R will do @lukecwik @kennknowles @tgroh

**Comment by dhalperi** [comment]
backwards-incompatible, but has not been released to Maven yet so it should be okay. Users should not be affected unless they're using this wildly incorrectly.

**Comment by davorbonaci** [comment]
SG, but let's make sure it gets to 1.5 of Dataflow.

**Comment by lukecwik** [comment]
LGTM

**Pull request closed without merging**
