### PR TITLE
Add KafkaIO tests to Flink runner RunnableOnService tests

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @mxm or @aljoscha 
CC: @amitsela 

The I/O stuff hasn't all been factored out from the core SDK yet, but I did realize that there are a number of useful tests that aren't run in any configuration.

I just added the config for KakfaIO here, mostly as an exercise & an example to see if it would be easy. I didn't look at any of the code under test or the test itself - I have suspicions that configuration changes might break it and/or make it too slow. At some point we probably want all of these to run with real clusters.

On the other hand, the whole point of the model/SDK/Runner API/Fn API/etc is that we should be able to develop these things in isolation with only selected integration tests. But for now, I'd say the more tests the better.

**Comment by aljoscha** [comment]
LGTM. Have you also looked into making the Kafka Sink tests `RunnableOnService`?

**Comment by dhalperi** [comment]
@rangadi 

I'm surprised we have Kafka `@RunnableOnService` tests. I suspect that they should actually be `@NeedsRunner` tests. Specifically, those tests seem to use mock objects rather than pointing at a Kafka service.

**Comment by mxm** [comment]
What would be the difference between `@RunnableOnService` and `@NeedsRunner`? The former extends the latter but it seems to be that tests written against one or the other are interchangeable.

**Comment by aljoscha** [comment]
@dhalperi @rangadi KafkaIO also has a dependency on the `DirectRunner`. Should this be removed and the tests executed in the direct runner similar to the tests in `java sdk` and `core runner`?

**Comment by dhalperi** [comment]
@mxm:

* `@RunnableOnService` means that the pipeline could be executed on any production instance of a runner (e.g., Cloud Dataflow service [hence the name, which is no longer as good], a Spark cluster, a Flink cluster, etc.).

`@NeedsRunner` means effectively today that a test needs the `DirectRunner` in order to pass. @tgroh is working on the test capability matrix to improve things.

A practical way to distinguish between the former and the latter is usually whether the test requires the the execution happen on the same-machine or even same-JVM -- if so, it's a `@NeedsRunner` test. Conversely, with `@RunnableOnService`, as long as the `TestPipelineOptions` are configured in the right way, the test *can* be made to pass running anywhere.

Examples of truly `@RunnableOnService` tests:
* tests that do not exercise any external systems. For example, CountingInput.upTo(N) -> Count.globally() -> PAssert(count == N).
* tests that exercise external systems that are hosted publicly. For example, tests that read from or write to Google Cloud Bigtable (see #505) can be run anywhere on the web as long as the execution environment can reach Google's network.
* tests that exercise external systems that are configured using `TestPipelineOptions`. The KafkaIO tests could be written in this way if the Kafka cluster was configured via `TestPipelineOptions` rather than either using mocks or a same-process spun-up Kafka instance.

**Comment by tgroh** [comment]
Seconding what @dhalperi said; there's also a distinction worth drawing between tests that can be run on a production instance and those which are worth running

Generally, `RunnableOnService` tests should exercise some runner functionality as it relates to the Beam model; `NeedsRunner` tests should exercise some PTransform functionality. As such, not all tests that can be run in production need to be marked `RunnableOnService`

**Comment by rangadi** [comment]
Thanks @dhalperi & @tgroh. KafkaIOTest borrowed code and structure from CountingSourceTest, and I kept @RunnableOnService annotation as well. I didn't think much about it that time. These are clearly @NeedsRunner tests as Tom described above. Shall I send a PR?

**Comment by dhalperi** [comment]
@rangadi please do.

**Comment by rangadi** [comment]
Updated KafkaIO tests annotation in #568

**Pull request closed without merging**
