### PR TITLE
Build in eclipse/eclipse-jdt

### PR DESCRIPTION
**Pull request by dkulp**
This just updates the code to build with eclipse-jdt (again) and adds the travis.xml changes back in .

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @tgroh @amitsela for affected code.

**Comment by tgroh** [comment]
LGTM for the `DirectRunner` changes. I don't really understand why the narrowing is required (I would have even expected it to be less likely to succeed). Do you have any insights?

**Comment by amitsela** [comment]
@dkulp I've heard that eclipse "understands" Scala better than IntelliJ, is this what's happening here ? some type inference issue ?
LGTM, but I'm really curious here 😉

**Comment by dkulp** [comment]
For some reason, eclipse scala finds multiple "empty()" methods on the immutable List type and complains about it being ambiguous.  I couldn't figure out how to get it resolved via a cast or anything (my scala skills are very limitted, let alone the whole java<->scala interaction).   This is what I came up with that works and compiles.  It's only once per VM (static) so any performance impact should be negligible.

**Comment by jbonofre** [comment]
LGTM

I gonna merge

**Comment by jbonofre** [comment]
Can you please rebase with last changes ? Else I can do it for you. Thanks.

**Comment by dhalperi** [comment]
is there a way to replace Eclipse's compiler with one that properly implements the Java spec?

**Comment by dkulp** [comment]
Who says it doesn't properly implement the Java spec?  In particular, according to the spec:
http://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html
A compiler is allowed to:
"Reordering the fields, methods, or constructors in an existing type declaration."

But the answer is no.  Within eclipse, you don't have any option other than to use the Eclipse compiler.

**Comment by dkulp** [comment]
BTW:  the IBM compiler on AIX would also have a similar issue.   This is something I have (too much) experience with in CXF.   In CXF, we have a JavaToWSDL command.  In our test suites, we had to be careful of direct compares as Eclipse, IBM, and Oracle/Sun compilers would output methods in different orders and result in the operations in the WSDL being different.   This is also why in JAXB, the XmlType annotation has a propOrder attribute to specify the order as it cannot be derived consistently from the output of the compiler.

**Comment by dhalperi** [comment]
We test with more than just Oracle JDK already, which is why I am generally suspicious of Eclipse's compiler. In this case, it seemed like Eclipse's compiler actually has and/or had a bug: https://github.com/google/auto/issues/292

**Comment by dkulp** [comment]
Actually, that's slightly different, but that issue DOES provide good information for a better alternative.  The "fix" does prevent the sorting of the attributes/methods for the current class.  However, it still results in sorted stuff inherited from interfaces.   Thus, a better fix is to define the "public abstract MetricName name()" methods on the class so AutoValue see's those in the order it needs them.

**Comment by dhalperi** [comment]
(I should add here, that I do not at all disagree with making things explicit rather than implicit :)

**Comment by jbonofre** [comment]
The test failures doesn't seem related. I'm rebasing and testing locally.

**Pull request closed without merging**
