### PR TITLE
Use item equality in apply_to_list test

### PR DESCRIPTION
**Pull request by aaltay**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Orders of PCollections are not guaranteed and this test depends on
the current DirectRunner implementation for output to have the same
order as input.

### CODE REVIEW

**Comment by aaltay** [comment]
Hi @chamikaramj, could you please review?

**Comment by chamikaramj** [comment]
LGTM

**Comment by aaltay** [comment]
Hi @bjchambers could you please review?

**Comment by bjchambers** [comment]
The history of this branch seems to be heavily polluted -- you may have been merging? I suspect you need to rebase on top of master so that only your commits show up.

**Comment by kennknowles** [comment]
To be specific, since a few branches are in play:

```bash
git checkout pttest
git rebase python-sdk
```

**Comment by aaltay** [comment]
I will close this and send a new PR with a clean history. Thank you.

**Comment by davorbonaci** [comment]
(It is generally easier to rewrite history of your PR branch. That way, we use the same PR and keep the history of comments, review, etc. This is fine too, but generally less preferable.)

**Pull request closed without merging**
