### PR TITLE
Merge remote-tracking branch 'origin/master' into python-sdk

### PR DESCRIPTION
**Pull request by aaltay**
Merge and update python-sdk pom.xml version and fixup to merge errors.

### CODE REVIEW

**Comment by aaltay** [comment]
R: @dhalperi

**Comment by aaltay** [comment]
All tests are passing.

R: @robertwb

**Comment by dhalperi** [comment]
LGTM now that tests are passing.

**Comment by dhalperi** [comment]
Merged, close at your leisure

**Comment by aaltay** [comment]
Thank you.

**Pull request closed without merging**
