### PR TITLE
[BEAM-499] Deletes some code that is not used by SDK.

### PR DESCRIPTION
**Pull request by chamikaramj**
Some code in apiclient.py is not used by Python SDK.

Deleting unused code and corresponding tests.

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @charlesccychen

**Comment by charlesccychen** [comment]
Thanks! LGTM.

**Comment by chamikaramj** [comment]
Thanks.

R: @dhalperi

**Comment by dhalperi** [comment]
LGTM, merged

**Comment by chamikaramj** [comment]
Thanks Dan.

**Pull request merged**
