### PR TITLE
[BEAM-242] Enable checkstyle and fix checkstyle errors in Flink runner

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @aljoscha 
R: @mxm

**Comment by aljoscha** [comment]
Could we wait for this to go in after #737 went in? This changes basically everything and would make rebasing a horrible experience.

**Comment by jbonofre** [comment]
@aljoscha sorry, no problem.

**Comment by aljoscha** [comment]
Cool, thanks. 😃

**Comment by mxm** [comment]
Already discussed this with @jbonofre Thanks for delaying this a bit.

**Comment by aljoscha** [comment]
#737 is in now so I think you can pick this up again.

**Comment by jbonofre** [comment]
@aljoscha Great ! Thanks a bunch. I'm updating accordingly.

**Comment by jbonofre** [comment]
Rebased, and updated with latest changes. Let me know what you think about it guys. Thanks.

**Comment by aljoscha** [comment]
LGTM from my side. Maybe @mxm has some comments, though.

**Comment by mxm** [comment]
Looks good @jbonofre!

**Comment by jbonofre** [comment]
Thanks, I gonna merge it. Thanks guys !

**Pull request closed without merging**
