### PR TITLE
Clear requirements cache directory before using it in test

### PR DESCRIPTION
**Pull request by swegner**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

`test_with_requirements_file` was failing locally because I had stale files in my /tmp/dataflow-requirements-cache from a previous package install. This change cleans the cache directory before validating its contents.

### CODE REVIEW

**Comment by swegner** [comment]
R: @robertwb

**Comment by robertwb** [comment]
Wouldn't this unconditional clear it? If we want a fresh directory, we should use tempfiles mechanisms to give us a fresh one each time (and attempt to delete it after use). More importantly, if this is used as a cache, it should be safe to re-use or there's a bug here, right?

**Comment by swegner** [comment]
> Wouldn't this unconditional clear it?

Yes

>  If we want a fresh directory, we should use tempfiles mechanisms to give us a fresh one each time (and attempt to delete it after use).

There is a separate test which tests overriding the cache directory, [`test_with_requirements_file_and_cache`](https://github.com/swegner/incubator-beam/blob/9ec4c926f0038f974e79afe0e65e200ef2a23c3e/sdks/python/apache_beam/utils/dependency_test.py#L152). So, the value of [`test_with_requirements_file`](https://github.com/swegner/incubator-beam/blob/9ec4c926f0038f974e79afe0e65e200ef2a23c3e/sdks/python/apache_beam/utils/dependency_test.py#L113) is only that it validates the behavior when the default cache location is used. Seems only marginally valuable to me, so I'd be fine dropping the test.

> More importantly, if this is used as a cache, it should be safe to re-use or there's a bug here, right?

This may point to an issue in [`dependency.stage_job_resources`](https://github.com/swegner/incubator-beam/blob/9ec4c926f0038f974e79afe0e65e200ef2a23c3e/sdks/python/apache_beam/utils/dependency.py#L208). It internally calls [`populate_requirements_cache`](https://github.com/swegner/incubator-beam/blob/9ec4c926f0038f974e79afe0e65e200ef2a23c3e/sdks/python/apache_beam/utils/dependency.py#L194) which is strictly additive-- it uses `pip` to download requested dependencies into the cache, but doesn't clear non-requested ones. It then gathers a list of all resources using [a file glob of the cache directory](https://github.com/swegner/incubator-beam/blob/9ec4c926f0038f974e79afe0e65e200ef2a23c3e/sdks/python/apache_beam/utils/dependency.py#L270). As a result, the final list of resources may contain previously cached resources.

It seems we are using the cache directory as a sandbox area to resolve transitive dependencies needed to stage. But since it's reused, we are getting extra files.

**Comment by swegner** [comment]
I've opened [BEAM-680](https://issues.apache.org/jira/browse/BEAM-680) to track the issue with staging extra cached dependencies.

**Pull request closed without merging**
