### PR TITLE
[BEAM-434] When examples write output to file it creates many output files instead of one

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
It looks like there is an assertion on the output hash, the hash I get is `d41d8cd98f00b204e9800998ecf8427e`.
Not sure which output file is expected as I would expect multiple output files (from what I've seen running the examples locally).

@dhalperi are you familiar with this ? I saw your name annotated somewhere in travis.yml 😄

**Comment by dhalperi** [comment]
I suspect that the travis-CI tests are failing because they are using the wrong path for the expected output. (Using `withoutSharding` changes the `shardNameTemplate`).

**Comment by dhalperi** [comment]
(Note that `d41d8cd98f00b204e9800998ecf8427e` is the md5 of the empty string)

**Comment by amitsela** [comment]
Oh, right. No more output_file_prefix-part#-of-total#parts
I'll try to change this later and see how Travis feels about it..

BTW, would you be more comfortable with passing "1" shard in the example as an option ?
For example: --numShards=1
So the user explicitly declares this, and we're not setting `withoutSharding` for him.

**Comment by amitsela** [comment]
@tgroh it seems that the best way to handle this one is by controlling the number of output shards in the `DirectRunner`. Can I close this PR as it has been superseded by https://github.com/apache/incubator-beam/pull/651 ?

**Comment by tgroh** [comment]
That seems reasonable.

**Comment by amitsela** [comment]
superseded by #651

**Pull request closed without merging**
