### PR TITLE
[BEAM-989] Better documentation for CompressionTypes.

### PR DESCRIPTION
**Pull request by katsiapis**

### CODE REVIEW

**Comment by katsiapis** [comment]
Hi @chamikaramj, @dhalperi can you please take a look?

**Comment by chamikaramj** [comment]
LGTM

Thanks.

**Comment by robertwb** [comment]
Could you make the identifiers actual names (e.g. `_CompressionType('zlib')`) while you're at it. (Actually, I think it'd be good to clean up this and use an actual Python enum class.)

**Comment by katsiapis** [comment]
Thanks folks.

Done (using strings).
Haven't moved to Python enums. Would you mind handling that in a followup?

Also, could you merge and let me know if I can close?

**Comment by robertwb** [comment]
Yes, enums can wait 'till a followup. I'll merge as soon as I verify tests pass.

**Comment by katsiapis** [comment]
Thanks for merging in Robert. Closing...

**Pull request closed without merging**
