### PR TITLE
[BEAM-132] pom.xml: skip source-release assembly

### PR DESCRIPTION
**Pull request by dhalperi**
We do this separately via our own assembly.

### CODE REVIEW

**Comment by dhalperi** [comment]
In the output of `mvn -Papache-release package`:

```
[INFO] --- maven-assembly-plugin:2.4.1:single (source-release-assembly) @ beam-parent ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO] 
```

**Comment by dhalperi** [comment]
R: @jbonofre @davorbonaci

**Comment by jbonofre** [comment]
I think we should more do a release-plugin configuration like this:

```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>2.5.3</version>
          <configuration>
            <useReleaseProfile>false</useReleaseProfile>
            <preparationGoals>clean install</preparationGoals>
            <goals>deploy</goals>
            <arguments>-Prelease</arguments>
            <autoVersionSubmodules>true</autoVersionSubmodules>
          </configuration>
        </plugin>
```

That would prevent to use the `apache-release` profile and keep our `release` profile.

**Comment by jbonofre** [comment]
LGTM anyway

**Pull request merged**
