### PR TITLE
BEAM-756 fix JavadocPackage checkstyle suppression

### PR DESCRIPTION
**Pull request by tweise**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
It seems as though other packages go with [/\\] instead of [\\\/] such as checkstyle (https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml)
It would be good to use the typical format for this and its strange that we used \\\/

**Comment by lukecwik** [comment]
R: @lukecwik

**Comment by tweise** [comment]
@lukecwik thanks, see update

**Comment by lukecwik** [comment]
LGTM, merging

**Pull request closed without merging**
