### PR TITLE
Turn on failOnWarning and set runners dependency scope as runtime in example.

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
LGTM, but would prefer to be project-wide.

**Comment by peihe** [comment]
rebased.
It is ready to merge once tests pass.

**Comment by peihe** [comment]
Fixed the build by setting dataflow runner back to compile time dependency.
We will be able to set it to runtime in the example cleanup PR.

**Pull request closed without merging**
