### PR TITLE
[BEAM-484] Dynamic Rebalance support for Datastore Source

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

- Add support for Dynamic rebalance
- Move and rename DatastoreSource/Reader to V1Beta3Source/Reader into a new file.
- Test Read transform, Source and Reader independently.

### CODE REVIEW

**Comment by vikkyrk** [comment]
@dhalperi Here is an initial stab at it. Few things to note,
- End-to-End tests pass. I have not verified that the dynamic splitting feature works on Dataflow yet. Wanted to get the code out for initial review. 
- I have covered most important test cases but there is definitely room for more coverage, but in another PR (in the interest of keeping this one small)
- Regarding the DatastoreFactory / QuerySplitter, I modified to be created lazily and made them transient to ensure that the Source is serailizable.

**Comment by dhalperi** [comment]
R: @tgroh @dhalperi

Thomas implemented Create-as-bounded-source. Can you take a first look @tgroh ?

**Comment by tgroh** [comment]
This seems like two changes - a file split, and updates to the source to support dynamic splits. Can you separate them into multiple commits?

**Comment by vikkyrk** [comment]
Sure, let me do that

**Comment by jkff** [comment]
I am still not convinced that implementing dynamic rebalancing this way (oversplitting + grouping the bundles) is a better idea than simply oversplitting (which would require far fewer code to implement). Can you comment on that?

**Comment by vikkyrk** [comment]
The idea is to not have too many sub-sources resulting from oversplits initially that runners might not be able to handle efficiently (additional RPCs back and forth to runner to request work items etc.). I don't know if we have any data supporting this but just intuition. @dhalperi might have more to add here. 

I don't think it is a lot of code, (this PR has a bunch of things not related to dynamic rebalancing, I am breaking it into relevant parts). Although I don't how much more complexity dynamic rebalancing adds in practice while running jobs in production.

**Comment by dhalperi** [comment]
Vikas is right. In general, oversplitting is considered harmful by runners. We still need to try to honor the runner's request bundle size; we oversplit only to provide later resharding of the bundles.

**Comment by vikkyrk** [comment]
From Dan, 

```
Eugene had a good suggestion: why not

Create.of(query) | ParDo.of(split query) | Reshard | ParDo.of(read from query)

Your code will probably be much simpler and we can let the dynamic work rebalancing happen on the GroupByKey inside of the reshard.
```

**Comment by vikkyrk** [comment]
@dhalperi @jkff  Nice idea, but once concern with the approach  is that GBK on Datastore Query is not possible since it cannot be deterministically encoded (It contains a proto Map). Create.of Source should itself be dynamic rebalancable right? Is there a way to avoid the GBK and just oversplit the queries and provide it to Create.of? (without having to split at pipeline construction time)?

**Comment by dhalperi** [comment]
No, you wouldn't use the Query as the key, but as the Value. See, for example, https://github.com/apache/incubator-beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/io/Write.java#L266

**Comment by vikkyrk** [comment]
I see. That would also work for runners that do not support dynamic rebalancing.

Just to confirm, this would mean that we no longer need to compute the estimated size and cannot leverage the 'desiredNumBytes' that runner would provide a source and instead rely on user provided numSplits or a default value.

**Comment by dhalperi** [comment]
That is correct. Here's my proposal for the splitting ParDo:

* There is an option on the read to set the number of splits, which is used by default.
* If that option is missing, get statistics and break the job into 64 MiB-sized splits, with a minimum of 12 splits. This is equivalent to `BoundedSource#splitIntoBundles` with desired chunk size of 64 MiB.
* For now, don't make the split size overridable.

**Comment by vikkyrk** [comment]
Sounds good.

**Comment by vikkyrk** [comment]
Closing in favor of https://github.com/apache/incubator-beam/pull/739

**Pull request closed without merging**
