### PR TITLE
[BEAM-443] Remove checked exceptions from PipelineResult.waitUntilFinish interface.

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @davorbonaci

**Comment by peihe** [comment]
2 out of 5 travis passed.
PTAL

**Comment by dhalperi** [comment]
JIRA issue?

**Comment by dhalperi** [comment]
This is a blocking operation, throwing `InterruptedException` should probably stay part of the contract.

**Comment by peihe** [comment]
I reopened and updated jira BEAM-443.
PTAL

**Comment by dhalperi** [comment]
Can you please add more details?

* need clearly defined contract and verification across all runners
* need to revisit how to handle metrics/aggregators
* need to be able to get logs

possibly other things?

**Comment by peihe** [comment]
Filed jira "Redesign PipelineResult API"
https://issues.apache.org/jira/browse/BEAM-849

**Pull request closed without merging**
