### PR TITLE
Little fixes to LatestFnTest

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @swegner and any committer

### CODE REVIEW

**Comment by swegner** [comment]
You beat me to it. LGTM

 I was also going to add a checkstyle rule to prevent files that end in `Tests.java`. Want to do that here, or should I follow-up? http://checkstyle.sourceforge.net/config_regexp.html#RegexpOnFilename

**Comment by kennknowles** [comment]
Added the checkstyle test, and confirmed it forbids what it ought to.

**Comment by swegner** [comment]
:+1: (LGTM)

**Comment by kennknowles** [comment]
R: @lukecwik for committer

**Comment by lukecwik** [comment]
LGTM, merging

**Comment by kennknowles** [comment]
(this is merged)

**Pull request closed without merging**
