### PR TITLE
[BEAM-480] Move createTable() from BigQueryTableInserter to BigQueryServices

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by dhalperi** [comment]
Have merged Ian's PR, so this can be updated and reviewed. Thanks for holding, Pei!

**Comment by peihe** [comment]
PTAL

**Comment by peihe** [comment]
synced and solved the conflicts
R: @dhalperi

**Comment by peihe** [comment]
R: @lukecwik

**Comment by dhalperi** [comment]
Status?

**Comment by peihe** [comment]
synced
R: @dhalperi
PTAL

**Comment by dhalperi** [comment]
Precommits failed.

**Comment by peihe** [comment]
This PR is covered in https://github.com/apache/incubator-beam/pull/1400.

**Pull request closed without merging**
