### PR TITLE
[BEAM-225] Create Class for Common TypeDescriptors

### PR DESCRIPTION
**Pull request by eljefe6a**
Jira issue BEAM-225 Create Class for Common TypeDescriptors. Adding KVTypeDescriptors and TypeDescriptors to make primitives easier.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @kennknowles

It may require adding some fancy methods to `TypeDescriptor`, but any chance we can have this?

```java

import static ...TypeDescriptors.kvs;
import static ...TypeDescriptors.strings;
import static ...TypeDescriptors.lists;

kvs(strings(), strings())
lists(strings());
kvs(strings(), lists(strings())
```

**Comment by eljefe6a** [comment]
Added support for KVs, Lists, Sets, and Iterables.

**Comment by kennknowles** [comment]
Nice. Since it can be fairly subtle whether or not erasure has left some problems, would you mind adding some basic tests?

**Comment by kennknowles** [comment]
LGTM. I'll proceed with merging this.

**Comment by kennknowles** [comment]
Have you submitted your ICLA or are you under another CLA? I cannot find you in the [phonebook](https://people.apache.org/phonebook.html) or in the [list of ICLAs](http://home.apache.org/unlistedclas.html).

I don't think this contribution qualifies as "large" per our contribution instructions, so I will proceed.

But given the number of PRs you have to us, it seems good to get an ICLA established moving forward.

**Comment by eljefe6a** [comment]
Submitted ICLA. Thought i had one, but I guess I didn't.

**Pull request closed without merging**
