### PR TITLE
Allow Google Cloud Dataflow workflows to use ".dev" workers

### PR DESCRIPTION
**Pull request by charlesccychen**

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM

**Comment by charlesccychen** [comment]
Thanks! R: @dhalperi 

Passing Travis: https://travis-ci.org/charlesccychen/incubator-beam/builds/154212139

**Comment by dhalperi** [comment]
Where on the roadmap is moving this code to a `/dataflow/` namespace inside of python sdk?

**Comment by dhalperi** [comment]
LGTM, merged

**Comment by charlesccychen** [comment]
Thanks.  This is happening after performance optimizations, which have higher priority, but before GA.

**Pull request closed without merging**
