### PR TITLE
[BEAM-79] Merge branch 'master' into gearpump_runner

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by manuzhang** [comment]
merge master into gearpump-runner branch and also follow up recent changes on integration-tests and package-info

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by manuzhang** [comment]
@jbonofre connecting issue on traivs ?

**Comment by jbonofre** [comment]
I'm checking, but it seems so. I will trigger a new run for this PR.

**Comment by manuzhang** [comment]
@jbonofre have we got another run? I'm worried that the branch is left behind with 0.2.0-incubating released

**Comment by jbonofre** [comment]
Hi Manu. It looks an temporary issue with travis as the build works fine. Do you want I rebase on master ?

**Comment by manuzhang** [comment]
Is that possible ? I've also added commits for `package-info` and integration-test.

**Comment by manuzhang** [comment]
@jbonofre @kennknowles @dhalperi rebased on recent master. Not sure what is going wrong with the travis test

**Comment by kennknowles** [comment]
I'm not certain what is going on with Travis, but you definitely will want to update `runners/gearpump/pom.xml` to version `0.3.0-incubating`. I'll try that out, too, and see if it resolves things.

**Comment by jbonofre** [comment]
A new rebase is needed for new version. I plan to do it asap.

**Comment by kennknowles** [comment]
I forked it and updated the version. It looks like it is passing: https://travis-ci.org/kennknowles/incubator-beam/builds/151282293.

I've opened manuzhang#1 which bumps the version on this branch, or you could just do it yourself.

**Comment by manuzhang** [comment]
@kennknowles updated but hit by downloading timeout again 😞

**Comment by manuzhang** [comment]
@kennknowles @jbonofre @dhalperi merged with recent master. Previous `DoFn` has been replaced with `OldDoFn` and support for new `DoFn` will be added later.

**Comment by manuzhang** [comment]
Guys, can we advance with this PR ?

**Comment by jbonofre** [comment]
I will be back from vacation Wednesday. I will work on it then.

**Comment by manuzhang** [comment]
guys, any updates ?

**Comment by jbonofre** [comment]
Yes, I rebased and tested. I noted some stuff to fix. I will comment today.

**Comment by jbonofre** [comment]
@manuzhang would you be available on Slack or Hangout ? I would like to discuss a couple of topics with you. Thanks !

**Comment by kennknowles** [comment]
The tests are green. Are there any outstanding issues, or are you ready to merge it in? Since it is a feature branch, presumably you can just roll forwards addressing any issues.

**Comment by jbonofre** [comment]
I plan to discuss with Manu about some topics tomorrow. I will do the merge. Thanks !

**Comment by jbonofre** [comment]
I discussed with Manu about couple of topics:
- support of some IO features (not yet implements, it's on the TODO)
- the README.md could be enhanced
- the translation of DoFn is based on Gearpump FlatMapFunction which matches well
- examples package and code directly in the runner (I would keep it like this for now and remove later)

I also tested the gearpump runner with the last gearpump incubating release with simple pipelines.

I also checked:
- checkstyle is OK
- headers are OK

@kennknowles I'm proposing to merge this runner on master. It would give more visibility and would allow people to experiment and provide feedback. If you agree, I will do more than happy to do the merge  ;)

**Comment by kennknowles** [comment]
That's a different discussion for the mailing list, where we have discussed criteria a bit. This PR is merging the other way, so that the `gearpump-runner` branch is caught up to `master` a bit.

**Comment by kennknowles** [comment]
I have shuffled the commits for readability and pushed the changes from this PR into `gearpump-runner`. I think you'll need to close this PR manually due to the way the asfgit bot operates.

I recommend merging `master` into `gearpump-runner` as frequently as possible so that it is almost always a pretty small update.

**Comment by jbonofre** [comment]
Fully agree. It's the plan and what I did. I think we have to move forward quickly to merge gearpump runner on master. It would give more visibility.

**Comment by manuzhang** [comment]
Thanks for both of you

**Pull request closed without merging**
