### PR TITLE
[BEAM-549] SparkRunner should support Beam's KafkaIO instead of providing it's own.

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
This PR will provide support for the SparkRunner to read from Kafka as best fits for Spark, yet keeping portability.
Only supports reading `TypedWithoutMetadata` for now.

**Comment by amitsela** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
R: @rangadi

**Comment by rangadi** [comment]
This provides API convenience to user and still uses Spark's native KafkaIO, essentially passing the configuration. I am not sure if that is a big improvement over current situation. In addition it is better if it is explicit to users that they are not using Beam KafkaIO.

Based on our discussion on email, it would be better to get Spark runner to support to Beam Unbounded sources. That way all of the Beam sources benefit. Even if there is a performance hit, I think that is useful. We can certainly look into improving how well Spark runner works for Beam. 

I am not sure of current state of Spark runner. will try to get more up to date.

**Comment by dhalperi** [comment]
I'm not sure I agree with @rangadi. Assuming that Spark's version of Kafka is indistinguishable to users from the Beam version of KafkaIO, it is nice to not need to change your pipeline when changing runners.

If Spark does not support `UnboundedSource` and can't do so quickly, this is a good solution. Even once Spark does support the API, it may still be better for users to override to the Spark-native solution if that brings much better performance (and as long as it is indistinguishable to users. If this is not the case, probably better to use the `UnboundedSource` implementation and log? rather than ignore silently or fail).

**Comment by rangadi** [comment]
I am not against this PR going in. API portability is certainly useful for users. There are some cases of API not supported here, and we will have to explain the difference while replying to support questions on user lists, but not a big deal.

Better to update the title of the PR and the Jira to better reflect intention.

**Comment by amitsela** [comment]
I think the PR title is accurate - currently, the SparkRunner actually provides it's own [KafkaIO](https://github.com/apache/incubator-beam/blob/master/runners/spark/src/main/java/org/apache/beam/runners/spark/io/KafkaIO.java) but the idea here is to be able to keep portability.
I am working on supporting `Read.Unbounded` and I'll have results by the end of the week, so let's keep this PR open for now.
Thanks.

**Comment by dhalperi** [comment]
(leaving open per your request. Please comment if that changes ;)

**Pull request closed without merging**
