### PR TITLE
[BEAM-287] Use flat groupId structure and full qualified artifactIds

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by tgroh** [comment]
Are artifactIds ever referenced in the absence of a groupId?

**Comment by jbonofre** [comment]
Let me take a look (it built fine on my box).

**Comment by dhalperi** [comment]
JB: should this be closed now that #423 has been merged?

**Comment by jbonofre** [comment]
Closing this PR as already covered by #423

**Pull request closed without merging**
