### PR TITLE
Migrated IO display data tests must be runner-filesystem agnostic

### PR DESCRIPTION
**Pull request by swegner**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by swegner** [comment]
R: @dhalperi 

This addresses post-commit failures from previous PR: https://builds.apache.org/job/beam_PostCommit_RunnableOnService_GoogleCloudDataflow/714/testReport/

Verified by running dataflow runnable-on-service tests locally.

**Comment by dhalperi** [comment]
Still failing everywhere -- direct runner.

**Comment by swegner** [comment]
@dhalperi PTAL

**Comment by dhalperi** [comment]
LGTM. Please sync with @peihe and Mark

**Pull request closed without merging**
