### PR TITLE
[BEAM-297] update flink README.md at line 145

### PR DESCRIPTION
**Pull request by JianfengQian**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
[BEAM-297] update flink README.md at line 145,
version of org.apache.beam should be 0.1.0-incubating-SNAPSHOT now.

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @mxm @aljoscha any reaction?

**Comment by aljoscha** [comment]
Ah yes, that one fell through the cracks. LGTM

I'll merge it. In the long run this should probably be folded into the documentation.

**Comment by aljoscha** [comment]
Thanks for fixing! @JianfengQian 😃

**Comment by mxm** [comment]
Thanks for sharing this fix with us!

**Pull request closed without merging**
