### PR TITLE
Increase the MESSAGES_POLLING_ATTEMPTS for slow backend starts

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @davorbonaci 
R: @lukecwik

**Comment by dhalperi** [comment]
R: @dhalperi to accelerate merge process. This Dataflow-runner change has been discussed in person.

**Comment by dhalperi** [comment]
LGTM. I believe that Jenkins is a flaky e2e test, but honestly I think that the flake was not our code. Still investigating, but this can be merged now.

**Comment by dhalperi** [comment]
@peihe backport?

**Pull request closed without merging**
