### PR TITLE
[BEAM-393] Adds more code snippets for Python SDK

### PR DESCRIPTION
**Pull request by chamikaramj**
Adds code snippets related to following.

(1) Creating and using a new custom source
(2) Creating and using a new custom sink
(3) Performing joins using side inputs

### CODE REVIEW

**Comment by chamikaramj** [comment]
R:@silviulica

**Comment by silviulica** [comment]
LGTM and awesome - thanks Cham! 
For the record -- we use these snippets to feed automatically code fragments into the SDK docs -- we would like a similar solution when the docs will be hosted on Apache site.

**Comment by silviulica** [comment]
Good catch! LGTM again

**Comment by chamikaramj** [comment]
Thanks Silviu.

R: @kennknowles can you take a look ?

**Comment by kennknowles** [comment]
This is a really cool system. We'd love to mimic it for Java, I bet. I feel like each START/END block deserves a little more commentary. And, of course, we should get this integrated into docs hosted on the Beam site.

I will need a little longer to grok everything and approve.

**Comment by chamikaramj** [comment]
Thanks Kenn. Please note that these snippets are designed to be integrated into websites. There should be more details in text.

I can add more comments here outside BEGIN/END tags. I'll wait for your review first.

**Comment by chamikaramj** [comment]
Added more comments. Please let me know if anything else needs to be updated.

Thanks.

**Comment by chamikaramj** [comment]
Fixed conflicts.

@kennknowles , could you PTAL.

**Comment by kennknowles** [comment]
LGTM.

There is a git convention of prefixing `fixup!` to commits that are just fixes to the prior commit (comes from the [use of `--autosquash` when rebasing](https://git-scm.com/docs/git-rebase) but I will do it manually). My impression is that there is only really one commit of changes here. Can you either squash them yourself and `git push -f` or else reword the commits to start with `fixup!`?

All of this is to just so that I don't have to sort out the right commit message. You can also just reply and let me know that the first commit message is the one you care about and I can squash the rest into that, which is what this looks like.

**Comment by chamikaramj** [comment]
Thanks Kenn.

Squashed commits into a single commit. PTAL.

**Pull request merged**
