### PR TITLE
Fix JDom malformed comment in Apex runner.

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @davorbonaci

**Comment by jbonofre** [comment]
This malformed comment causes issue on the pom transformation performed by the Maven release plugin, and so it blocks the release.

**Comment by dhalperi** [comment]
LGTM, thanks JB. Merge once tests pass.

**Comment by jbonofre** [comment]
@dhalperi awesome ! Thanks a lot !

**Comment by jbonofre** [comment]
I'm checking why Jenkins failed.

**Comment by jbonofre** [comment]
The build itself looks "SUCCESS", but Jenkins data collection failed.

**Comment by dhalperi** [comment]
No, this is an actual test failure. I think that the issues with Apex kryo serialization were not actually fixed yesterday.

**Comment by dhalperi** [comment]
@davorbonaci @kennknowles @tgroh @tweise

**Comment by dhalperi** [comment]
(Confirming that this PR looks like it is built from head, so it's not just missing the fix.)

**Comment by jbonofre** [comment]
@dhalperi yeah good catch. And yes, the PR is on master head.

**Comment by kennknowles** [comment]
PRs are built from their merge commit.

Chatted a bit, and the necessary  `@Bind` annotation was already in place. It is only supported by later versions of Keys, so it was likely overridden by our shared dependency set up. I'll take a look shortly, if there's not already an investigation/fix underway.

**Comment by davorbonaci** [comment]
LGTM. Merging.

**Pull request closed without merging**
