### PR TITLE
[BEAM-889] CheckpointDir option does not accept relative path and req…

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

…uires protocol.

### CODE REVIEW

**Comment by amitsela** [comment]
This seems much more friendly (and less code!).

Spark already does it's [due-diligence](https://github.com/apache/spark/blob/branch-1.6/streaming/src/main/scala/org/apache/spark/streaming/StreamingContext.scala#L231) on the provided checkpoint dir so no need to double verify.
Still warn if prefix does not much a reliable storage.

**Comment by amitsela** [comment]
Jenkins failed on Dataflow IT test, unrelated.

**Comment by amitsela** [comment]
R: @tgroh

**Comment by amitsela** [comment]
R: @jbonofre if you're available ;-)

**Comment by jbonofre** [comment]
Sure ! Thanks !

**Comment by tgroh** [comment]
The commit message doesn't seem to match the actual change, which is basically "handle relative paths in Spark CheckpointDir"

other than that, LGTM.

**Comment by amitsela** [comment]
@tgroh it describes the issue instead of the solution.. mostly to match the ticket.
I'll change the commit message (leaving the ticket id) as it does make more sense.
Thanks!

**Comment by jbonofre** [comment]
LGTM

**Pull request closed without merging**
