### PR TITLE
checkstyle: enforce where line breaks happen

### PR DESCRIPTION
**Pull request by dhalperi**
We should do it consistently throughout the SDK. Only a few
fixups.

Ported from: https://github.com/checkstyle/checkstyle/blob/ccdc3c09c500ccd31d56e4d6ed9c2d86edf2e9f1/src/main/resources/google_checks.xml#L167

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @tgroh @davorbonaci @amitsela

**Comment by tgroh** [comment]
Jenkins seems to not like this.

LGTM

**Comment by dhalperi** [comment]
Jenkins has other issues, unrelated to this. (Follow the link)

**Comment by amitsela** [comment]
👍

**Pull request closed without merging**
