### PR TITLE
[BEAM-329] Update Spark runner README.

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Waiting the end of the test to merge.

**Comment by amitsela** [comment]
I updated the README. Also made it a bit more official in terms of supported features.
I would really like to have here a Cluster example and an example/starter pom for local/deployed app but not having HDFS support really gets in the way for now and since I see README as something "official" I'd rather remove (for now) things like cluster example and example pom.
If this change is OK, we should open another ticket to follow BEAM-59 and once HDFS is properly supported we can reinstate cluster example and add pom example. 
R: @jbonofre

**Comment by amitsela** [comment]
I changed the ticket and PR name to be a bit more suitable. Care to change the commit name appropriately on merge ?

**Comment by jbonofre** [comment]
Sure np

**Pull request closed without merging**
