### PR TITLE
[BEAM-684] pom.xml: replace dataflow.javadoc_opts with beam.javadoc_opts

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by dhalperi** [comment]
R: @kennknowles for careful reading of legacy Dataflow javadoc. (low priority, I will keep appending to this PR over time if not reviewed ;).

**Comment by dhalperi** [comment]
(136 -> 95 Dataflows in SDK core after changes so far)

**Comment by jbonofre** [comment]
LGTM but weird travis failed (I'm checking).

**Comment by kennknowles** [comment]
Since it requires careful reading, I may not get to it until after Strata is over.

**Comment by dhalperi** [comment]
Ping @kennknowles

**Comment by kennknowles** [comment]
LGTM. There's a conflict with master (presumably in javadoc). If you want another round after resolving conflicts, LMK.

**Comment by dhalperi** [comment]
Thanks, resolved conflict; confirmed compile; and merged

**Pull request closed without merging**
