### PR TITLE
[Beam-43] Upgrade to Spark 1.6

### PR DESCRIPTION
**Pull request by amitsela**
Upgrade to Spark 1.6.1 (latest) and resolve some involved deprecations.

### CODE REVIEW

**Comment by amitsela** [comment]
R: @jbonofre

**Comment by dhalperi** [comment]
(LGTM. If you wanted JB to specifically review, ignore ;)

**Comment by jbonofre** [comment]
LGTM

**Comment by amitsela** [comment]
@dhalperi you're just as good :)

will merge

**Pull request closed without merging**
