### PR TITLE
[BEAM-1165] Fix unexpected file creation when checking dependencies

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @aljoscha

**Comment by dhalperi** [comment]
This is an AWESOME catch! Wow. I have never been able to track that down.

While you're doing this, maybe let's put the property in a private namespace? like `flink.wordcount.input`?

**Comment by dhalperi** [comment]
Looking around a little more, might be better as something like `flink.examples.input` [and also add `parallelism` to the namespace while at it.]

**Comment by aljoscha** [comment]
Are `input` and `output` reserved words? Or what was the problem?

(Off topic: I'd like to get rid of the separate Flink examples POM at some point.)

**Comment by iemejia** [comment]
Ok, I did the changes as suggested thanks for checking @dhalperi .

@aljoscha It seems that at leaste output is the reserved word
https://maven.apache.org/plugins/maven-dependency-plugin/tree-mojo.html#output

It is ike a trickier scoping issue at the maven-dependency-plugin, and considering that you plan to get rid of this later on, I think this fix is enough for the moment.

**Comment by aljoscha** [comment]
I see, thanks for the explanation!

**Comment by iemejia** [comment]
Can someone of you guys give the OK and merge (if is it ok now of course), thanks.

**Comment by aljoscha** [comment]
Yes, sorry for the delay. I'm merging.

And thanks for finding and fixing this again! 👍

**Comment by iemejia** [comment]
Thank you guys for the review/merge.

**Comment by aljoscha** [comment]
Could you please close the Jira issue? I forgot that.

**Pull request closed without merging**
