### PR TITLE
Add type hints to bigshuffle to avoid pickle overhead.

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @mdvorsky

**Comment by silviulica** [comment]
@robertwb - the code analysis does not pick up that the lambda expression returns a KV[str, str]?
We will need to give a warning to people for similar cases so they do not get unexpected performance degradation.

**Comment by robertwb** [comment]
Agreed, the type inference should be smarter (I don't think it handles slices). I think we also need to fall back to better default than pickling, e.g.

https://github.com/robertwb/incubator-beam/commit/af73fff4092913fb0050ee9ebec874535743b5eb

**Comment by mdvorsky** [comment]
LGTM

**Pull request closed without merging**
