### PR TITLE
[BEAM-488] Remove KEYS file

### PR DESCRIPTION
**Pull request by dhalperi**
Per discussion, linked in JIRA:

> Bundling PGP keys inside a package is worse than worthless – an
> attacker can just bundle spoofed keys with a bogus distro! Keys need
> to be made available from a highly reliable, separate server: Download
> the main package from a mirror, get PGP keys from apache.org,
> pgp.mit.edu, etc. and verify.
>
> The KEYS file within the Beam source tree should be deleted.

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Agree to remove the KEYS from the distro. However, instead of using the "global" KEYS file, I would prefer to have a Beam KEYS file. 
It's what we are doing in most of other Apache projects:
- http://svn.apache.org/repos/asf/karaf/KEYS
- http://svn.apache.org/repos/asf/servicemix/KEYS
- https://github.com/apache/camel/blob/master/KEYS

So, what do you think about excluding KEYS from the distro but keeping KEYS on our git ?

**Comment by dhalperi** [comment]
Since keys is required on the distro site, I am concerned that we have the same info in two places -- they will get out of sync. Since the distro is required, I'd prefer to drop the keys file here.

I also looked at 3 of the biggest Apache projects, and they do not have a `KEYS` file:

* [Maven](https://github.com/apache/maven)
* [Hadoop](https://github.com/apache/hadoop)
* [Avro](https://github.com/apache/avro)

**Comment by dhalperi** [comment]
So I'd like to drop our `KEYS` -- okay with you?

**Comment by jbonofre** [comment]
Fair enough.

LGTM. I'm merging.

**Comment by jbonofre** [comment]
By the way, I'm also updating the main committers KEYS file ;)

**Comment by jbonofre** [comment]
By the way, Maven has its own KEYS file: https://maven.apache.org/developers/release/pmc-gpg-keys.html

**Comment by jbonofre** [comment]
https://svn.apache.org/repos/asf/maven/project/KEYS

**Comment by jbonofre** [comment]
Same for Hadoop: https://dist.apache.org/repos/dist/release/hadoop/common/KEYS

**Comment by jbonofre** [comment]
So, what I'm proposing:

1. I can move the KEYS on dist.apache.org
2. Then we can remove the KEYS from git

WDYT ?

**Pull request closed without merging**
