### PR TITLE
[BEAM-386] Copy and use UnboundedReadFromBoundedSource in dataflow runner

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @dhalperi @kennknowles

**Comment by dhalperi** [comment]
Generally LGTM, with a few fixes:

* File a JIRA issue -- Dataflow runner to support Read.Bounded in streaming mode.
* add `@Deprecated` to the google-cloud-dataflow copy of URFBS.
* rename to `DataflowUnboundedReadFromBoundedSource`?

Also,
* move the examples cleanup to a separate PR

**Comment by peihe** [comment]
Done

**Comment by dhalperi** [comment]
LGTM

**Pull request closed without merging**
