### PR TITLE
[BEAM-211] Replace usages of PCollection.setCoder with Create.of().withCoder 

### PR DESCRIPTION
**Pull request by ilganeli**
* Replaced all usages of ```PCollection.setCoder`` with the recommended ```withCoder```.

### CODE REVIEW

**Comment by ilganeli** [comment]
Retest this please

**Comment by ilganeli** [comment]
Looks like the Jenkins failure is due exclusively to a connection failure when pulling Flink dependencies.

**Comment by kennknowles** [comment]
LGTM. Thanks!

**Comment by amitsela** [comment]
I actually opened [[BEAM-211]](https://issues.apache.org/jira/browse/BEAM-211) as a `runner-spark` issue since this appears all over the runner's unit tests..
I actually didn't think we had this issue in the SDK as well.
I'll reopen as a new JIRA and be more specific. 
Thanks for the contribution @ilganeli and feel free to checkout the same issue in the Spark runner 😃

**Comment by ilganeli** [comment]
@amitsela This brings up an interesting point. If an issue is specific to the Spark Runner, which is maintained as a separate project, is that still tracked within Beam?

**Pull request closed without merging**
