### PR TITLE
[BEAM-79] Add Gearpump runner to runners parent pom.xml

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

I think this line got lost in the shuffle. It is why we aren't seeing the module in the Jenkins web UI, though the [tests are running and passing](https://builds.apache.org/view/Beam/job/beam_PostCommit_RunnableOnService_GearpumpLocal/).

R: @dhalperi 
CC: @manuzhang

### CODE REVIEW

**Comment by dhalperi** [comment]
LGTM

**Comment by dhalperi** [comment]
Hmm, the travis failure is kind of worrying. @manuzhang does Gearpump require Java 8? Beam is generally trying very hard to keep the core at Java 7.

That said, we can easily add an option to travis to disable Gearpump in Java 7 builds if this is required.

**Comment by manuzhang** [comment]
@kennknowles @dhalperi 
I'm afraid that line is not lost. Gearpump requires Java 8 so I put it in the profile.

```
    <profile>
      <id>java8</id>
      <activation>
        <jdk>[1.8,)</jdk>
      </activation>
      <modules>
        <module>gearpump</module>
      </modules>
    </profile>
```

**Comment by kennknowles** [comment]
Right, of course. It is unfortunate that it fails to appear in Jenkins when it did run.

**Pull request closed without merging**
