### PR TITLE
Remove DataflowMatchers

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This is a Dataflow-specific requirement and should not be present within
the core Beam SDK.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Will this break Dataflow streaming at HEAD?

**Comment by dhalperi** [comment]
container 20160921 is pushed with the corresponding fix

**Comment by dhalperi** [comment]
please confirm windowed word count, etc., works

**Comment by tgroh** [comment]
No. This is purely a testing utility.

**Comment by dhalperi** [comment]
Gotcha; LGTM

**Pull request closed without merging**
