### PR TITLE
[BEAM-757, BEAM-807] new DoFn via SimpleDoFnRunner

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
R: @kennknowles 
CC: @jkff - this should leave very little (and trivial) changes to the Spark runner in #1565.

**Comment by amitsela** [comment]
`E2E` failure is related to `Apex`.
`ResumeFromCheckpointStreamingTest` flakiness is being handled by #1579.

**Comment by kennknowles** [comment]
I think both are fixed, so a rebase should do it. I don't recall if Jenkins re-merges. If so, then that should also suffice, so I will try it.

**Comment by kennknowles** [comment]
retest this please

**Comment by amitsela** [comment]
Rebased and while I was at it i did some squashing and fancied-up the commit messages 😉

**Comment by amitsela** [comment]
Travis fails 2/5 on `Maven Archtypes`, unrelated.

**Comment by amitsela** [comment]
`E2E` failure is `Apex`, unrelated.

**Comment by kennknowles** [comment]
Confirmed that `mvn clean verify` succeeds (Travis already shows this) and that the Spark runner integration tests succeed via the following command after a clean install:

```
mvn --errors failsafe:integration-test@spark-runner-integration-tests \
    -pl examples/java \
    -P jenkins-precommit,apex-runner,spark-runner,flink-runner,dataflow-runner,direct-runner \
    -D beamTestPipelineOptions='[
      "--runner=org.apache.beam.runners.spark.TestSparkRunner",
      "--project=...",
      "--tempRoot=..."
    ]'
```

**Pull request merged**
