### PR TITLE
Merge master into runners-spark2 branch to keep up-to-date

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
I've merged master into the runners-spark2 branch so I could keep working against an updated branch.
@jbonofre @kennknowles or any other committer for that matter.

**Comment by lukecwik** [comment]
LGTM

**Comment by jbonofre** [comment]
LGTM

**Comment by dhalperi** [comment]
Looks like @amitsela will have to close this PR manually since the "closes #585" commit was merged into a branch, not master.

**Comment by amitsela** [comment]
I was just wondering about it..
I'll close, thanks @lukecwik !

**Pull request closed without merging**
