### PR TITLE
Add some built artifacts to gitignore

### PR DESCRIPTION
**Pull request by kennknowles**

### CODE REVIEW

**Comment by kennknowles** [comment]
Just noticed this directory pop up after a build. Good to ignore @amitsela?

**Comment by kennknowles** [comment]
I don't know why I thought this was the Spark runner. Brain malfunction.

**Comment by kennknowles** [comment]
@mxm is there any reason we should not have git ignore this directory?

**Comment by mxm** [comment]
I don't think this comes from the Flink Runner. By default, the examples write to a user-specified path or to the project basedir (which would be `runners/flink/examples`). Would be nice to find out where the directory is created...

**Comment by kennknowles** [comment]
Interesting. I first confirmed that after building the Flink runner and examples I don't see the folder. And then `mvn install` did not produce the folder. So I am going to just close this PR.

**Pull request closed without merging**
