### PR TITLE
[BEAM-362] Move ActiveWindowSet and implementations to runners-core

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

In service, ultimately, of clearing all state internals out of the SDK.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @amitsela this will require me to get LGTM and then bump Dataflow to be ready for the change

**Comment by amitsela** [comment]
Failures are `Apex` related so LGTM. Not sure if you want to bump Dataflow before merging so I'll leave this one to you.

**Comment by kennknowles** [comment]
retest this please

**Comment by amitsela** [comment]
retest this please

**Comment by amitsela** [comment]
Looks like Dataflow still didn't "bump" ?
`Exception: java.lang.NoClassDefFoundError: org/apache/beam/sdk/util/ActiveWindowSet$MergeCallback`

**Comment by kennknowles** [comment]
Yea, I didn't bump yet. Just retested to clear out the other errors. It'll happen soon...

**Comment by kennknowles** [comment]
It seems that the Jenkins build from when this had conflicts actually did run and did succeed. I don't understand how it successfully merged - if it pulled by PR # instead of by hash and got the conflict-resolved version then that success would presumably be reflected on the commit status. Very confusing.

**Pull request merged**
