### PR TITLE
[BEAM-742] Remove pieces of Trigger now owned by TriggerStateMachine

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

The state machine methods `onElement`, `onTimer`, `shouldFire`, `onTrigger`, `clear`, etc, are all now part of `TriggerStateMachine` in runners-core. This is another PR in the endeavor to turn `Trigger` into a simple syntax tree that will be serialized to language-agnostic JSON embedded in the pipeline graph in the Runner API. Prior PRs, for reference, are #1083, #1101, #1138.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @tgroh / @aljoscha (two different time zones :-)

**Comment by kennknowles** [comment]
Since this review should hopefully consist of "I deleted a bunch of stuff that didn't break the tests", and I actually did break the tests, feel free to not review just yet.

**Comment by kennknowles** [comment]
Or, if you like, review the deletions and give a :+1: pending deployment/tests green.

**Comment by kennknowles** [comment]
The integration test failures are now fixed. Please do review.

**Comment by aljoscha** [comment]
Why is `ExecutableTrigger` not yet removed and why is `Trigger.getWatermarkThatGuaranteesFiring()` still in `Trigger`?

Other than that, this LGTM! (I'm hoping that travis will not fail anymore once you merge... 😃)

**Comment by kennknowles** [comment]
The reason I left `ExecutableTrigger` is because of `WindowingStrategy.getTrigger()`. We only really ever need `WindowingStrategy.getTrigger().getSpec()` but eliminating the extra level of indirection is yet another migration step.

And I left `getWatermarkThatGuaranteesFiring()` because it is actually a property of the abstract trigger, not especially a property of the state machine, just like `continuationTrigger`.

So I'm hoping my answer is enough to satisfy your prerequisites for LGTM. I will merge this, and definitely will be following up with eliminating `ExecutableTrigger`. The discussion of what methods to finally leave on `Trigger` can be ongoing.

**Comment by aljoscha** [comment]
Perfect, I was just interested in how you might proceed there. 👍

**Pull request merged**
