### PR TITLE
[BEAM-105] We may attempt to remove an inactive window from the active window set.

### PR DESCRIPTION
**Pull request by mshields822**

### CODE REVIEW

**Comment by mshields822** [comment]
Ken noticed was closed due to a spurious commit message in the spark runner commit. Sigh.

**Comment by amitsela** [comment]
Nice catch! I think this was the one responsible: https://github.com/tomwhite/incubator-beam/commit/06e611a7516ef2fc61d43b1edd7aa6a7c3caf194 
Sorry..

**Comment by mshields822** [comment]
@kennknowles  PTAL

**Comment by kennknowles** [comment]
LGTM. Merging in.

**Comment by mshields822** [comment]
This time for real!

**Pull request merged**
