### PR TITLE
[BEAM-462] Replace MonitoringUtil.PrintHandler with a handler that utilizes a Java logger

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @tgroh

**Comment by tgroh** [comment]
Is there any documentation about where output messages will be flushed to in the `BlockingDataflowRunner`?

Otherwise, LGTM

**Comment by lukecwik** [comment]
Fixed javadoc in BlockingDataflowRunner

**Comment by tgroh** [comment]
LGTM

**Comment by peihe** [comment]
After this PR, is the default logging same in BlockingDataflowRunner, logs job messages to System.out?

And, how users change to log job messages to file, through slf4j config file? I think users also want to config workers logging and PipelineRunner.run() logging separately.

**Comment by lukecwik** [comment]
This changes the logging of job messages to use the SLF4J logger which will delegate logging to any logger the user has configured for the SLF4J backend. For example, if they configure their application to use log4j, then they can have a log4j config which sets the log level and output location in their log4j.properties file. They can use any supported SLF4J backend logger like log4j, JUL, JCL, ... and associated configuration to control the output now.

**Pull request closed without merging**
