### PR TITLE
BEAM-682-Invoker Class should be created in Thread Context Classloader

### PR DESCRIPTION
**Pull request by sumitchawla**
As of now the InvokerClass is being loaded in wrong classloader. It should be loaded into Thread.currentThread.getContextClassLoader()
https://github.com/apache/incubator-beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/DoFnInvokers.java#L167

```
 Class<? extends DoFnInvoker<?, ?>> res =
        (Class<? extends DoFnInvoker<?, ?>>)
            unloaded
                .load(DoFnInvokers.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                .getLoaded();
```

Fix

```
 Class<? extends DoFnInvoker<?, ?>> res =
        (Class<? extends DoFnInvoker<?, ?>>)
            unloaded
                .load(Thread.currentThread().getContextClassLoader(),
                        ClassLoadingStrategy.Default.INJECTION)
                .getLoaded();
```

### CODE REVIEW

**Comment by kennknowles** [comment]
Can you add a regression test to protect us from accidentally re-introducing the error?

**Comment by sumitchawla** [comment]
@kennknowles  sure will do that.  Is there any easy way to run the IT tests (@Category(NeedsRunner.class)) directly from IDE like IntelliJ? Running the tests through only maven is little painful. (some maven issue forces me to do full clean for running any incremental tests)

**Comment by kennknowles** [comment]
Yes, and I agree that it can be painful otherwise.

In IntelliJ, you can run "all in directory" for the core SDK, but with the classpath of the module `beam-runners-direct-java` to run them all with the direct runner. @tgroh, do you recommend this or another way? 

Does the issue repro in the direct runner?

**Comment by bjchambers** [comment]
I worry about this. The fact that this is necessary means that there are cases where the ClassLoader that pulled in DoFnInvokers differs from the ClassLoader of the thread running user code. Is this only happening in specific runners? It would be good to understand the cases this can happen.

The larger potential problem is that we cache the loaded class. So, with just this change, we're now assuming that whichever ClassLoader was associated with the thread the first time we created a DoFnInvoker will always be the ClassLoader associated with all future threads that create DoFnInvokers.

Given that the first assumption (they're the same) is being violated, how do we know the second is a valid assumption? If we need to go down this route (and we should understand the runner environment leading to it), we may need to have a per-ClassLoader cache of the DoFnInvoker classes, allowing us to load it into each ClassLoader we need it in.

**Comment by tgroh** [comment]
@kennknowles That's the way I do it, and I don't believe that there's another way - the classpath modification is roughly equivalent to the maven test suppressions and classpath-scanning that we perform.

**Comment by sumitchawla** [comment]
@bjchambers We noticed this in FlinkRunner.  The class which generated NoClassDefError is available in user classloader.

Attached is the stack trace that i got.

```
java.lang.NoClassDefFoundError: com/example/SinkImpl
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.apache.beam.sdk.transforms.reflect.DoFnInvokers.getOrGenerateByteBuddyInvokerConstructor(DoFnInvokers.java:120)
	at org.apache.beam.sdk.transforms.reflect.DoFnInvokers.newByteBuddyInvoker(DoFnInvokers.java:98)
	at org.apache.beam.sdk.transforms.reflect.DoFnInvokers.newByteBuddyInvoker(DoFnInvokers.java:83)
	at org.apache.beam.sdk.transforms.DoFnAdapters$SimpleDoFnAdapter.readObject(DoFnAdapters.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:291)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:249)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:195)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:275)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:212)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:271)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:212)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:271)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:212)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:105)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:225)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:584)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kennknowles** [comment]
Now that I've had a chance to think about this a little, I don't think the context class loader is necessarily the best answer. The important thing is for the user's `DoFn` class to be available from the generated class. Can we use `fnClass.getClassLoader()`?

**Comment by dhalperi** [comment]
R: @kennknowles @tgroh

**Comment by kennknowles** [comment]
Sumit - have you found another workaround for this issue? I would love to move forward with this PR, as it does seem useful once we get it right and tested.

**Comment by sumitchawla** [comment]
@kennknowles we did a workaround by moving all beam dependencies to user class path, and packaging them with user code

**Comment by kennknowles** [comment]
OK. If you are not interested in moving forwards here, would you care to close the pull request?

**Comment by sumitchawla** [comment]
sure. thanks

**Pull request closed without merging**
