### PR TITLE
[BEAM-540] Do not add DataDisks to windmill service jobs.

### PR DESCRIPTION
**Pull request by drieber**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by drieber** [comment]
Hey @dpmills please take a look. Thanks.

**Comment by dpmills** [comment]
LGTM

**Comment by drieber** [comment]
@dhalperi Hi Dan, can you please merge this change.

**Comment by dhalperi** [comment]
Consider where this logic should live in the long term. Seems like something that could be moved to inside the runner and then be controllable/updatable without an SDK release.

LGTM for now.

**Pull request closed without merging**
