### PR TITLE
[BEAM-362] Remove deprecated AggregatorFactory from SDK

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

The reason this change actually adds real value is that it is the last reference to `ExecutionContext` in the SDK. After this PR, we can move all that to runners-core, which in turn starts to unblock moving `StateInternals` and `TimerInternals` to runners-core. I haven't included that here since it will require a Dataflow worker process while this will go right in.

R: @lukecwik (randomly selected committer)

### CODE REVIEW

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
Waiting on tests to pass and will merge.

**Comment by lukecwik** [comment]
Failed with:
(2f145d1721975631): java.lang.NoClassDefFoundError: org/apache/beam/sdk/transforms/Aggregator$AggregatorFactory
 at com.google.cloud.dataflow.worker.runners.worker.DataflowDoFnRunners.create(DataflowDoFnRunners.java:82)
 at com.google.cloud.dataflow.worker.runners.worker.SimpleParDoFn.reallyStartBundle(SimpleParDoFn.java:192)
 at com.google.cloud.dataflow.worker.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:212)
 at com.google.cloud.dataflow.worker.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42)
 at com.google.cloud.dataflow.worker.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47)
 at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:48)
 at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:52)
 at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:198)
 at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
 at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:70)
 at com.google.cloud.dataflow.worker.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:307)
 at com.google.cloud.dataflow.worker.runners.worker.DataflowWorker.doWork(DataflowWorker.java:251)
 at com.google.cloud.dataflow.worker.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:203)
 at com.google.cloud.dataflow.worker.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:246)
 at com.google.cloud.dataflow.worker.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:226)
 at com.google.cloud.dataflow.worker.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:213)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

**Comment by kennknowles** [comment]
Ah, yes. This also needs a new worker, but it can be built from HEAD without having to do any fancy process.

**Pull request merged**
