### PR TITLE
Fixes crash of shade plugin on SparkProcessContext

### PR DESCRIPTION
**Pull request by jkff**
Error discovered by debugging the Maven plugin itself
(using mvnDebug) and setting a breakpoint for the exception
and then inspecting the call stack to spot a weird-looking
method signature descriptor:

`Lorg/apache/beam/sdk/transforms/windowing/WindowFn<Ljava/lang/Object;!*>.AssignContext;`

(note the exclamation mark, which is an invalid character AFAIK!
I have no idea where it came from, but the current change makes it go away)

R: @dhalperi 
CC: @amitsela

### CODE REVIEW

**Comment by jkff** [comment]
Example failure reminder: https://s3.amazonaws.com/archive.travis-ci.org/jobs/172122953/log.txt (in #1201)

**Comment by jkff** [comment]
How I ran mvn for debugging:
1. Ran mvn clean install once
2. `~/maven-3.3.9/bin/mvnDebug -pl :beam-runners-spark -Peclipse-jdt -e install org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade`

**Comment by jkff** [comment]
I suspect this is a bug in the Eclipse compiler. I'll try to figure that out in parallel.

**Comment by jkff** [comment]
Yup, definitely Eclipse compiler bug. Set IntelliJ to use Eclipse compiler, asked to compile project.

`javap './runners/spark/target/classes/org/apache/beam/runners/spark/translation/SparkProcessContext$1.class'`
Compiled from "SparkProcessContext.java"
Error: A serious internal error has occurred: java.lang.IllegalStateException: Lorg/apache/beam/sdk/transforms/windowing/WindowFn<Ljava/lang/Object;!!!*>.AssignContext;
Please file a bug report, and include the following information:
java.lang.IllegalStateException: Lorg/apache/beam/sdk/transforms/windowing/WindowFn<Ljava/lang/Object;!!!*>.AssignContext;
	at com.sun.tools.classfile.Signature.parseTypeSignature(Signature.java:180)
	at com.sun.tools.classfile.Signature.parseTypeSignatures(Signature.java:188)
	at com.sun.tools.classfile.Signature.parseClassTypeSignatureRest(Signature.java:208)
	at com.sun.tools.classfile.Signature.parseClassTypeSignature(Signature.java:196)
	at com.sun.tools.classfile.Signature.parseTypeSignature(Signature.java:146)
	at com.sun.tools.classfile.Signature.parse(Signature.java:104)
	at com.sun.tools.classfile.Signature.getType(Signature.java:48)
	at com.sun.tools.javap.ClassWriter.write(ClassWriter.java:187)
	at com.sun.tools.javap.JavapTask.write(JavapTask.java:784)
	at com.sun.tools.javap.JavapTask.writeClass(JavapTask.java:606)
	at com.sun.tools.javap.JavapTask.run(JavapTask.java:560)
	at com.sun.tools.javap.JavapTask.run(JavapTask.java:423)
	at com.sun.tools.javap.Main.main(Main.java:46)

**Comment by jkff** [comment]
Minimal repro:
```
public class EclipseBug {
  private static class Generic<T> {
    class Inner {}
  }

  private  static void foo(Generic<?> generic) {
    generic.new Inner() {};
  }
}
```

I'll file a bug to Eclipse.

**Comment by dhalperi** [comment]
Wowza. That's "fun".

cc: @dkulp

**Comment by dhalperi** [comment]
(Jenkins presubmit bug is my fault, fixed now.)

**Comment by jkff** [comment]
Travis failure is a transient timeout.

**Comment by dkulp** [comment]
Do you know if updating Tycho from 0.24 to 0.26 fixes this?   (would require updating the travis build to java8, but we likely should do that anyway)

**Comment by dhalperi** [comment]
@dkulp it doesn't. I have a separate PR where I've made the Java8 switch per our prior discussion, but since Eugene fixes the root cause I have deferred it until this gets in.

**Pull request closed without merging**
