### PR TITLE
Pylint integration for Python SDK

### PR DESCRIPTION
**Pull request by aaltay**
This change introduces a pylint rule to keep the code base in a consistent state. Pylint configuration is heavily influenced by the existing standards in the code. Even with this there were multiple pylint issues. In order to make this change submit locking and also affect the others minimally I made the following choices:

- Enabled line length (80 chars), and indentation rules (2 spaces, and 4 spaces after parentheses.).
- Disabled all other rules. I will work on fixing violations of those and enabling them one by one.
- Run pylint only on those files under python/sdks/apache_beam/**/*.py and that changed compared to python_sdk branch HEAD. Note that this is files changed not lines changed.
- Made it submit blocking. Travis will fail if there are lint errors.

You can install pylint (pip install pylint) and run it locally:

$ cd sdks/python
To run on all files:

$ pylint apache_beam

To run on all changed files (Diff of last commit to python-sdk branch HEAD):
$ ./run_pylint.sh

### CODE REVIEW

**Comment by aaltay** [comment]
R: @silviulica

**Comment by silviulica** [comment]
LGTM - Thanks Ahmet!

**Comment by aaltay** [comment]
@dhalperi Could you please take a look?

**Comment by dhalperi** [comment]
LGTM, merged. Please close PR manually.

**Comment by aaltay** [comment]
Thank you Dan.

**Pull request closed without merging**
