### PR TITLE
[BEAM-1079] Improve validation speed for large number of files

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Do not need to list all files in GCS for validation. Add limit field to fileIO

### CODE REVIEW

**Comment by sb2nov** [comment]
R: @chamikaramj PTAL

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by sb2nov** [comment]
@davorbonaci please merge.

Thanks you.

**Comment by davorbonaci** [comment]
Conflicts. Please rebase on top of the current python-sdk branch.

**Comment by sb2nov** [comment]
@davorbonaci fixed now. Thanks again.

**Comment by sb2nov** [comment]
@davorbonaci ping for merge

**Comment by dhalperi** [comment]
Can merge, if @davorbonaci or @robertwb hsa not.

But: is there a JIRA issue for this change?

**Comment by sb2nov** [comment]
@dhalperi that would be great. There is no JIRA for this right now.

**Comment by davorbonaci** [comment]
Please file it & update the title.

**Comment by sb2nov** [comment]
@davorbonaci done, thanks.

**Comment by dhalperi** [comment]
Merged, thanks.

**Comment by sb2nov** [comment]
Thanks

**Pull request closed without merging**
