### PR TITLE
Change PAssert's dummy inputs from (Void) null to integer 0

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
Just checking that Jenkins has the same failures with just this change.

**Comment by amitsela** [comment]
In Spark (streaming), in order to invoke the transformation that actually executes the "RunChecks", we need to create an element to use as the "trigger" for this transformation (it won't execute on no-data).
I think it's the same for Beam and probably because it's the same for Cloud Dataflow, that's why `OneSideInputAssert` for example used to apply `Void`.
In https://github.com/apache/incubator-beam/blob/master/runners/spark/src/main/java/org/apache/beam/runners/spark/translation/streaming/StreamingTransformTranslator.java#L140 I take this special use case into consideration just for PAsserts.
So `null` input with `VoidCoder` was OK for the Spark runner, while VarIntCoder could "confuse" it with an actual input.
Keep in mind that while Beam is built with tests as a "first class citizen" it's not so in Spark - don't know about other runners, and pretty sure that not in such a complete way as in Beam.
Would it be awkward to have a "PLACEHOLDER" (not good with names..) coder with the same value (0) ? that way there are no nulls, but the coder implies that this is not a "real" value to process.

**Comment by amitsela** [comment]
Anyway, I can fix this, would it be OK to push into this PR branch ?

**Comment by kennknowles** [comment]
I don't quite understand why switching from `null` to `0` causes the failures, but any fix is great. You could pull this branch and add your fix, or just PR your fix. Or has my change broken something in an expected way? I will upgrade this PR to more than a demo if that makes sense.

**Comment by kennknowles** [comment]
I was hoping this change would actually make things easier for all runners by basing `PAssert` on things that are more likely to be universally supported from an early stage of runner development.

**Comment by amitsela** [comment]
I think I was a bit confusing and verbose, this change did make things simpler, it allows me (as a runner developer) to ignore the special `null` case.
You'll see in my fix..

**Comment by amitsela** [comment]
I can't seem to push to this PR, permissions issues. 
You can use PR https://github.com/apache/incubator-beam/pull/331 it's not "by the books" with the naming and all because I don't want to keep you blocked, and I do want to go to sleep 😄 
Feel free to use it or simply copy the code, what ever works best for you, I don't mind.

**Comment by amitsela** [comment]
And just to be clear, this change did achieve the goal you were aiming for 😃

**Comment by kennknowles** [comment]
BTW as to the branches - this branch is on the `kennknowles` fork, so the best way to use it is to pull it down and then add to it, and push the result up to your own fork and PR from there, or PR back to this branch if you like.

Anyhow, awesome, and I will get everything all merged & rebased as appropriate.

**Comment by kennknowles** [comment]
Great. Since this is one commit from a whole PR with many LGTMs and other feedback, I will go ahead and merge.

**Pull request merged**
