### PR TITLE
[BEAM-820] Fix and streamline Travis CI configuration

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

1. Tidy up env vars
2. Use settings universally
3. Skip javadoc, checkstyle, findbugs, which are covered well by Jenkins and do not benefit from a test matrix.

### CODE REVIEW

**Comment by kennknowles** [comment]
Example failure: https://s3.amazonaws.com/archive.travis-ci.org/jobs/170276418/log.txt

**Comment by kennknowles** [comment]
@dhalperi the Travis failures here are the ones mentioned where `WordCount` class cannot be found. Is there something in this change that you think triggers it?

**Comment by kennknowles** [comment]
R: @lukecwik (Dan & Davor have been in Travis discussions, but are overloaded)

It is hard for me to tell from the state of the repo whether or not this worked. There is no attempt to download 0.4.0 snapshots, which there used to be, but I cannot tell if that is just because it is failing earlier :-/

**Comment by kennknowles** [comment]
It works somewhat. No flakes and smaller times, but an odd error in the Eclipse profile.

**Comment by dhalperi** [comment]
We have this coverage in Jenkins, I think this is great. Merged.

**Pull request closed without merging**
