### PR TITLE
Deduplicates ParDo{Single,Multi}EvaluatorFactory

### PR DESCRIPTION
**Pull request by jkff**
This is in preparation for adding a third one for a future ParDo-like primitive
transform to be introduced inside SplittableParDo.

R: @tgroh

### CODE REVIEW

**Comment by jkff** [comment]
This is hitting the same unrelated compile error in Spark runner https://github.com/apache/incubator-beam/blob/master/runners/spark/src/main/java/org/apache/beam/runners/spark/io/SourceRDD.java#L220

2016-10-27T02:56:47.631 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project beam-runners-spark: Compilation failure
2016-10-27T02:56:47.631 [ERROR] /home/travis/build/apache/incubator-beam/runners/spark/src/main/java/org/apache/beam/runners/spark/io/SourceRDD.java:[220]
2016-10-27T02:56:47.631 [ERROR] scala.collection.immutable.List.empty();
2016-10-27T02:56:47.631 [ERROR] ^^^^^
2016-10-27T02:56:47.631 [ERROR] The method empty() is ambiguous for the type List
2016-10-27T02:56:47.631 [ERROR] -> [Help 1]
2016-10-27T02:56:47.631 [ERROR]

**Comment by jkff** [comment]
Isn't that what the current PR effectively does? It uses "template method" pattern which is basically composition; and the template methods are exactly as you described (application -> DoFn and DoFn (+ context) -> TransformEvaluator).

**Comment by jkff** [comment]
OK, fixed per offline discussion to use composition (a "hooks" interface).

**Comment by tgroh** [comment]
LGTM

**Pull request closed without merging**
