### PR TITLE
Restore ReshuffleTriggerTest to SDK

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @lukecwik 

This restore was missed in a64acb2f from #1083, where all prior trigger files were restored for compatibility. We have some internal dependencies lingering.

### CODE REVIEW

**Comment by kennknowles** [comment]
Jenkins failures are actually internal failures of the Dataflow service, not this PR.

**Comment by lukecwik** [comment]
Your comment makes it seem like the ReshuffleTriggerTests aren't useful. Are they not useful anymore?

**Comment by kennknowles** [comment]
`ReshuffleTriggerTest` still provides unit tests for `ReshuffleTrigger`. Both are going away ASAP, but this restore should definitely be done.

**Comment by kennknowles** [comment]
Rebased to kick Jenkins now that integration tests might be able to pass.

**Comment by lukecwik** [comment]
LGTM

**Comment by kennknowles** [comment]
I'll follow up with a `git diff --stat` on `util` before and after #1083, which should be a noop. I had previously neglected that directory.

**Pull request merged**
