### PR TITLE
Fix warnings that came with newly released Pylint (1.6.1) version

### PR DESCRIPTION
**Pull request by aaltay**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by aaltay** [comment]
R: @charlesccychen  Please take a look.

**Comment by charlesccychen** [comment]
Thanks!  This LGTM.

**Comment by aaltay** [comment]
R: @dhalperi Please review.

**Comment by dhalperi** [comment]
LGTM, merged.

**Comment by dhalperi** [comment]
Manually close PR at your leisure

**Comment by aaltay** [comment]
Thank you.

**Pull request closed without merging**
