### PR TITLE
[BEAM-83] Move Java 8 tests to their own module

### PR DESCRIPTION
**Pull request by kennknowles**
This allows easy setting of the compiler source and target version to 1.8 without any fragile plugin configuration. It also allows the import into Eclipse to easily set separate compliance levels, as this
is done per-Eclipse-project.

### CODE REVIEW

**Comment by davorbonaci** [comment]
R: @davorbonaci

**Comment by bjchambers** [comment]
Eclipse has a similar problem with the examples. Should we apply the same logic to them? Just not import them?

**Comment by kennknowles** [comment]
Yes, we do also need to sort out the examples. The requirements are different enough that (prior to code drop) we did not come to consensus on whether to use the approach in this PR.

Rather than attempting to bring up the issue and attain consensus on that, I propose this (hopefilly) uncontroversial bit to immediately ease developer pain. You can always omit the examples from m2e import.

**Comment by davorbonaci** [comment]
I think this approach is good, both for core SDK and examples, but I think this make even more sense after the directory reorganization. So, I'd sit on it a bit since that is coming next week. @kennknowles, does this make sense?

**Comment by kennknowles** [comment]
I think we can have some goodness now, some goodness later. It will actually probably make the directory reorg less painful to have removed the more complex maven config.

**Comment by kennknowles** [comment]
This was merged into #57, which is also merged.

**Pull request closed without merging**
