### PR TITLE
Relocate Immutability Enforcement tests

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
These tests exercise a runner behavior rather than an inherent ParDo behavior; move
to the runner that applies this enforcement.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
LGTM

**Comment by kennknowles** [comment]
Other merges have created conflicts here; please rebase.

**Comment by tgroh** [comment]
Done.

**Comment by tgroh** [comment]
Most of my travis builds are taking about 4x as long (to run the same tests), which is what's causing the redness

**Pull request merged**
