### PR TITLE
Handle empty batches in GcsIO batch methods

### PR DESCRIPTION
**Pull request by charlesccychen**

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by charlesccychen** [comment]
Thanks!  R: @robertwb for merge.

**Comment by charlesccychen** [comment]
Passing Travis: https://travis-ci.org/charlesccychen/incubator-beam/builds/182123561

**Comment by charlesccychen** [comment]
Ping?  This fixes an issue @chamikaramj discovered with write finalization failing in certain stress tests.

**Comment by robertwb** [comment]
Merged. (FYI, I look at tests before merging, so pinging for a merge after tests complete is more likely to get acted on quickly.)

**Comment by charlesccychen** [comment]
Thanks!

**Pull request closed without merging**
