### PR TITLE
[BEAM-79] sync gearpump-runner branch with master

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by manuzhang** [comment]
@kennknowles @dhalperi @jbonofre another round of sync and fix the import order as per latest changes on checkstyle.

**Comment by dhalperi** [comment]
Hi @manuzhang  -- does this fix the `@RunnableOnService` tests?

**Comment by dhalperi** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
I looked through the diff and there weren't really any functional changes. So I merged, but we need to get the tests back up!

**Comment by manuzhang** [comment]
@dhalperi how did you disable the build ? I can't run `@RunnableOnService` tests locally now.

**Comment by dhalperi** [comment]
The only thing I did was disable the Jenkins build. I didn't change your config at all.

**Comment by manuzhang** [comment]
ok, then how are we supposed to run `@RunnableOnService` tests locally now. I tried `mvn integration-test` but no tests are executed.

**Comment by dhalperi** [comment]
The command that is run is:

mvn -B -e clean verify -am -pl runners/gearpump -DforkCount=0
-DrunnableOnServicePipelineOptions='[ "--runner=TestGearpumpRunner",
"--streaming=false" ]'

You can see this by looking at the failing Gearpump runnable on service
jenkins build:
https://builds.apache.org/view/Beam/job/beam_PostCommit_RunnableOnService_GearpumpLocal/148/consoleFull

Executing Maven:  -B -f
/home/jenkins/jenkins-slave/workspace/beam_PostCommit_RunnableOnService_GearpumpLocal/pom.xml
-Dmaven.repo.local=/home/jenkins/jenkins-slave/workspace/beam_PostCommit_RunnableOnService_GearpumpLocal/.repository
-B -e clean verify -am -pl runners/gearpump -DforkCount=0
-DrunnableOnServicePipelineOptions=[ "--runner=TestGearpumpRunner",
"--streaming=false" ]

**Comment by manuzhang** [comment]
Why "--streaming=false" ? Gearpump only supports streaming mode.

**Comment by manuzhang** [comment]
The test failure is due to unpublished dependencies. I will create a PR to fix it.

**Pull request closed without merging**
