### PR TITLE
 Change maven build order to first pick up python

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
This ensures that python tests run before java, which allows for jenkins to fail fast on errors related to the change and also giving us more confidence merge changes in case of flaky java test failures.

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @robertwb @aaltay @jasonkuster @davorbonaci

**Comment by davorbonaci** [comment]
This doesn't make much sense to me. @jasonkuster is (actively) working on separating the builds, which makes this obsolete.

**Comment by vikkyrk** [comment]
This is temporary fix until we have Jason's work. Do we know when that is expected to be out? Until then, I think it is useful in not waiting for java tests to be run before we fail on python (unless I am missing something).

**Comment by davorbonaci** [comment]
Fairly soon. I don't think this is the right "fix" to change what tests run and/or in which order. We can perhaps change how we invoke Maven to get the desired effect. Overall, test execution concerns shouldn't affect module layout.

**Comment by vikkyrk** [comment]
I certainly don't disagree. I was looking for a short term fix (without having visibility into jenkins commands). But I wasn't aware of the work you guys have been "already" doing in this front. Just read your email on beam mailing list, thanks. Closing this PR.

**Pull request closed without merging**
