### PR TITLE
[BEAM-1046] - Travis tests on Python fail on Linux

### PR DESCRIPTION
**Pull request by pabloem**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by pabloem** [comment]
The problem is the `--user travis` argument that we pass to `pip`. The proper argument is only `--user`, without a username. `pip` interprets `travis` as a new package to install.

Previously, `travis` was a valid PyPi repository, so it was installed, and the script ran properly ([see here for an old successful run installing the travis package](https://travis-ci.org/apache/incubator-beam/jobs/169343346#L207)).

Here is my most recent run in [Linux](https://travis-ci.org/apache/incubator-beam/jobs/180215248#L230) and [Mac](https://travis-ci.org/apache/incubator-beam/jobs/180215247#L95). It seems that my change fixes it.

**Comment by aaltay** [comment]
@pabloem, this is great. Thank you. LGTM.

Any idea why mac was working? Is it because tox was already installed on the Travis images and that `pip install` command was not executing at all?

**Comment by pabloem** [comment]
Good question. Yes, that's it. You can see how `tox (2.3.1)` appears when we `grep` for it [before installing](https://travis-ci.org/apache/incubator-beam/jobs/180222701#L90).
I'll wait for the current tests to run and then ask a committer to merge.

**Comment by aaltay** [comment]
R: @robertwb for merging. (Jenkins failure is not related and python-sdk component passed.)

**Pull request closed without merging**
