### PR TITLE
[BEAM-162] Check for closed windows early

### PR DESCRIPTION
**Pull request by mshields822**
Rather than squash speculation on the bug I'll post this early.

Will do unit test and try to get more randomization into NexMark Q11 so we can tease out these rare failures before our customers do.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
LGTM. Waiting for tests then merging.

**Comment by mshields822** [comment]
PTAL

**Comment by mshields822** [comment]
Can we merge? Then I'll back-port to DataflowSDK.

**Comment by mshields822** [comment]
R=@bjchambers 
In case you want to cherry pick this and Repeatably trigger bug fixes.

**Comment by kennknowles** [comment]
LGTM, merging

**Comment by kennknowles** [comment]
But we do need to revisit this, semantically.

**Pull request closed without merging**
