### PR TITLE
[BEAM-155][BEAM-362] Remove TriggerBuilder backwards-compatibility adapter

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This is preparatory work to make it easier to separate trigger syntax from implementation.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @bjchambers

**Comment by bjchambers** [comment]
LGTM -- it would be helpful if there was a jira issue or something that had an outline of where this series of PRs was going, but this seems like a reasonable improvement (although the builder was added to separate the syntax, so it's unclear how removing it leads to that goal)...

**Comment by kennknowles** [comment]
To separate the syntax, we need the dependency to be the other direction. What today is `Trigger` will be moved to `runners-core`, while the syntax will remain in the SDK.

I've added also a reference to the "make runners-core a thing" Jira issue, as the drive to separate syntax from implementation is driven by that as well as the runner API.

**Comment by bjchambers** [comment]
Ah! Makes sense. Thanks for the explanation!

**Pull request merged**
