### PR TITLE
[BEAM-27] Fix exclusion of UsesTimersInParDo for FlinkRunner streaming tests

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: anyone (fixing postcommit) ping @aljoscha @mxm

### CODE REVIEW

**Comment by kennknowles** [comment]
I plan on merging this and getting LGTM later due to these special circumstances;

1. Fixes postcommit
2. The concept is LGTM and merged
3. The code is trivial and mirrors the batch configuration

**Comment by aljoscha** [comment]
+1, good call in these special circumstances.

Sorry for not spotting this in my review of the earlier PR.

**Comment by mxm** [comment]
Did we just add tests for the `UsesTimersInParDo` test group or were the existing tests failing for a while?

**Comment by kennknowles** [comment]
They were just added. It was my mistake that I excluded them from batch but not from streaming.

**Pull request merged**
