### PR TITLE
[BEAM-350] DataflowPipelineJob: Retry messages, metrics, and status polls

### PR DESCRIPTION
**Pull request by dhalperi**
At some point in the past, we decided to use a rawDataflowClient that
does not do retries when checking job status, because it was best-effort
reporting to users. The purported goal was to not clutter the log with
networking errors.

However, since that time, we have:
* Added the ability to suppress logs (emit only at DEBUG level or not at
  all) when retrying.
* Increased reliability of the job checking status so that these errors
  are less frequent and more indicative of quota or other issues.
* Started using the metrics in tests, where we do need to retry
  transient issues (BEAM-350).

So let's drop the raw transport client and just use the one that
retries.

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @lukecwik you seem to have touched this code last, but the history goes back to before either of joined the project.

**Comment by dhalperi** [comment]
R: + @kennknowles

**Comment by kennknowles** [comment]
LGTM. I can't think of a pitfall that would come from respecting the user's options. Luke?

**Comment by lukecwik** [comment]
This is very hard to review since the 500 error code impacts all Google Cloud Dataflow service calls.

As for the retry, a user did complain about Dataflow waiting ~50mins before giving any output so is this something that will occur during job submission now?

https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/301

**Comment by lukecwik** [comment]
Retry sounds better than no retry in this case since duplicate jobs should be prevented by the user and it seems like we do handle the case where the retry would have created two jobs and we dedupe using the requestId.

**Pull request closed without merging**
