### PR TITLE
Insert a shuffle before write finalization

### PR DESCRIPTION
**Pull request by charlesccychen**
Original author: @mdvorsky

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @mdvorsky

**Comment by mdvorsky** [comment]
Thanks Charles. Do you think we should do it in ViewAsIterable, so that all uses of side input can benefit from reshuffling?

**Comment by charlesccychen** [comment]
I'm a bit reluctant to do this more generally because for iterable side inputs, at least, we currently support potentially a large set of moderately sized elements.  The benefit we gain here from reshuffling is that we are able to reduce the read latency that comes from oversharding for a large collection of small elements [i.e. gcs paths] (through prefetching and skipping empty shards).  But for a large collection of moderately sized elements, perhaps it's the case that this overhead is negligible and most of the time is spent actually reading the elements.  I don't have any numbers, but I could see adding an extra shuffle step here in this case to be somewhat costly because it bottlenecks on one worker.  What do you think?

**Comment by mdvorsky** [comment]
LGTM

OK, let's just fix the finalization for now.

**Comment by charlesccychen** [comment]
Thanks!

R: @robertwb

**Comment by robertwb** [comment]
So, we still have the issue that there may be lots of empty shards, but hopefully fewer (vs. one item per shard) and perhaps someday none. 

I agree that we should just be doing this locally for now. LGTM

**Comment by cozos** [comment]
@mdvorsky @charlesccychen What is the motivation behind this change?

**Comment by robertwb** [comment]
IIRC, the problem was that using a side input with many, many shards is slow (regardless of whether they are empty or mostly empty), but the same is not true after a reshuffle.

**Comment by cozos** [comment]
Thanks for the quick reply many years after the PR was made @robertwb! 

Can you shine some light on why a side input with many shards is slow? The original comment says:

> The benefit we gain here from reshuffling is that we are able to reduce the read latency that comes from oversharding for a large collection of small elements [i.e. gcs paths](through prefetching and skipping empty shards)

I am inferring that this is on Dataflow and that before being broadcast, a side input has to be assembled from many different shards from many different machines, over the network. And a shuffle is faster because... its somehow faster than the "collect side input from shards" process. And then once the side input is nicely collected on a contiguous block of memory on the same machine, it can be broadcasted in a pipelined manner via prefetching, thus decreasing read latency on the ptransforms consuming the side inputs...

Is that what he meant? Or is it something else?

Thanks!

**Pull request merged**
