### PR TITLE
[BEAM-78] Rename com.google.cloud.dataflow to org.apache.beam

### PR DESCRIPTION
**Pull request by bjchambers**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Note that this doesn't rename *everything* possible. Follow-up work that remains includes at least:
  1. Updating `README.md`s
  2. Deploying updated testing protos to maven central, and fixing up the `ProtoCoder` tests to use them.

### CODE REVIEW

**Comment by davorbonaci** [comment]
Move files, instead of remove & add.

**Comment by bjchambers** [comment]
Done.

This required rebuilding the entire PR -- Git doesn't have a notion of "move". It detects this within each commit. Since the commit has so many files modified, it bypasses the "detect moves in files with N% changed". I had to restructure it as a commit that moves everything without changing contents (so it can detect diffs by just looking at the MD5 hashes) and then a series of commits to fix the build.

Important note: When merging, we *cannot* squash any changes into the commit that does the moves. Any modified files will not be recorded as moves.

**Comment by bjchambers** [comment]
R: @lukecwik

**Comment by bjchambers** [comment]
When merging, note that each of the fixup! commits can be squashed, but contains a description of the changes that needed to be performed (and/or scripts used) to make edits. It may be worth preserving those for historical purposes.

**Comment by davorbonaci** [comment]
A few minor comments:
* Commit: "Rename com/google/cloud/dataflow->org/apache/beam" --> has removal of empty lines at the end of the file.
* Spark has different import order. I think we could have followed the same order regardless.
* TODO: Package reorganization inside the Cloud Dataflow runner.

All this is minor and can be addressed later.

Merge in progress.

**Pull request closed without merging**
