### PR TITLE
Move Jenkins Python post commit script to the repository

### PR DESCRIPTION
**Pull request by aaltay**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This is a copy of the script Jenkins post commit Python verify job is
running (with some cosmetic changes, license and instructions.) Moving
it to the repo so that we can track changes to it.

Jenkins will be updated to call this script instead of keeping a copy
of it as part of its configuration.

### CODE REVIEW

**Comment by aaltay** [comment]
R: @dhalperi @jasonkuster

**Comment by dhalperi** [comment]
LGTM, merging.

**Comment by dhalperi** [comment]
LGTM, merged.

**Comment by dhalperi** [comment]
(please manually close at leisure)

**Pull request closed without merging**
