### PR TITLE
Integration fixes

### PR DESCRIPTION
**Pull request by dhalperi**
Resolves a testing difference between DataflowJavaSDK and Beam copies of the code that was lost in a recent code change.

### CODE REVIEW

**Comment by dhalperi** [comment]
A partial forward-port from https://github.com/GoogleCloudPlatform/DataflowJavaSDK/pull/202/files

**Comment by bjchambers** [comment]
I think at least some of the fixes have already been merged. Can you confirm that this is necessary, and if so resolve the conflicts?

**Comment by dhalperi** [comment]
@bjchambers : The fixes were not merged, but rather completely differently implemented by you and scott. This is to normalize them.

**Comment by dhalperi** [comment]
Closing because they have now been merged in as part of #126

**Pull request closed without merging**
