### PR TITLE
[BEAM-898] Fix Jenkins BigQueryTornadoes IT Failure

### PR DESCRIPTION
**Pull request by markflyhigh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

- Remove @Default annotation on getChecksum() in IT PipelineOption to avoid conflicts. It's related to [PR-1159](https://github.com/apache/incubator-beam/pull/1159)
- Remove hard code input path in WordCountIT

### CODE REVIEW

**Comment by markflyhigh** [comment]
+R: @peihe @jasonkuster

**Comment by markflyhigh** [comment]
+R: @lukecwik

**Comment by jasonkuster** [comment]
LGTM as well.

**Comment by lukecwik** [comment]
Merging

**Pull request closed without merging**
