### PR TITLE
[BEAM-523] Fixed typo in aggregator_test.py

### PR DESCRIPTION
**Pull request by shlee0605**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by aaltay** [comment]
@shlee0605 thank you for fixing this. This LGTM. Let's ask for a merge once the integrations tests pass.

**Comment by kennknowles** [comment]
The typo fix introduced a pylint error - I'll fix it up while I merge.

**Comment by aaltay** [comment]
Thank you @kennknowles. And thank you again @shlee0605.

**Comment by kennknowles** [comment]
This has been merged.

**Comment by shlee0605** [comment]
@kennknowles @aaltay thanks!

**Pull request closed without merging**
