### PR TITLE
Replace PubsubIO and injector with TextIO in StreamingWordExtract

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
Pending on https://github.com/apache/incubator-beam/pull/550

**Comment by tgroh** [comment]
I don't know if the changed example is useful anymore. Isn't this just `WordCount` that writes to BigQuery?

**Comment by peihe** [comment]
WordCount (TextIO.Write) currently doesn't work with DataflowRunner in streaming. (I haven't test other runners)
This PR is one step forward to unify streaming and batch.
Once they are truly unified, we will be able to have unified examples.

**Comment by tgroh** [comment]
No, that's what I mean; given the submission of `UnboundedReadFromBoundedSource`, can't we just run `WordCount` with `streaming = true` (and this is effectively just a duplication of that example)? This example isn't really `Streaming` anymore.

**Comment by peihe** [comment]
TextIO.Read should works for all runners in streaming, as long as they support BoundedSource and UnboundedSource.

However, TextIO.Write still doesn't work in streaming with dataflow runner. And, it might also not work with other runners.

StreamingWordExtract is still useful for users to try run a pipeline in streaming mode. Once WordCount works in streaming mode, I agree that it will not longer useful as an example. But, I still see it can be useful as an integration test for new runners implementors.

**Comment by peihe** [comment]
R: @tgroh 
R: @dhalperi

**Pull request closed without merging**
