### PR TITLE
Remove dependency on findbugs annotations artifact

### PR DESCRIPTION
**Pull request by swegner**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

The findbugs annotations artifact has an incompatible license and cannot
be included within Beam. We were previously referencing it for the
@SuppressFBWarning annotation for inline FindBugs suppression.

This change moves inline suppressions out to the existing
findbugs-filter.xml file. While not ideal as it removes the suppressions
from the offending context, it allows us to drop our dependency on the
incompatible artifact.

We are also referencing the @Nullable attribute from findbugs. This is
now source from findbugs jsr305, which does have a compatible license.

### CODE REVIEW

**Comment by swegner** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
LGTM

**Comment by dhalperi** [comment]
Is there a JIRA issue filed I can link to for this?

**Comment by swegner** [comment]
I don't believe there was. @davorbonaci, can you confirm?

**Comment by davorbonaci** [comment]
No JIRA, sorry.

**Pull request closed without merging**
