### PR TITLE
[BEAM-651]: Consider making TypedPValue.setTypeDescriptorInternal no longer Internal

### PR DESCRIPTION
**Pull request by nssalian**
On the PR: Refactored the project to modify the name of setTypeDescriptorInternal to setTypeDescriptor.
Ran a mvn clean install to SUCCESS and a local TRAVIS build went through as well.

@kennknowles , do you have some to help review?
My previous PR had some additional conflicts.
Thank you.

### CODE REVIEW

**Comment by nssalian** [comment]
Not sure why this conflict occurs. Seems to be running and building fine. Not sure what I am missing.

**Comment by kennknowles** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
On your branch, can you run `git rebase origin/master`? After this, you'll need to `git push -f nssalian BEAM-651-new` (assuming you have your fork set up to be called `nssalian`)

**Comment by nssalian** [comment]
My branch seems to have a lot of issues. Let me clean things up and post this fresh in another PR. Thanks @kennknowles

**Pull request closed without merging**
