### PR TITLE
[BEAM-755] SplittableParDoTest does not require RunnableOnService

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @lukecwik 
CC: @jkff @tgroh

### CODE REVIEW

**Comment by dhalperi** [comment]
```
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ beam-runners-core-java ---
[INFO] Starting audit...
[ERROR] /home/jenkins/jenkins-slave/workspace/beam_PreCommit_MavenVerify/runners/core-java/src/test/java/org/apache/beam/runners/core/SplittableParDoTest.java:37:8: Unused import: org.apache.beam.sdk.testing.NeedsRunner. [UnusedImports]
[ERROR] /home/jenkins/jenkins-slave/workspace/beam_PreCommit_MavenVerify/runners/core-java/src/test/java/org/apache/beam/runners/core/SplittableParDoTest.java:56:8: Unused import: org.junit.experimental.categories.Category. [UnusedImports]
Audit done.
[INFO] There are 2 errors reported by Checkstyle 6.19 with beam/checkstyle.xml ruleset.
[ERROR] src/test/java/org/apache/beam/runners/core/SplittableParDoTest.java:[37,8] (imports) UnusedImports: Unused import: org.apache.beam.sdk.testing.NeedsRunner.
[ERROR] src/test/java/org/apache/beam/runners/core/SplittableParDoTest.java:[56,8] (imports) UnusedImports: Unused import: org.junit.experimental.categories.Category.
```

**Comment by jkff** [comment]
I think you forgot to add `@NeedsRunner`.

**Comment by tgroh** [comment]
There's no call to `p.run()`, so it doesn't need a `NeedsRunner` annotation; `CrashingRunner` should be sufficient.

**Comment by kennknowles** [comment]
@dhalperi I do actually appreciate pulling errors out of a log - saves a couple clicks and rather slow page loads. But even better, if checkstyle is your only remaining concern, perhaps a comment like "LGTM once you fix checkstyle / once Jenkins is green [and @tgroh or @jkff LGTM]". Then I can go ahead and merge after doing trivial stuff.

**Comment by kennknowles** [comment]
Failures are now the same that are affecting every PR.

**Comment by dhalperi** [comment]
(Also LGTM)

**Comment by dhalperi** [comment]
And merged.

**Pull request closed without merging**
