### PR TITLE
[BEAM-7] Initial Dataflow code drop

### PR DESCRIPTION
**Pull request by francesperry**
Initial contribution of the [Google Cloud Dataflow Java SDK](https://github.com/GoogleCloudPlatform/DataflowJavaSDK) to Apache Beam. 

Caveat: There is still a lot to do before this becomes usable as Apache Beam. In particular:
* Reorganize directories.
* Incorporate additional drops by Google, Cloudera, and dataArtisans.
* Make major backwards incompatible API changes.
* Rename from Dataflow to Beam.

Beaming with joy ;-D

### CODE REVIEW

**Comment by evilsoapbox** [comment]
I am assigning this to me but I do not have permissions. Once assigned to me, I will review and merge if it passes review.

**Comment by imsky** [comment]
whoa

**Comment by lukecwik** [comment]
Was that a whoa :-) or whoa :-( ?

**Comment by imsky** [comment]
whoa :)

**Pull request merged**
