### PR TITLE
[BEAM-1049] Update spark version to 1.6.3

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
LGTM pending tests.

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by amitsela** [comment]
Spark tests _look_ like the common flake in streaming tests.. but the Apex one is weird...

**Comment by iemejia** [comment]
Just rebased after my last PR was merged to run the tests again

**Comment by amitsela** [comment]
Thanks! I'll merge once tests pass.

**Comment by jbonofre** [comment]
Thanks, Amit or I will merge once tests will be OK.

**Comment by amitsela** [comment]
np, thanks!

**Comment by jbonofre** [comment]
Tests are OK. I'm merging thanks.

**Pull request merged**
