### PR TITLE
[BEAM-390] Update spark runner to use spark version 1.6.2

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by iemejia** [comment]
@amitsela This is a really simple one, does it look ok to you ? So we can merge ?

**Comment by amitsela** [comment]
+1. If anyone wants to merge, feel free. 
 I'm not available in the next 12 hours.

**Comment by jbonofre** [comment]
LGTM

I gonna merge it.

**Pull request closed without merging**
