### PR TITLE
[BEAM-85] Manually fix some broken uses of DataflowAssert

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @tgroh

**Comment by tgroh** [comment]
LGTM

**Comment by dhalperi** [comment]
Okay, BEAM-85 really is the issue I was thinking of. Geeze.

**Comment by davorbonaci** [comment]
LGTM.

**Comment by dhalperi** [comment]
rebased and repushed to trigger jenkins rerun

**Comment by kennknowles** [comment]
It's an LGTM party!

**Pull request merged**
