### PR TITLE
[BEAM-703] SingletonViewFn might exhaust defaultValue if it's serialized after being used.

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
R: @kennknowles or any other committer who knows the SDK well.

**Comment by kennknowles** [comment]
LGTM

**Comment by kennknowles** [comment]
This change may ~double the memory consumption due to singleton side inputs with defaults that are accessed. Since that is proportional to the number of empty windows accessed, I wouldn't expect it to be relevant. And anyhow, it is actually incorrect prior to your change. If it becomes a problem, we'll have to think of other ways to address it.

**Comment by amitsela** [comment]
I agree. Thanks for merging!

**Pull request merged**
