### PR TITLE
[BEAM-550] DatastoreIO Write PTranform for Bounded/Unbounded PCollections

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

- Implement Datastore Write as a composite transform of ParDo without using the Sink API
- Generalize the transform for handling idempotent Datastore Mutations. This allows for a Delete transform for deleting entities. 
- Add an example that deletes entities from Datastore.

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @dhalperi : This PR has both Sink as ParDo and the support for Mutations. Making them a separate PR would mean two refactors, so went in favor of just one PR.

**Comment by vikkyrk** [comment]
But let me know if you prefer to review it as two separate ones, I will fix it.

**Comment by dhalperi** [comment]
There are three separate things; these should get factored out three ways.

1. Sink
2. Mutations
3. Example deleting.

Probably easiest to review in that order. Not sure we'll want to merge 3 into here vs posting it elsewhere.

**Comment by vikkyrk** [comment]
@dhalperi sounds good. Sent another PR for Sink, https://github.com/apache/incubator-beam/pull/833. 
Will be able to work on the other two once that is merged. Closing this PR.

**Pull request closed without merging**
