### PR TITLE
[BEAM-115] Rename GroupByKeyEvaluator to GroupByKeyOnlyEvaluator, etc

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Just getting this rename in place ahead of actually switching up the in-process runner to treating GABW also as a primitive with an evaluator.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @tgroh who wrote the code
R: @bjchambers who is a committer

**Comment by kennknowles** [comment]
I made this change but it ended up in a larger commit for which git failed to deduce the file moves. So I've pulled it out and figured it can go in whenever.

**Comment by tgroh** [comment]
LGTM

**Comment by kennknowles** [comment]
Going to incorporate this into a slightly larger change.

**Pull request closed without merging**
