### PR TITLE
[Beam-353] Correct the licenses

### PR DESCRIPTION
**Pull request by aaltay**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by aaltay** [comment]
Hi @silviulica, @jasonkuster could you please take a look?

**Comment by silviulica** [comment]
LGTM - Thanks very much Ahmet for cleaning this up!

**Comment by aaltay** [comment]
Hi @dhalperi, could you please take a look?

**Comment by dhalperi** [comment]
LGTM -  thanks @aaltay . Merging now

**Comment by aaltay** [comment]
Thank you Dan. Closing.

**Pull request closed without merging**
