### PR TITLE
[BEAM-234] Remove Pipeline from TestDataflowPipelineRunner

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
LGTM, will merge once green.

**Comment by dhalperi** [comment]
[it may fail because of jenkins WordCountIT. if so, will fix config and then merge anyway]

**Comment by tgroh** [comment]
Jenkins looks to be UNSTABLE

**Comment by dhalperi** [comment]
NB: merged, but had to update the Jenkins config with the new name change from `TestDataflowPipelineRunner` to `TestDataflowRunner`

**Pull request closed without merging**
