### PR TITLE
[BEAM-1006] Fixing the splitKeysToFilters methofd as calling toString on the Document prefixed …"Document"

### PR DESCRIPTION
**Pull request by david-billings**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

…Document to the string, updated it to just get the value of ID. Also fixed a typo

### CODE REVIEW

**Comment by dhalperi** [comment]
Hi David,

Thanks for this fix. Sorry no one has addressed it yet; we've been traveling a lot recently.

If you are willing to do so, would you consider adding a unit test of the affected function?

(If not, this bug fix looks clearly LGTM, and I will merge after figuring out why the precommit build failed. Alternately, you could rebase on `master` and force-push, which will also kick off another Jenkins build.)

Thanks,
Dan

CC: @jbonofre

**Comment by dhalperi** [comment]
R: @dhalperi

**Comment by jbonofre** [comment]
Oh, sorry, I've missed this PR.

**Comment by jbonofre** [comment]
I will make a new build locally (with a rebase). I'm also triggering a new build on Jenkins.

**Pull request closed without merging**
