### PR TITLE
Fixing postcomit error caused by PR 1526.

### PR DESCRIPTION
**Pull request by pabloem**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by pabloem** [comment]
r:aaltay

**Comment by aaltay** [comment]
Thank you. LGTM.

**Comment by markflyhigh** [comment]
Turn out that it's necessary to have service tests in Precommit to catch such problems. Either a subset of VR tests, or E2E test, or both.

**Comment by pabloem** [comment]
It's also possible to update the `run_postcomit.sh` file to take in a project and a gcs location, so that other developers can run a (perhaps shortened) version of the postcomit tests?

@robertwb can you merge this please?

**Pull request closed without merging**
