### PR TITLE
Python sdk merge from master

### PR DESCRIPTION
**Pull request by aaltay**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Merge master branch into python-sdk branch. We will do this on a regular basis going forward to keep python-sdk development branch in sync with the master. 

Merging changes since 6/9/2016 and there were no merge conflicts.

### CODE REVIEW

**Comment by aaltay** [comment]
@silviulica, @dhalperi Could you please take a look?

**Comment by silviulica** [comment]
LGTM but please can you make a more clear comment for the PR?
We need to do this periodically until the Python SDK development will move to the master branch.

**Comment by aaltay** [comment]
Thank you Silviu, update the PR comment in a more descriptive way.

**Comment by davorbonaci** [comment]
Actually, I was wrong before -- GitHub will automatically close PRs going into the default branch only, not into feature branches. So, you'd have to click the close button yourself for a little bit.

**Comment by aaltay** [comment]
Closing then. Thanks for pushing.

**Pull request closed without merging**
