### PR TITLE
Add GitHub pull request template

### PR DESCRIPTION
**Pull request by kennknowles**
The contribution guide is still receiving comment, so this is subject to revision. But I think we can get one in place that is somewhat useful immediately. And I am eager to try out this rather fun feature :-)

### CODE REVIEW

**Comment by jbonofre** [comment]
LGTM

**Comment by kennknowles** [comment]
Thanks for suggesting this, @iemejia.

R: @davorbonaci, @jbonofre

**Comment by davorbonaci** [comment]
LGTM; will merge today.

**Comment by kennknowles** [comment]
I went ahead and merged from the LGTM(s), and I assume it will receive polish over time.

**Pull request merged**
