### PR TITLE
BEAM-783 Add test to cover side inputs and outputs.

### PR DESCRIPTION
**Pull request by tweise**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
R: @kennknowles

### CODE REVIEW

**Comment by kennknowles** [comment]
This seems like something that `RunnableOnService` tests should have caught. If not, then your new test seems like it can definitely be runner independent.

What am I missing?

**Comment by tweise** [comment]
This test will likely be expanded to cover Apex runner specific things and I added it actually to investigate the issue with View.AsSingleton 

Discovery of the bug with side outputs was a side effect :-) The problem was that nothing was emitted with the main output tag, which the integration test did not catch: 

https://github.com/apache/incubator-beam/blob/apex-runner/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoTest.java#L710

```
    PAssert.that(outputs.get(mainOutputTag))
        .satisfies(ParDoTest.HasExpectedOutput
                   .forInput(inputs)
                   .andSideInputs(11, 222));
```

**Comment by tweise** [comment]
@kennknowles it looks like since the assertion was never executed with the main output it also could not fail.

**Comment by tweise** [comment]
Confirmed, since the PAssert didn't execute, the test passes. The modified test for Apex runner checks the actual results and fails (but also assumes embedded execution). Maybe it would be good to assert that PAsserts actually run? Please let me know if you need anything else to be done for this PR.

**Comment by kennknowles** [comment]
Ah, yes. This has bit every runner so far, when it is first written :-)

This should really be owned by `TestPipeline` or something around there, but it seems each runner needs to do it for now: You can see in `TestDataflowRunner`:

There is some counting of how many asserts should run: https://github.com/apache/incubator-beam/blob/master/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/testing/TestDataflowRunner.java#L181

And there is some checking that they all ran: https://github.com/apache/incubator-beam/blob/master/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/testing/TestDataflowRunner.java#L188

**Comment by tweise** [comment]
@kennknowles yep, for this metrics need to be supported. I would also like to use that to finish tests faster when all PAsserts were met, instead of waiting for the embedded cluster to shut down by itself.

Do you see anything else that needs to be done for this PR or can it be merged?

**Comment by kennknowles** [comment]
Yes, this LGTM. It is a step in the right direction. I am surprised that aggregators are not covered by `RunnableOnService` tests. But it is just as well, since I think the new metrics should totally replace them.

**Pull request merged**
