### PR TITLE
Update badge for new suite name.

### PR DESCRIPTION
**Pull request by jasonkuster**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @davorbonaci

### CODE REVIEW

**Comment by davorbonaci** [comment]
LGTM. Merging.

Please follow up for the test failure:
```
Failed tests: 
  ParDoBoundTranslatorTest.testAssertionFailure:175->runExpectingAssertionFailure:160 assertion should have failed
```

**Comment by davorbonaci** [comment]
(The flake is BEAM-1067.)

**Comment by jasonkuster** [comment]
@davorbonaci It looks like that ticket is for wordcounttest and this break is in the pardoboundtranslatortest. Are they the same root cause?

**Comment by davorbonaci** [comment]
Perhaps (but somebody already mentioned this type of break, so it can be tracked by the same issue).

**Pull request merged**
