### PR TITLE
Update Spark Test to use more standard Pipeline Running

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Ensures that the Pipeline uses the appropriate runner while constructing the graph.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @amitsela

**Comment by amitsela** [comment]
+1

**Comment by tgroh** [comment]
Beamified.

**Comment by tgroh** [comment]
Replaced by #182

**Comment by tgroh** [comment]
#182 merged, so this is no longer required.

**Pull request closed without merging**
