### PR TITLE
Update 404 link to setuptools docs

### PR DESCRIPTION
**Pull request by swegner**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by swegner** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM.

Thanks.

**Comment by swegner** [comment]
@chamikaramj who can help get this merged? I see @francesperry is the [sdk-py "component lead"](https://issues.apache.org/jira/browse/BEAM/component/12328910/?selectedTab=com.atlassian.jira.jira-projects-plugin:component-summary-panel) in JIRA.

**Comment by chamikaramj** [comment]
Please add one of the committers as a reviewer to get this merged.

**Comment by swegner** [comment]
R: @dhalperi

**Pull request closed without merging**
