### PR TITLE
[BEAM-595] avoid throwing Exception in waitUntilFinish in SparkRunner streaming mode

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @amitsela

**Comment by amitsela** [comment]
This seems fine, keep in mind though that for streaming pipelines the SparkRunner uses [`StreamingEvaluationContext`](https://github.com/amitsela/incubator-beam/blob/master/runners/spark/src/main/java/org/apache/beam/runners/spark/translation/streaming/StreamingEvaluationContext.java) which currently doesn't support the new API at all.
For batch, your change definitely LGTM, but there is a WIP on this now so I wouldn't want to go beyond that.

**Comment by peihe** [comment]
Update the PR to keep throw in streaming mode
R: @kennknowles

**Comment by peihe** [comment]
@amitsela 
PTAL

**Comment by amitsela** [comment]
LGTM, could you ask a(nother) committer to merge this ? If this will still be open in ~10 hours from now I'll do it, thanks!

Oh, one comment - maybe state in the JIRA ticket name (and PR title) that it's for batch, as streaming will still throw.

**Comment by peihe** [comment]
Done update PR title
Updated to jira to "Support non-blocking run() in SparkRunner and cancel() and waitUntilFinish() in Spark EvaluationContext"

@kennknowles could you help to merge this?

**Pull request merged**
