### PR TITLE
[BEAM-808] Increase "spark.port.maxRetries" to avoid BindException in…

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
- [x] Make sure the PR title is formatted like:
  `[BEAM-<Jira issue #>] Description of pull request`
- [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
     Travis-CI on your fork and ensure the whole test matrix passes).
- [x] Replace `<Jira issue #>` in the title with the actual Jira issue
     number, if there is one.
- [x] If this contribution is large, please file an Apache
     [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
---

… ROS.

### CODE REVIEW

**Comment by amitsela** [comment]
R: @dhalperi.
It's best to test this PR branch by letting Jenkins run ROS on it.

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Updated the configuration and trigger a new build:

https://builds.apache.org/job/beam_PreCommit_MavenVerify/4567/

**Comment by jbonofre** [comment]
It worked. So: LGTM

**Comment by jbonofre** [comment]
By the way, I reverted the change. Should I update https://builds.apache.org/view/Beam/job/beam_PostCommit_RunnableOnService_SparkLocal/ ?

**Comment by amitsela** [comment]
Let's try to initiate this ROS build manually once after the merge, and assuming it works (should be similar to what we've just tested successfully) we can enable it tow run on PostCommit automatically.

**Comment by jbonofre** [comment]
It makes sense.

**Comment by dhalperi** [comment]
JB: you didn't run ROS, you ran the precommit tests manually. This is not what is broken, not what we're trying to fix :). This change did not actually fix the build, so should not have been merged. https://builds.apache.org/view/Beam/job/beam_PostCommit_RunnableOnService_SparkLocal/32/testReport/

**Comment by jbonofre** [comment]
I changed the Jenkins build with the profiles and add the integration-test goal. Do I have other change to do ?

By the way guys, I added you both as Jenkins job admin.

**Comment by amitsela** [comment]
Thanks JB Dan helped me to try a couple of more things but no luck..

**Pull request closed without merging**
