### PR TITLE
Import Spark Runner code

### PR DESCRIPTION
**Pull request by tomwhite**
This addresses https://issues.apache.org/jira/browse/BEAM-6.

I've preserved git history (using @mxm's amazing git rewriting trick from #12). This is just an initial import - the Spark runner build is not yet integrated with the main build, packages need changing, etc. That's going to take more work, so it might be a good idea to get this merged first.

### CODE REVIEW

**Comment by davorbonaci** [comment]
R: @davorbonaci

I'll take a quick peek.

**Comment by amitsela** [comment]
@davorbonaci feel free to merge this. I'll take care of integrating per https://issues.apache.org/jira/browse/BEAM-11

**Comment by davorbonaci** [comment]
Nice!

I'd probably get rid of LICENCE and CONTRIBUTING.md right away, and prefix the pull request with `[BEAM-6] Import...`.

I can merge this right away -- no issues there. Just to confirm -- both of you should have commit/write access to the project. Is that not the case?

**Comment by davorbonaci** [comment]
Awesome. Thanks @amitsela and @tomwhite.

**Comment by mxm** [comment]
Glad the snippet could help you out @tomwhite. Nice to see this going in!

**Pull request merged**
