### PR TITLE
Allow ".tar" files in extra_packages

### PR DESCRIPTION
**Pull request by charlesccychen**
This change allows uncompressed ".tar" package tarballs to be staged and installed on worker startup.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @silviulica

**Comment by charlesccychen** [comment]
@aaltay: do you have any insight into why the Travis check fails?  Thanks!

**Comment by silviulica** [comment]
LGTM - we should eventually allow everything that you can run pip install on (e.g., zip files too)

**Comment by aaltay** [comment]
@charlesccychen Pylint released a new version (1.6.1) to PyPi recently. It adds a new warning for extra new lines at the end of the files. It is warning about a total of 3 places including this one. I will fix them. This one you can remove the extra line at the end of the dependecy.py file. (FYI: https://pylint.readthedocs.io/en/latest/whatsnew/changelog.html#what-s-new-in-pylint-1-6-1)

**Comment by charlesccychen** [comment]
@aaltay: Thanks!  Fixed.

**Comment by charlesccychen** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
LGTM, merged, manual close please

**Pull request closed without merging**
