### PR TITLE
[BEAM-1147] Do not test pickling native sink objects

### PR DESCRIPTION
**Pull request by aaltay**

### CODE REVIEW

**Comment by aaltay** [comment]
R: @charlesccychen @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by aaltay** [comment]
R: @robertwb

**Comment by robertwb** [comment]
Motivation? JIRA issue?

**Comment by aaltay** [comment]
Thank you @robertwb. Added a JIRA issue.

Motivation is: BQ tests are failing on DirectPipelineRunner due to testing of pickling/unpickling.

**Comment by chamikaramj** [comment]
We should not be picking unpickling native sink objects since they might contain unpicklable data (proto objects in this case). For example dataflow runner builds a JSON step discriptions out of information available in native sink objects instead of pickling them. Custom sink objects on the other hand should be picklable.

**Comment by robertwb** [comment]
Sounds good. Merging.

**Pull request merged**
