### PR TITLE
[BEAM-443] Update Beam batch examples to call waitUntilFinish()

### PR DESCRIPTION
**Pull request by peihe**
This PR adds waitUntilFinish() to batch examples and RunnableOnService tests.

### CODE REVIEW

**Comment by peihe** [comment]
R: @dhalperi @davorbonaci

**Comment by dhalperi** [comment]
PR does not compile.

**Comment by peihe** [comment]
Jenkins and soem travis passed
PTAL

**Comment by peihe** [comment]
blocked on https://github.com/apache/incubator-beam/pull/1160
I will ping this thread once that PR is merged.

**Comment by dhalperi** [comment]
This LGTM, 1160 does not. Any reason to hold?

**Comment by peihe** [comment]
#1160 is merged
removed the added exceptions.

maven clean verify passed locally

wait for presubmit, then ready to review.

**Comment by davorbonaci** [comment]
LGTM

**Comment by peihe** [comment]
4 out of 5 travis passed
should be ready to merge

**Pull request merged**
