### PR TITLE
[BEAM-944] Spark runner causes an exception when creating pipeline op…

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

…tions.

Create a SparkContextOptions for context-ware options.

### CODE REVIEW

**Comment by amitsela** [comment]
This PR creates a separate `SparkContextOptions` that inherits `SparkPipelineOptions` and handles `ProvidedSparkContext` and `Listeners`.
This new `SparkContextOptions` is NOT registered via `SparkRunnerRegistrar` to avoid the issues mentioned in [BEAM-944](https://issues.apache.org/jira/browse/BEAM-944).

**Comment by davorbonaci** [comment]
Yup -- I believe this would solve the issue mentioned in BEAM-944. LGTM.

CC: @francesperry

**Comment by amitsela** [comment]
Once tests pass..
R: @davorbonaci or @kennknowles 
CC: @amarouni

**Comment by kennknowles** [comment]
LGTM and Jenkins is happy.

**Comment by amarouni** [comment]
LGTM, but the boolean `UsesProvidedSparkContext` doesn't link directly to Spark dependencies and moving it means that we can no longer create a `PipelineOptions` with `UsesProvidedSparkContext` using command-line arguments which can be very useful sometimes.

**Comment by amitsela** [comment]
@amarouni that's interesting.. I thought that it should reside next to the `UsesProvidedSparkContext `..
I assumed that if you programmatically set the context, you set the flag. 
What am I missing ?

**Comment by amarouni** [comment]
@amitsela That's what we should have done (setting the flag if the context was set programmatically), but unfortunately I didn't think about it at the time. And from what we saw, concerning the `ProvidedSparkContext`, people tend to create a SparkPipelineOptions using command-line arguments with `UsesProvidedSparkContext` set to `true` and then inject the SparkContext using `SetProvidedSparkContext` programmatically at the last moment.

We can totally look at setting `UsesProvidedSparkContext` to true once the `SetProvidedSparkContext` is used.

**Comment by amitsela** [comment]
The way I see it, we have two ways to solve this:

1. Remove the `UsesProvidedSparkContext` option, and have it implicitly "set" by  checking `ProvidedSparkContext != null`.
2. Moving `UsesProvidedSparkContext` to `SparkPipelineOptions`, and letting users provide command-line flag (for example) to toggle a driver code that will set (and start!) a provided context.

I guess (2) is reasonable.

Thoughts ?

**Comment by amarouni** [comment]
2 LGTM

**Comment by amitsela** [comment]
Moved `UsesProvidedSparkContext ` and rebased on master.

@davorbonaci I still want to reproduce the issue on master to make sure this solves the problem (please see JIRA ticket), although it looks like this changed is welcomed anyway.
CC: @amarouni

**Comment by davorbonaci** [comment]
LGTM -- this change is good anyway. I'd suggest to proceed, once tests pass.

**Comment by amitsela** [comment]
Test failures are unrelated, and looks like this solution benefits all, I'll merge.

**Pull request closed without merging**
