### PR TITLE
Display data: minor cleanups

### PR DESCRIPTION
**Pull request by dhalperi**
* wrong @Nullable
* Remove unused function

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @swegner

**Comment by swegner** [comment]
Thanks for doing this cleanup. Can you add `org.apache.avro.reflect.Nullable` to the [Checkstyle IllegalImport](https://github.com/apache/incubator-beam/blob/master/sdks/java/build-tools/src/main/resources/beam/checkstyle.xml#L110) list?

**Comment by dhalperi** [comment]
Avro's `@Nullable` is valuable part of describing objects with `@DefaultCoder(AvroCoder.class)`. Have to live with this one.

E.g.: 

https://github.com/apache/incubator-beam/blob/b5e15c23a97a36b6e159610ad6ea7cd92a6c8c3e/examples/java8/src/main/java/org/apache/beam/examples/complete/game/UserScore.java#L81

**Comment by swegner** [comment]
Bummer.  A quick search over Beam shows it's also being misused in `ApproximatelyUnique`-- want to replace that usage as well?

LGTM

**Pull request closed without merging**
