### PR TITLE
[BEAM-1010] A few improvements to Apache Beam Python's FileIO.

### PR DESCRIPTION
**Pull request by katsiapis**
- Ensuring that AUTO compression works properly for FileSinks.
- Introducing __enter__ and __exit__ in _CompressedFile to allow use
  of "with", and updating textio accordingly.

### CODE REVIEW

**Comment by katsiapis** [comment]
R: @chamikaramj 

Hey Chamikara can you take a look?

**Comment by katsiapis** [comment]
Errors seem unrelated to this PR (they seem related to Java).

@robertwb would you be able to Merge in after @chamikaramj 's LGTM?

**Comment by chamikaramj** [comment]
LGTM

**Comment by katsiapis** [comment]
Hey @lukecwik since @robertwb is not available, could you Merge this and let me know when I can close?

**Comment by lukecwik** [comment]
When attempting to build your branch (mvn clean verify -pl sdks/python -am), I get the following failure from this merge (note it doesn't happen in head python-sdk branch):

======================================================================
FAIL: test_model_multiple_pcollections_partition (apache_beam.examples.snippets.snippets_test.SnippetsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/lcwik/git/incubator-beam/sdks/python/apache_beam/examples/snippets/snippets_test.py", line 549, in test_model_multiple_pcollections_partition
    self.get_output(result_path))
AssertionError: Lists differ: ['0', '17', '32', '42', '53', ... != []

First list contains 8 additional elements.
First extra element 0:
0

- ['0', '17', '32', '42', '53', '64', '89', '99']
+ []
-------------------- >> begin captured logging << --------------------
root: INFO: Missing pipeline option (runner). Executing pipeline using the default runner: DirectPipelineRunner.
root: INFO: Running pipeline with DirectPipelineRunner.
--------------------- >> end captured logging << ---------------------

**Comment by lukecwik** [comment]
This is now merged in as 8e88c7b035e76c6e15d03a79f9751c6e53786859
Feel free to close

**Comment by katsiapis** [comment]
Thanks Lukasz! Closing...

**Pull request closed without merging**
