### PR TITLE
Update surefire plugin to 2.19.1

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

I noticed that we were using a very old version of surefire. The latest version is still 6 months old, so nothing like bleeding edge. It adds simple things like excluding tests by fully qualified class name, which is nicer than file path patterns.

### CODE REVIEW

**Comment by lukecwik** [comment]
Update sdks/java/maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml also?

**Comment by lukecwik** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
ping?

**Comment by kennknowles** [comment]
I thought I really required this, but it turned out not to be the case. I'll update the archetype and get this in in a bit.

**Pull request closed without merging**
