### PR TITLE
[BEAM-721] Testing tox intermittent failures on Mac

### PR DESCRIPTION
**Pull request by pabloem**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ x ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ x ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ x ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by pabloem** [comment]
@aaltay I added the checks: If `tox` is installed, then update TOX_HOME to the right place. Otherwise, install it. The fix has run fine three times already:

* https://travis-ci.org/apache/incubator-beam/builds/165958424
* https://travis-ci.org/apache/incubator-beam/builds/165960898
* https://travis-ci.org/apache/incubator-beam/builds/165961980

**Comment by aaltay** [comment]
All the linked runs, ran with the image that has tox preinstalled. Do you have successful run with other images?

**Comment by pabloem** [comment]
Not at the moment. I'll trigger a few runs by closing/opening the PR. To be fair, though, all the Python runs that I found from the last two days have come with `tox` preinstalled:

* https://travis-ci.org/apache/incubator-beam/jobs/165945731
* https://travis-ci.org/apache/incubator-beam/jobs/165929142
* https://travis-ci.org/apache/incubator-beam/jobs/165963568
* https://travis-ci.org/apache/incubator-beam/builds/165665252
* https://travis-ci.org/apache/incubator-beam/jobs/165401745
* https://travis-ci.org/apache/incubator-beam/jobs/165389942

**Comment by aaltay** [comment]
Maybe there was a rolling change to Travis. If there will be a single image with tox installed, then we do not need the branch to check whether it is installed or not.

Either way, let's wait for your test runs to complete.

**Comment by pabloem** [comment]
I filed an [issue to Travis](https://github.com/travis-ci/travis-ci/issues/6696) to find out if that's the case.

**Comment by pabloem** [comment]
According to the Travis people: They don't officially support Python, but they've pushed a new Mac image on 10/04 that might have changed the behavior.

If they don't support Python, it's feasible that they'll push an image that will again not come with Tox - so it might be fine to leave the code as is in this PR. What do you think?

**Comment by aaltay** [comment]
LGTM.

According to the Travis [blog post](https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/) they will maintain multiple images at least until the end of October and maybe longer. So, it makes sense to keep this code as it is.

**Comment by pabloem** [comment]
@robertwb can you review and commit if appropriate? : ) - received LGTM from aaltay.

**Comment by robertwb** [comment]
Thanks for doing this. I think this is good. I'll merge.

**Pull request closed without merging**
