### PR TITLE
Allow custom timestamp/watermark function for UnboundedFlinkSource

### PR DESCRIPTION
**Pull request by Lusitanian**
So, using an `UnboundedFlinkSource` seems to force the timestamp applied to each element of the incoming stream to the ingestion time, rather than allowing for proper event timestamping. This PR  adds the ability to created an `UnboundedFlinkSource` with a custom TimestampAssigner, which should alleviate that issue. Note that this is particularly useful, as currently the only means of consuming from Kafka 0.8 using Beam/Flink Runner is to wrap Flink's Kafka 0.8 consumer.

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @mxm  @aljoscha

**Comment by aljoscha** [comment]
LGTM! If no one objects I'll merge it later today.

**Comment by Lusitanian** [comment]
@aljoscha awesome, thanks :)

**Comment by mxm** [comment]
Thanks!

**Pull request closed without merging**
