### PR TITLE
[BEAM-22] Explicitly use a ConcurrentLinkedQueue in UnboundedReadEvaluatorFactory

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

The evaluator may be reused in a different thread, and updates to the
checkpoint must be visible.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Can you say more about why? Is there a test that can add?

**Comment by tgroh** [comment]
Updated the description; changed what's actually being implemented.

There must be a visibility restriction between uses of the evaluators - as an evaluator may be used by different threads, any update to the state of that evaluator must be visible between uses. [ConcurrentLinkedQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html) provides a happens-before relationship between offering an element to the queue and polling it from that queue.

As we offer the evaluator to the queue after completing any updates to the evaluator state, this ensures that reads to the value of CheckpointMark are consistent with the writes to that value.

**Comment by dhalperi** [comment]
LGTM

**Pull request closed without merging**
