### PR TITLE
Support BigQuery BYTES type

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
LGTM

**Comment by dhalperi** [comment]
Pending changes to swap away from `byte[]` as the default decoding because TableRowJsonCoder objects are terrible.

**Comment by peihe** [comment]
Updated to return base64 encoded string from BigQuery.
This will be consistent with TableRowJsonCoder.

**Comment by dhalperi** [comment]
LGTM, and jenkins has passed.

**Pull request closed without merging**
