### PR TITLE
Wait for Elements to be fetched in KafkaIO#start

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This makes it significantly more likely that the reader has elements after
the call to returns.

### CODE REVIEW

**Comment by tgroh** [comment]
@eljefe6a This might fix your issue with reading from Kafka with the InProcessRunner

**Comment by tgroh** [comment]
R: @rangadi @dhalperi

**Comment by rangadi** [comment]
+1
As this might still result in cases where start() might still return false (in some case in every attempt). Please comment if that is ok.

**Comment by tgroh** [comment]
Added.

**Comment by tgroh** [comment]
ping @dhalperi

**Comment by dhalperi** [comment]
LGTM

**Pull request closed without merging**
