### PR TITLE
Add BigQueryTornadoes integration test with a BigQuery.Read fix.

### PR DESCRIPTION
**Pull request by peihe**
This PR fixed the project picking in BigQuery.Read.
The fixed is verified with BigQueryTornadoes tests.

### CODE REVIEW

**Comment by peihe** [comment]
R: @davorbonaci

**Comment by peihe** [comment]
R: @dhalperi for commit "define executingProject, and use it for creating BigQuery jobs"

**Comment by davorbonaci** [comment]
R: @jasonkuster for the usage of e2e framework.

**Comment by jasonkuster** [comment]
LGTM. Thanks for expanding E2E coverage Pei!

**Comment by peihe** [comment]
BigQueryTornadoes passed in Jenkins, but the build was timed out.

triggered the tests to rerun

**Comment by peihe** [comment]
@dhalperi 
Could you take a look at the BigQuery.Read fix?
If that looks good, I will send the backport RP in dataflow.

**Comment by dhalperi** [comment]
LGTM

**Comment by dhalperi** [comment]
In followup, let's improve the unit tests to exercise and verify the projects.

**Pull request closed without merging**
