### PR TITLE
Make SerializableMatchers Public Used for E2E test

### PR DESCRIPTION
**Pull request by markflyhigh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
- [ ] Make sure the PR title is formatted like:
  `[BEAM-<Jira issue #>] Description of pull request`
- [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
     Travis-CI on your fork and ensure the whole test matrix passes).
- [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
     number, if there is one.
- [ ] If this contribution is large, please file an Apache
     [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
---

SerializableMatchers is useful in E2E test such as verifying multiple success conditions at the end of pipeline instead of one.

### CODE REVIEW

**Comment by markflyhigh** [comment]
+R: @jasonkuster @kennknowles

**Comment by kennknowles** [comment]
We had left `SerializableMatcher` and `SerializableMatchers` package-private to avoid diamond-dependency issues.

Since 2b63fb9 made `SerializableMatcher` public, this change has no additional negative impact. The two classes are really just a Java-ism.

LGTM based on precedent, but it is probably still worth considering what the impact on users is. Since hamcrest is already a `provided` dependency, even before 2b63fb9, the impact is on users who want to use this or anything that uses it transitively.

R: @dhalperi for this.

**Comment by jasonkuster** [comment]
LGTM from my side; defer to Dan for comments about above.

**Comment by dhalperi** [comment]
I believe we had always intended to shade Hamcrest, moving it from a `provided` dependency to a purely internal one. Internally, see #24000452 and #18837384

Now may be the time that we should do this correctly.

**Comment by kennknowles** [comment]
This PR has gotten a bit old, and we have a good number of IT tests now running. Do we still need this? If so, I think a rebase & retest is in order.

**Comment by kennknowles** [comment]
R: -@kennknowles

Feel free to re-add when ready.

**Comment by markflyhigh** [comment]
Thanks for coming back to this old PR. I think we can close it now considering current number of IT tests.

**Pull request closed without merging**
