### PR TITLE
[BEAM-1084] Update Apitools to version 0.5.6

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @chamikaramj PTAL

### CODE REVIEW

**Comment by sb2nov** [comment]
R: @chamikaramj PTAL

**Comment by sb2nov** [comment]
R: @robertwb please merge

**Comment by robertwb** [comment]
Justification?

**Comment by sb2nov** [comment]
https://github.com/google/apitools/pull/136 there was an issue where a JsonValue that was an array was only returning the last element instead of the full list. This impacts the bigquery reader in reading a repeated column with the direct runner.

**Comment by sb2nov** [comment]
https://issues.apache.org/jira/browse/BEAM-877 is blocked by this.

**Comment by robertwb** [comment]
Good. This is the kind of thing that should go in the commit message and PR description.

**Pull request closed without merging**
