### PR TITLE
Add jacoco coverage

### PR DESCRIPTION
**Pull request by swegner**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by swegner** [comment]
@kennknowles do you know much about our coveralls setup? I see we're reporting coverage from jenkins rather than travis. Coveralls [also supports travis](https://coveralls.zendesk.com/hc/en-us/articles/201347419-Coveralls-currently-supports), and from what I can tell Travis has a couple advantages:

* Infers correct pull request context to [associate with coverage data](https://coveralls.io/builds/6931744).
* Also [runs on fork repositories](https://coveralls.io/builds/6932737) since the .travis.yml config is part of source.

**Comment by kennknowles** [comment]
Our coveralls setup is in the maven config. I don't know whether PR context is inferred.

**Comment by swegner** [comment]
RE: PR context, I noticed in the [coveralls build list](https://coveralls.io/repos/101216/builds), all PR's from jenkins are listed as #99999. IIRC, this is some hack @davorbonaci needed to add to make it work. The [build for this PR from travis](https://coveralls.io/builds/6931744) has its PR number correct.

Not sure if there are other pros- and cons- of collecting from Travis vs Jenkins. @jasonkuster, do you know?

**Comment by jasonkuster** [comment]
Don't know of anything meaningful that hasn't been mentioned. From my perspective though, since Jenkins is where the bulk of our testing effort is, it would be good to keep what we can there. If you think the pros outweigh that though, feel free to push back.

**Pull request closed without merging**
