### PR TITLE
Fix NPE in UnboundedReadFromBoundedSource

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Can you say more about this change? Where was the `null` coming from and can we simply sub in empty list there?

**Comment by peihe** [comment]
The null comes from:
newCheckpoint = new Checkpoint<>(null /* residualElements */, null /* residualSource */);
And, NPE comes from:
init(newCheckpoint.residualElements, newCheckpoint.residualSource, options);

I removed replacing nulls with empty lists to init() in order to make sure I don't miss any other cases.

**Comment by dhalperi** [comment]
LGTM, merging.

**Pull request closed without merging**
