### PR TITLE
Fix errors in Flink runner javadoc

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

I think these are all the errors, though I think the javadoc tool may be configured to fail on both warnings and errors.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @mxm @aljoscha but realistically anyone is probably fine

**Comment by jbonofre** [comment]
See PR #382 (same fix).

By the way, Java8 examples javadoc has to be fixed too (working on it).

**Comment by kennknowles** [comment]
Great; I'll close this in favor of #382

**Comment by mxm** [comment]
Thanks for the doc fixes!

**Pull request closed without merging**
