### PR TITLE
[BEAM-167] Fix decompression of a concatenation of gzip streams in CompressedSource

### PR DESCRIPTION
**Pull request by lukecwik**
I pulled in the patch from kirpichov@google.com and gave him authorship of the commit.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
LGTM

**Comment by dhalperi** [comment]
rename to BEAM-167? 161 is FAQ.

**Comment by lukecwik** [comment]
Fixed BEAM-161 -> BEAM-167 in commit history by rewording commits

**Pull request closed without merging**
