### PR TITLE
[BEAM-22] Enforce non-null preconditions

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace "<Jira issue #>" in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

The InProcessPipelineRunner expects some result values to be non-null.
Enforce those early.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles 

Should go in after #147, as that has the code to fix an existing error.

**Comment by kennknowles** [comment]
LGTM. Even though it is trivial and passes on my box, might as well rebase and push it up so the test success is a matter of public record.

**Comment by tgroh** [comment]
Done.

**Comment by jbonofre** [comment]
LGTM

**Pull request closed without merging**
