### PR TITLE
Make TextFileReader observable

### PR DESCRIPTION
**Pull request by charlesccychen**
This allows future implementation of size tracking for elements in side input sources.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @silviulica

**Comment by silviulica** [comment]
LGTM

**Comment by dhalperi** [comment]
@charlesccychen  -- travis failures look real. Investigate before I merge?

**Comment by charlesccychen** [comment]
Yes. Also, please don't merge yet. This will go in after the beta. Thanks.

**Comment by robertwb** [comment]
Close at your leisure.

**Comment by charlesccychen** [comment]
Thanks.

**Pull request closed without merging**
