### PR TITLE
Add a compatibility stub of GABWViaWindowSetDoFn

### PR DESCRIPTION
**Pull request by bjchambers**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [*] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [*] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [*] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [*] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Direct calls to
`org.apache.beam.sdk.util.GroupAlsoByWindowViaWindowSetDoFn#create`
failed following the rename in 892ead2c.

This re-introduces that method as a redirect to the new name to
unbreak things while waiting for a complete fix.

### CODE REVIEW

**Comment by bjchambers** [comment]
R: @kennknowles @dhalperi @davorbonaci 
CC: @peihe @mshields822

**Comment by dhalperi** [comment]
LGTM

**Comment by kennknowles** [comment]
You mean reflective calls? Obviously direct calls would be compile-time breakage.

**Comment by kennknowles** [comment]
LGTM, but let's follow up and fix at the source.

**Pull request merged**
