### PR TITLE
[BEAM-80] Fix the Unexpected StateTag error in convertToBagTagInternal

### PR DESCRIPTION
**Pull request by peihe**
It adds asBagTag() in KeyedCombiningValueWithContextStateTag,
and allows convertToBagTagInternal accept it.

### CODE REVIEW

**Comment by peihe** [comment]
Assignee: kennknowles
(we lack permission to set it on the pull request itself)

**Comment by bjchambers** [comment]
Please add a test.

**Comment by davorbonaci** [comment]
R: @kennknowles

**Comment by peihe** [comment]
tests added, PTAL

**Pull request merged**
