### PR TITLE
Lower maven central timeouts on Travis-CI

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

I believe you showed me this configuration. I may or may not have gotten the config line right, but it seems reasonable to fail/retry fast. Exact numbers may need tuning, or it may not even help. Just something to try.

R: @dhalperi

### CODE REVIEW

**Comment by kennknowles** [comment]
Still got a timeout while downloading from Maven central :-/

Are we getting hit with temporary blacklisting or anything? Either way, caching should help.

**Comment by kennknowles** [comment]
Note that using our own settings file also works around travis-ci/travis-ci#4269, wherein containerized Travis builds have a broken `settings.xml`.

The full contents of it:

```
<settings>
  <profiles>
    <profile>
      <id>standard-with-extra-repos</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <repositories>
        <repository>
          <id>central</id>
          <name>Central Repository</name>
          <url>http://repo.maven.apache.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>

        <repository>
          <id>sonatype</id>
          <name>OSS Sonatype repo (releases)</name>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>false</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://oss.sonatype.org/content/repositories/releases/</url>
        </repository>

        <repository>
          <id>sonatype-snapshots</id>
          <name>OSS Sonatype repo (snapshots)</name>
          <releases>
            <enabled>false</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>

        <repository>
          <id>sonatype-apache</id>
          <name>Apache repo (releases)</name>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>false</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://repository.apache.org/releases/</url>
        </repository>

        <repository>
          <id>apache-snapshots</id>
          <name>ASF repo (snapshots)</name>
          <releases>
            <enabled>false</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://repository.apache.org/snapshots/</url>
        </repository>

        <repository>
          <id>codehaus-snapshots</id>
          <name>Codehaus (snapshots)</name>
          <releases>
            <enabled>false</enabled>
            <updatePolicy>always</updatePolicy>
            <checksumPolicy>warn</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://nexus.codehaus.org/snapshots/</url>
        </repository>
      </repositories>
    </profile>
  </profiles>

  <!-- remove the mirrors for now as VMs are based in the US -->
  <!-- <mirrors>
    <mirror>
      <id>travis-ci-central</id>
      <name>Travis CI Central mirror</name>
      <url>http://maven.mirrors.travis-ci.org/nexus/content/repositories/central/</url>
      <mirrorOf>central</mirrorOf>
    </mirror>

    <mirror>
      <id>travis-ci-sonatype</id>
      <name>Travis CI oss.sonatype.org mirror</name>
      <url>http://maven.mirrors.travis-ci.org/nexus/content/repositories/sonatype/</url>
      <mirrorOf>sonatype</mirrorOf>
    </mirror>

    <mirror>
      <id>travis-ci-sonatype-snapshots</id>
      <name>Travis CI oss.sonatype.org mirror (snapshots)</name>
      <url>http://maven.mirrors.travis-ci.org/nexus/content/repositories/sonatype-snapshots/</url>
      <mirrorOf>sonatype-snapshots</mirrorOf>
    </mirror>

    <mirror>
      <id>travis-ci-apache</id>
      <name>Travis CI repository.apache.org mirror (releases)</name>
      <url>http://maven.mirrors.travis-ci.org/nexus/content/repositories/apache/</url>
      <mirrorOf>apache</mirrorOf>
    </mirror>

    <mirror>
      <id>travis-ci-apache-snapshots</id>
      <name>Travis CI repository.apache.org mirror (snapshots)</name>
      <url>http://maven.mirrors.travis-ci.org/nexus/content/repositories/apache-snapshots/</url>
      <mirrorOf>sonatype-snapshots</mirrorOf>
    </mirror>

    <mirror>
      <id>travis-ci-codehaus-snapshots</id>
      <name>Travis CI Codehaus mirror (snapshots)</name>
      <url>http://maven.mirrors.travis-ci.org/nexus/content/repositories/codehaus-snapshots/</url>
      <mirrorOf>codehaus-snapshots</mirrorOf>
    </mirror>
  </mirrors> -->
</settings>
```

I see nothing that we need to retain.

**Comment by kennknowles** [comment]
R: @jbonofre you might also have some opinion about the best way to deal with this. Now that Travis is caching, it is less of an issue. But it still makes sense to time out in a couple seconds rather than multiple minutes, to allow retry to be effective.

**Comment by dhalperi** [comment]
LGTM

**Pull request merged**
