### PR TITLE
[BEAM-493] Modify examples pom to add precommit execution profile.

### PR DESCRIPTION
**Pull request by jasonkuster**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @dhalperi @amitsela @aljoscha 

After commit of this PR, Jenkins command will remove -DintegrationTestPipelineOptions and include instead '-P include-runners,jenkins-precommit'. All runners will run WordCountIT in precommit to ensure functionality.

Signed-off-by: Jason Kuster <jasonkuster@google.com>

### CODE REVIEW

**Comment by dhalperi** [comment]
"jason@google.com"? I don't think that's your email :p

**Comment by jasonkuster** [comment]
Yeah I don't know - git grabbed it from...somewhere?

**Comment by amitsela** [comment]
Oh, that explains things.... so "jasonkuster@google.com" is the way to ping you ?
I'd like to merge https://github.com/apache/incubator-beam/pull/897 before that and I'd be happy if you just took a look because it followed your advise on adding verifiers.

**Comment by aljoscha** [comment]
Looks good from me. This doesn't verify anything on Flink, though, because the `TestFlinkRunner` is not yet integrated with verifiers. It's still good to just see whether the program runs.

**Comment by dhalperi** [comment]
@jasonkuster : https://help.github.com/articles/setting-your-email-in-git/

**Comment by jasonkuster** [comment]
@amitsela That's the right email for me, yeah. Sorry for not chiming in on that PR yet - I was on vacation for the last 2 weeks :) Will do tomorrow.

**Comment by jasonkuster** [comment]
Done - will wait on #897 to be merged before merging this.

**Comment by amitsela** [comment]
LGTM and #897 is closed, so go ahead 😄

**Comment by lukecwik** [comment]
Merging

**Pull request closed without merging**
