### PR TITLE
Add snippet for standard sql

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @hadarhg PTAL

### CODE REVIEW

**Comment by sb2nov** [comment]
R: @aaltay PTAL

**Comment by aaltay** [comment]
LGTM

**Comment by sb2nov** [comment]
@robertwb please merge

**Comment by robertwb** [comment]
Shouldn't all snippets be tested?

**Comment by sb2nov** [comment]
The test for BigQuery is a no-op. https://github.com/apache/incubator-beam/blob/python-sdk/sdks/python/apache_beam/examples/snippets/snippets_test.py#L473 so I think we just don't run a BQ unittest.

**Comment by robertwb** [comment]
Ah, I see.

**Pull request closed without merging**
