### PR TITLE
[BEAM-151] Clean up reference to DataflowWorkerHarnessOptions

### PR DESCRIPTION
**Pull request by lukecwik**
This prevents moving DataflowWorkerHarnessOptions to Dataflow Runner maven
module.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @tgroh

**Comment by lukecwik** [comment]
@davor Should I backport this to Dataflow SDK?

**Comment by tgroh** [comment]
LGTM

**Comment by lukecwik** [comment]
@davor please merge this in

**Comment by davorbonaci** [comment]
This would break Beam codebase running on Cloud Dataflow; let's not merge this right now.

**Comment by davorbonaci** [comment]
LGTM (self-merge), after adding a new worker label.

**Pull request closed without merging**
