### PR TITLE
[BEAM-289] Examples Use TypeDescriptors

### PR DESCRIPTION
**Pull request by eljefe6a**
Jira issue BEAM-289 Examples Use TypeDescriptors. Changed example code to use `TypeDescriptors`.

These could have used static imports to make the lines shorter, but we opted for the more understandable syntax.

### CODE REVIEW

**Comment by eljefe6a** [comment]
The build succeeded, but Jenkins timed out. cc @kennknowles

**Comment by kennknowles** [comment]
R: @kennknowles

I'm taking a look. One way you can kick Jenkins is to rebase against the current HEAD.

**Comment by kennknowles** [comment]
Any chance you can prune the other commits out of this pull request?

**Comment by eljefe6a** [comment]
Closing to use a different branch without the extra commits.

**Pull request closed without merging**
