### PR TITLE
[BEAM-498] Move PerKeyCombineFnRunner to runners-core

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @peihe seems there is no reason this needs to stay, right? `PerKeyCombineFnRunners` (the static util class) is already moved.

R: @lukecwik this has some references to `OldDoFn` so at least this gets them out of the SDK.

### CODE REVIEW

**Comment by peihe** [comment]
LGTM after fixing the import orders.

**Comment by kennknowles** [comment]
This will need a new worker image, which I will build as soon as it has LGTM from a committer.

**Comment by lukecwik** [comment]
LGTM, build new worker image and update PR to have Jenkins fire tests off again

**Comment by kennknowles** [comment]
Confirmed that the only failure is the known precommit issue with Apex. In particular, Dataflow integration tests passed.

**Pull request merged**
